BEGIN;
DO $$
DECLARE
  v_subject_id UUID;
  v_topic_id UUID;
  v_test_id BIGINT;
BEGIN
  SELECT id INTO v_subject_id FROM test_subjects WHERE name ILIKE '%cardio%' ORDER BY id LIMIT 1;
  IF v_subject_id IS NULL THEN
    INSERT INTO test_subjects (name, description) VALUES ('Cardiovascular System', 'Cardiovascular notes') RETURNING id INTO v_subject_id;
  END IF;
  SELECT id INTO v_topic_id FROM test_topics WHERE name = 'Anticoagulants' ORDER BY (SELECT COUNT(*) FROM test_questions q WHERE q.topic_id = test_topics.id) DESC, created_at ASC LIMIT 1;
  IF v_topic_id IS NULL THEN
    INSERT INTO test_topics (subject_id, name, description, status) VALUES (v_subject_id, 'Anticoagulants', 'Anticoagulant pharmacology, monitoring, antidotes, and bridge safety', 'published') RETURNING id INTO v_topic_id;
  END IF;
  SELECT id INTO v_test_id FROM tests WHERE is_active = true ORDER BY id LIMIT 1;
  IF v_test_id IS NULL THEN
    INSERT INTO tests (test_name, system_category, description, is_active)
    VALUES ('Cardiovascular System - Anticoagulants (Generated)', 'Cardiovascular System', 'Auto-generated NCLEX question set', true)
    RETURNING id INTO v_test_id;
  END IF;
  DELETE FROM test_questions WHERE topic_id = v_topic_id AND category = 'Anticoagulants - NCLEX';
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which finding best supports aPTT role in this anticoagulation scenario?', 'Which finding best supports aPTT role in this anticoagulation scenario?', '[{"id": "a", "text": "aPTT monitors heparin therapy; normal is about 30–40 sec and therapeutic heparin range is 45–80 sec."}, {"id": "b", "text": "Blood pressure alone is enough for all anticoagulant safety decisions."}, {"id": "c", "text": "Antidote planning is unnecessary when labs are elevated."}, {"id": "d", "text": "Therapeutic heparin aPTT is below 20 sec in this note."}]'::jsonb, '["a"]'::jsonb, 'Correct because aPTT monitors heparin therapy; normal is about 30–40 sec and therapeutic heparin range is 45–80 sec. Trend aPTT during heparin titration to avoid under- or over-anticoagulation.', 'Anticoagulants - NCLEX', false, 1, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse reviews current data. Which interpretation best matches PT/INR role?', 'The nurse reviews current data. Which interpretation best matches PT/INR role?', '[{"id": "a", "text": "Warfarin is monitored by aPTT only in this note."}, {"id": "b", "text": "INR goal for most patients is below 1 in this note."}, {"id": "c", "text": "Antidote planning is unnecessary when labs are elevated."}, {"id": "d", "text": "Use INR trends to guide safe warfarin dosing."}]'::jsonb, '["d"]'::jsonb, 'Correct because PT/INR monitor warfarin; INR therapeutic range is 2–3 for most indications. Use INR trends to guide safe warfarin dosing.', 'Anticoagulants - NCLEX', false, 2, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which clinical judgment is most accurate regarding heparin basics?', 'Which clinical judgment is most accurate regarding heparin basics?', '[{"id": "a", "text": "Heparin requires 2–5 days to start working in this note."}, {"id": "b", "text": "Heparin is oral only in this note."}, {"id": "c", "text": "Blood pressure alone is enough for all anticoagulant safety decisions."}, {"id": "d", "text": "Heparin is given IV or SubQ, has immediate IV onset, and is used for DVT, PE, ACS, dialysis, and perioperative prevention."}]'::jsonb, '["d"]'::jsonb, 'Correct because Heparin is given IV or SubQ, has immediate IV onset, and is used for DVT, PE, ACS, dialysis, and perioperative prevention. Heparin is chosen when rapid anticoagulation is needed.', 'Anticoagulants - NCLEX', false, 3, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'In urgent triage, which conclusion aligns with heparin antidote?', 'In urgent triage, which conclusion aligns with heparin antidote?', '[{"id": "a", "text": "Vitamin K is the heparin antidote in this note."}, {"id": "b", "text": "Blood pressure alone is enough for all anticoagulant safety decisions."}, {"id": "c", "text": "Prepare protamine quickly when significant heparin-associated bleeding risk is present."}, {"id": "d", "text": "Idarucizumab reverses heparin in this note."}]'::jsonb, '["c"]'::jsonb, 'Correct because Protamine sulfate is the antidote for heparin. Prepare protamine quickly when significant heparin-associated bleeding risk is present.', 'Anticoagulants - NCLEX', false, 4, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which statement most appropriately reflects aPTT above 80?', 'Which statement most appropriately reflects aPTT above 80?', '[{"id": "a", "text": "If aPTT exceeds 80 sec: stop infusion, assess vitals for bleeding, prepare protamine, then notify provider before giving antidote."}, {"id": "b", "text": "This pattern is more consistent with warfarin antidote."}, {"id": "c", "text": "Blood pressure alone is enough for all anticoagulant safety decisions."}, {"id": "d", "text": "Continue infusion and recheck next shift in this note."}]'::jsonb, '["a"]'::jsonb, 'Correct because If aPTT exceeds 80 sec: stop infusion, assess vitals for bleeding, prepare protamine, then notify provider before giving antidote. Follow sequence: stop, assess, prepare, call.', 'Anticoagulants - NCLEX', false, 5, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which finding best supports HIT recognition in this anticoagulation scenario?', 'Which finding best supports HIT recognition in this anticoagulation scenario?', '[{"id": "a", "text": "Antidote planning is unnecessary when labs are elevated."}, {"id": "b", "text": "HIT increases clotting risk paradoxically despite thrombocytopenia."}, {"id": "c", "text": "Blood pressure alone is enough for all anticoagulant safety decisions."}, {"id": "d", "text": "HIT primarily lowers clot risk in this note."}]'::jsonb, '["b"]'::jsonb, 'Correct because HIT is suspected when platelets drop more than 50% on heparin; stop heparin and switch to argatroban. HIT increases clotting risk paradoxically despite thrombocytopenia.', 'Anticoagulants - NCLEX', false, 6, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse reviews current data. Which interpretation best matches warfarin basics?', 'The nurse reviews current data. Which interpretation best matches warfarin basics?', '[{"id": "a", "text": "Warfarin is only used during surgery in this note."}, {"id": "b", "text": "This pattern is more consistent with warfarin teaching interactions."}, {"id": "c", "text": "Warfarin is oral and has delayed onset of 2–5 days, so it is used for long-term anticoagulation."}, {"id": "d", "text": "Warfarin has immediate IV onset in this note."}]'::jsonb, '["c"]'::jsonb, 'Correct because Warfarin is oral and has delayed onset of 2–5 days, so it is used for long-term anticoagulation. Delayed onset drives need for bridging in acute clot treatment.', 'Anticoagulants - NCLEX', false, 7, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which clinical judgment is most accurate regarding warfarin therapeutic range?', 'Which clinical judgment is most accurate regarding warfarin therapeutic range?', '[{"id": "a", "text": "Blood pressure alone is enough for all anticoagulant safety decisions."}, {"id": "b", "text": "Valve patients often require higher anticoagulation intensity."}, {"id": "c", "text": "Antidote planning is unnecessary when labs are elevated."}, {"id": "d", "text": "Warfarin has one fixed INR for all patients in this note."}]'::jsonb, '["b"]'::jsonb, 'Correct because Therapeutic INR is usually 2–3, but mechanical heart valves often target 2.5–3.5. Valve patients often require higher anticoagulation intensity.', 'Anticoagulants - NCLEX', false, 8, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'In urgent triage, which conclusion aligns with warfarin antidote?', 'In urgent triage, which conclusion aligns with warfarin antidote?', '[{"id": "a", "text": "Vitamin K (phytonadione) is the reversal agent for warfarin."}, {"id": "b", "text": "Andexanet alfa reverses warfarin in this note."}, {"id": "c", "text": "Blood pressure alone is enough for all anticoagulant safety decisions."}, {"id": "d", "text": "Antidote planning is unnecessary when labs are elevated."}]'::jsonb, '["a"]'::jsonb, 'Correct because Vitamin K (phytonadione) is the reversal agent for warfarin. Know warfarin-vitamin K pair for rapid NCLEX decisions.', 'Anticoagulants - NCLEX', false, 9, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which statement most appropriately reflects warfarin teaching vitamin K?', 'Which statement most appropriately reflects warfarin teaching vitamin K?', '[{"id": "a", "text": "Antidote planning is unnecessary when labs are elevated."}, {"id": "b", "text": "This pattern is more consistent with bridge discontinuation rule."}, {"id": "c", "text": "Diet consistency prevents INR instability."}, {"id": "d", "text": "Vitamin K intake has no effect on warfarin in this note."}]'::jsonb, '["c"]'::jsonb, 'Correct because Patients should keep vitamin K intake consistent rather than eliminating leafy greens entirely. Diet consistency prevents INR instability.', 'Anticoagulants - NCLEX', false, 10, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which finding best supports warfarin teaching interactions in this anticoagulation scenario?', 'Which finding best supports warfarin teaching interactions in this anticoagulation scenario?', '[{"id": "a", "text": "Antidote planning is unnecessary when labs are elevated."}, {"id": "b", "text": "Blood pressure alone is enough for all anticoagulant safety decisions."}, {"id": "c", "text": "Avoid NSAIDs and grapefruit while on warfarin due to increased bleeding risk or level changes."}, {"id": "d", "text": "Warfarin patients should take NSAIDs for routine pain in this note."}]'::jsonb, '["c"]'::jsonb, 'Correct because Avoid NSAIDs and grapefruit while on warfarin due to increased bleeding risk or level changes. Medication/food interaction review is a safety essential.', 'Anticoagulants - NCLEX', false, 11, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse reviews current data. Which interpretation best matches warfarin bleeding teaching?', 'The nurse reviews current data. Which interpretation best matches warfarin bleeding teaching?', '[{"id": "a", "text": "This pattern is more consistent with critical high-risk thresholds."}, {"id": "b", "text": "Blood pressure alone is enough for all anticoagulant safety decisions."}, {"id": "c", "text": "Medical alert ID is unnecessary in this note."}, {"id": "d", "text": "Early bleeding recognition prevents severe complications."}]'::jsonb, '["d"]'::jsonb, 'Correct because Teach patients to report unusual bleeding, hematuria, or blood in stool and wear a medical alert bracelet. Early bleeding recognition prevents severe complications.', 'Anticoagulants - NCLEX', false, 12, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which clinical judgment is most accurate regarding bridge overlap duration?', 'Which clinical judgment is most accurate regarding bridge overlap duration?', '[{"id": "a", "text": "Blood pressure alone is enough for all anticoagulant safety decisions."}, {"id": "b", "text": "This pattern is more consistent with STOP ASSESS PREPARE CALL."}, {"id": "c", "text": "Stop heparin the same day warfarin starts in this note."}, {"id": "d", "text": "When transitioning heparin to warfarin, overlap both drugs for at least 5–7 days."}]'::jsonb, '["d"]'::jsonb, 'Correct because When transitioning heparin to warfarin, overlap both drugs for at least 5–7 days. Bridge prevents gaps in anticoagulation while warfarin effect develops.', 'Anticoagulants - NCLEX', false, 13, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'In urgent triage, which conclusion aligns with bridge discontinuation rule?', 'In urgent triage, which conclusion aligns with bridge discontinuation rule?', '[{"id": "a", "text": "Heparin stops before INR reaches goal in this note."}, {"id": "b", "text": "Blood pressure alone is enough for all anticoagulant safety decisions."}, {"id": "c", "text": "Require stable therapeutic INR before removing rapid-acting anticoagulant."}, {"id": "d", "text": "This pattern is more consistent with internal bleeding signs."}]'::jsonb, '["c"]'::jsonb, 'Correct because Do not stop heparin until INR is therapeutic 2–3 for two consecutive days. Require stable therapeutic INR before removing rapid-acting anticoagulant.', 'Anticoagulants - NCLEX', false, 14, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which statement most appropriately reflects stable INR follow-up?', 'Which statement most appropriately reflects stable INR follow-up?', '[{"id": "a", "text": "Antidote planning is unnecessary when labs are elevated."}, {"id": "b", "text": "This pattern is more consistent with dabigatran profile."}, {"id": "c", "text": "Once INR is stable, warfarin monitoring can be every 3 weeks per note."}, {"id": "d", "text": "Warfarin monitoring is discontinued once stable in this note."}]'::jsonb, '["c"]'::jsonb, 'Correct because Once INR is stable, warfarin monitoring can be every 3 weeks per note. Stable outpatient monitoring still requires routine checks.', 'Anticoagulants - NCLEX', false, 15, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which finding best supports critical high-risk thresholds in this anticoagulation scenario?', 'Which finding best supports critical high-risk thresholds in this anticoagulation scenario?', '[{"id": "a", "text": "Blood pressure alone is enough for all anticoagulant safety decisions."}, {"id": "b", "text": "This pattern is more consistent with factor Xa inhibitors profile."}, {"id": "c", "text": "Recognize threshold triggers for urgent safety response."}, {"id": "d", "text": "Antidote planning is unnecessary when labs are elevated."}]'::jsonb, '["c"]'::jsonb, 'Correct because INR greater than 4 or aPTT greater than 80 sec indicates high hemorrhage risk and immediate intervention. Recognize threshold triggers for urgent safety response.', 'Anticoagulants - NCLEX', false, 16, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse reviews current data. Which interpretation best matches STOP ASSESS PREPARE CALL?', 'The nurse reviews current data. Which interpretation best matches STOP ASSESS PREPARE CALL?', '[{"id": "a", "text": "NCLEX priority order for suspected internal bleeding is STOP anticoagulant, ASSESS vitals/bleeding, PREPARE antidote, then CALL provider."}, {"id": "b", "text": "Give antidote before assessment in this note."}, {"id": "c", "text": "Antidote planning is unnecessary when labs are elevated."}, {"id": "d", "text": "This pattern is more consistent with enoxaparin profile."}]'::jsonb, '["a"]'::jsonb, 'Correct because NCLEX priority order for suspected internal bleeding is STOP anticoagulant, ASSESS vitals/bleeding, PREPARE antidote, then CALL provider. Sequence discipline improves emergency anticoagulant safety.', 'Anticoagulants - NCLEX', false, 17, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which clinical judgment is most accurate regarding internal bleeding signs?', 'Which clinical judgment is most accurate regarding internal bleeding signs?', '[{"id": "a", "text": "Combine hemodynamic and symptom clues for early detection."}, {"id": "b", "text": "This pattern is more consistent with lab-memory rule."}, {"id": "c", "text": "Hematuria is expected and not concerning in this note."}, {"id": "d", "text": "Bradycardia with hypertension is classic anticoagulant bleed in this note."}]'::jsonb, '["a"]'::jsonb, 'Correct because Signs of internal bleeding include low BP, high HR, melena, hematuria, and severe headache suggesting intracranial bleed. Combine hemodynamic and symptom clues for early detection.', 'Anticoagulants - NCLEX', false, 18, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'In urgent triage, which conclusion aligns with dabigatran profile?', 'In urgent triage, which conclusion aligns with dabigatran profile?', '[{"id": "a", "text": "Dabigatran is factor Xa inhibitor in this note."}, {"id": "b", "text": "Antidote planning is unnecessary when labs are elevated."}, {"id": "c", "text": "Protamine is dabigatran antidote in this note."}, {"id": "d", "text": "Dabigatran is a direct thrombin inhibitor; monitor renal function and reverse with idarucizumab."}]'::jsonb, '["d"]'::jsonb, 'Correct because Dabigatran is a direct thrombin inhibitor; monitor renal function and reverse with idarucizumab. Match class and antidote accurately in urgent reversal decisions.', 'Anticoagulants - NCLEX', false, 19, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which statement most appropriately reflects factor Xa inhibitors profile?', 'Which statement most appropriately reflects factor Xa inhibitors profile?', '[{"id": "a", "text": "Idarucizumab reverses apixaban in this note."}, {"id": "b", "text": "This pattern is more consistent with integrated anticoagulant safety."}, {"id": "c", "text": "Xa inhibitors are monitored by daily INR in this note."}, {"id": "d", "text": "Differentiate Xa inhibitor reversal from other anticoagulants."}]'::jsonb, '["d"]'::jsonb, 'Correct because Rivaroxaban and apixaban are factor Xa inhibitors; monitor renal function/CBC and reverse with andexanet alfa. Differentiate Xa inhibitor reversal from other anticoagulants.', 'Anticoagulants - NCLEX', false, 20, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which finding best supports enoxaparin profile in this anticoagulation scenario?', 'Which finding best supports enoxaparin profile in this anticoagulation scenario?', '[{"id": "a", "text": "This pattern is more consistent with aPTT role."}, {"id": "b", "text": "Enoxaparin is monitored by INR only in this note."}, {"id": "c", "text": "Blood pressure alone is enough for all anticoagulant safety decisions."}, {"id": "d", "text": "Enoxaparin is LMWH with anti-Xa monitoring if needed; protamine provides partial reversal."}]'::jsonb, '["d"]'::jsonb, 'Correct because Enoxaparin is LMWH with anti-Xa monitoring if needed; protamine provides partial reversal. Understand that reversal is partial, not complete.', 'Anticoagulants - NCLEX', false, 21, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse reviews current data. Which interpretation best matches lab-memory rule?', 'The nurse reviews current data. Which interpretation best matches lab-memory rule?', '[{"id": "a", "text": "This pattern is more consistent with PT/INR role."}, {"id": "b", "text": "Blood pressure alone is enough for all anticoagulant safety decisions."}, {"id": "c", "text": "Use mnemonic for rapid exam-time lab matching."}, {"id": "d", "text": "Antidote planning is unnecessary when labs are elevated."}]'::jsonb, '["c"]'::jsonb, 'Correct because Memory cue: H for Heparin equals aPTT; W for Warfarin equals INR. Use mnemonic for rapid exam-time lab matching.', 'Anticoagulants - NCLEX', false, 22, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which clinical judgment is most accurate regarding monitoring distinction?', 'Which clinical judgment is most accurate regarding monitoring distinction?', '[{"id": "a", "text": "Warfarin titration uses q6h aPTT in this note."}, {"id": "b", "text": "Blood pressure alone is enough for all anticoagulant safety decisions."}, {"id": "c", "text": "Warfarin monitoring is INR/PT only, while heparin titration requires frequent aPTT checks every 6 hours."}, {"id": "d", "text": "Antidote planning is unnecessary when labs are elevated."}]'::jsonb, '["c"]'::jsonb, 'Correct because Warfarin monitoring is INR/PT only, while heparin titration requires frequent aPTT checks every 6 hours. Do not interchange heparin and warfarin monitoring labs.', 'Anticoagulants - NCLEX', false, 23, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'In urgent triage, which conclusion aligns with integrated anticoagulant safety?', 'In urgent triage, which conclusion aligns with integrated anticoagulant safety?', '[{"id": "a", "text": "Most preventable harm comes from delayed recognition and delayed response."}, {"id": "b", "text": "Escalation sequence is optional in this note."}, {"id": "c", "text": "This pattern is more consistent with heparin antidote."}, {"id": "d", "text": "Blood pressure alone is enough for all anticoagulant safety decisions."}]'::jsonb, '["a"]'::jsonb, 'Correct because Safe anticoagulant care requires correct lab-drug pairing, bleeding surveillance, antidote readiness, and structured escalation. Most preventable harm comes from delayed recognition and delayed response.', 'Anticoagulants - NCLEX', false, 24, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which statement most appropriately reflects aPTT role?', 'Which statement most appropriately reflects aPTT role?', '[{"id": "a", "text": "aPTT is the primary warfarin monitoring test in this note."}, {"id": "b", "text": "Antidote planning is unnecessary when labs are elevated."}, {"id": "c", "text": "aPTT monitors heparin therapy; normal is about 30–40 sec and therapeutic heparin range is 45–80 sec."}, {"id": "d", "text": "Blood pressure alone is enough for all anticoagulant safety decisions."}]'::jsonb, '["c"]'::jsonb, 'Correct because aPTT monitors heparin therapy; normal is about 30–40 sec and therapeutic heparin range is 45–80 sec. Trend aPTT during heparin titration to avoid under- or over-anticoagulation.', 'Anticoagulants - NCLEX', false, 25, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which finding best supports PT/INR role in this anticoagulation scenario?', 'Which finding best supports PT/INR role in this anticoagulation scenario?', '[{"id": "a", "text": "This pattern is more consistent with HIT recognition."}, {"id": "b", "text": "Warfarin is monitored by aPTT only in this note."}, {"id": "c", "text": "Antidote planning is unnecessary when labs are elevated."}, {"id": "d", "text": "Use INR trends to guide safe warfarin dosing."}]'::jsonb, '["d"]'::jsonb, 'Correct because PT/INR monitor warfarin; INR therapeutic range is 2–3 for most indications. Use INR trends to guide safe warfarin dosing.', 'Anticoagulants - NCLEX', false, 26, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse reviews current data. Which interpretation best matches heparin basics?', 'The nurse reviews current data. Which interpretation best matches heparin basics?', '[{"id": "a", "text": "Heparin is oral only in this note."}, {"id": "b", "text": "Heparin requires 2–5 days to start working in this note."}, {"id": "c", "text": "Antidote planning is unnecessary when labs are elevated."}, {"id": "d", "text": "Heparin is given IV or SubQ, has immediate IV onset, and is used for DVT, PE, ACS, dialysis, and perioperative prevention."}]'::jsonb, '["d"]'::jsonb, 'Correct because Heparin is given IV or SubQ, has immediate IV onset, and is used for DVT, PE, ACS, dialysis, and perioperative prevention. Heparin is chosen when rapid anticoagulation is needed.', 'Anticoagulants - NCLEX', false, 27, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which clinical judgment is most accurate regarding heparin antidote?', 'Which clinical judgment is most accurate regarding heparin antidote?', '[{"id": "a", "text": "Vitamin K is the heparin antidote in this note."}, {"id": "b", "text": "This pattern is more consistent with warfarin therapeutic range."}, {"id": "c", "text": "Blood pressure alone is enough for all anticoagulant safety decisions."}, {"id": "d", "text": "Prepare protamine quickly when significant heparin-associated bleeding risk is present."}]'::jsonb, '["d"]'::jsonb, 'Correct because Protamine sulfate is the antidote for heparin. Prepare protamine quickly when significant heparin-associated bleeding risk is present.', 'Anticoagulants - NCLEX', false, 28, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'In urgent triage, which conclusion aligns with aPTT above 80?', 'In urgent triage, which conclusion aligns with aPTT above 80?', '[{"id": "a", "text": "If aPTT exceeds 80 sec: stop infusion, assess vitals for bleeding, prepare protamine, then notify provider before giving antidote."}, {"id": "b", "text": "Antidote planning is unnecessary when labs are elevated."}, {"id": "c", "text": "Continue infusion and recheck next shift in this note."}, {"id": "d", "text": "Blood pressure alone is enough for all anticoagulant safety decisions."}]'::jsonb, '["a"]'::jsonb, 'Correct because If aPTT exceeds 80 sec: stop infusion, assess vitals for bleeding, prepare protamine, then notify provider before giving antidote. Follow sequence: stop, assess, prepare, call.', 'Anticoagulants - NCLEX', false, 29, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which statement most appropriately reflects HIT recognition?', 'Which statement most appropriately reflects HIT recognition?', '[{"id": "a", "text": "Blood pressure alone is enough for all anticoagulant safety decisions."}, {"id": "b", "text": "HIT increases clotting risk paradoxically despite thrombocytopenia."}, {"id": "c", "text": "This pattern is more consistent with warfarin teaching vitamin K."}, {"id": "d", "text": "HIT primarily lowers clot risk in this note."}]'::jsonb, '["b"]'::jsonb, 'Correct because HIT is suspected when platelets drop more than 50% on heparin; stop heparin and switch to argatroban. HIT increases clotting risk paradoxically despite thrombocytopenia.', 'Anticoagulants - NCLEX', false, 30, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which finding best supports warfarin basics in this anticoagulation scenario?', 'Which finding best supports warfarin basics in this anticoagulation scenario?', '[{"id": "a", "text": "This pattern is more consistent with warfarin teaching interactions."}, {"id": "b", "text": "Warfarin is oral and has delayed onset of 2–5 days, so it is used for long-term anticoagulation."}, {"id": "c", "text": "Blood pressure alone is enough for all anticoagulant safety decisions."}, {"id": "d", "text": "Warfarin has immediate IV onset in this note."}]'::jsonb, '["b"]'::jsonb, 'Correct because Warfarin is oral and has delayed onset of 2–5 days, so it is used for long-term anticoagulation. Delayed onset drives need for bridging in acute clot treatment.', 'Anticoagulants - NCLEX', false, 31, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse reviews current data. Which interpretation best matches warfarin therapeutic range?', 'The nurse reviews current data. Which interpretation best matches warfarin therapeutic range?', '[{"id": "a", "text": "Mechanical valve INR target is below 2 in this note."}, {"id": "b", "text": "Valve patients often require higher anticoagulation intensity."}, {"id": "c", "text": "Warfarin has one fixed INR for all patients in this note."}, {"id": "d", "text": "This pattern is more consistent with warfarin bleeding teaching."}]'::jsonb, '["b"]'::jsonb, 'Correct because Therapeutic INR is usually 2–3, but mechanical heart valves often target 2.5–3.5. Valve patients often require higher anticoagulation intensity.', 'Anticoagulants - NCLEX', false, 32, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which clinical judgment is most accurate regarding warfarin antidote?', 'Which clinical judgment is most accurate regarding warfarin antidote?', '[{"id": "a", "text": "Vitamin K (phytonadione) is the reversal agent for warfarin."}, {"id": "b", "text": "Andexanet alfa reverses warfarin in this note."}, {"id": "c", "text": "This pattern is more consistent with bridge overlap duration."}, {"id": "d", "text": "Protamine reverses warfarin in this note."}]'::jsonb, '["a"]'::jsonb, 'Correct because Vitamin K (phytonadione) is the reversal agent for warfarin. Know warfarin-vitamin K pair for rapid NCLEX decisions.', 'Anticoagulants - NCLEX', false, 33, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'In urgent triage, which conclusion aligns with warfarin teaching vitamin K?', 'In urgent triage, which conclusion aligns with warfarin teaching vitamin K?', '[{"id": "a", "text": "Blood pressure alone is enough for all anticoagulant safety decisions."}, {"id": "b", "text": "Antidote planning is unnecessary when labs are elevated."}, {"id": "c", "text": "Leafy greens must be eliminated forever in this note."}, {"id": "d", "text": "Diet consistency prevents INR instability."}]'::jsonb, '["d"]'::jsonb, 'Correct because Patients should keep vitamin K intake consistent rather than eliminating leafy greens entirely. Diet consistency prevents INR instability.', 'Anticoagulants - NCLEX', false, 34, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which statement most appropriately reflects warfarin teaching interactions?', 'Which statement most appropriately reflects warfarin teaching interactions?', '[{"id": "a", "text": "Warfarin patients should take NSAIDs for routine pain in this note."}, {"id": "b", "text": "Avoid NSAIDs and grapefruit while on warfarin due to increased bleeding risk or level changes."}, {"id": "c", "text": "Grapefruit lowers warfarin effect safely in this note."}, {"id": "d", "text": "Blood pressure alone is enough for all anticoagulant safety decisions."}]'::jsonb, '["b"]'::jsonb, 'Correct because Avoid NSAIDs and grapefruit while on warfarin due to increased bleeding risk or level changes. Medication/food interaction review is a safety essential.', 'Anticoagulants - NCLEX', false, 35, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which finding best supports warfarin bleeding teaching in this anticoagulation scenario?', 'Which finding best supports warfarin bleeding teaching in this anticoagulation scenario?', '[{"id": "a", "text": "Bleeding signs can be ignored if INR is therapeutic in this note."}, {"id": "b", "text": "Medical alert ID is unnecessary in this note."}, {"id": "c", "text": "Blood pressure alone is enough for all anticoagulant safety decisions."}, {"id": "d", "text": "Early bleeding recognition prevents severe complications."}]'::jsonb, '["d"]'::jsonb, 'Correct because Teach patients to report unusual bleeding, hematuria, or blood in stool and wear a medical alert bracelet. Early bleeding recognition prevents severe complications.', 'Anticoagulants - NCLEX', false, 36, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse reviews current data. Which interpretation best matches bridge overlap duration?', 'The nurse reviews current data. Which interpretation best matches bridge overlap duration?', '[{"id": "a", "text": "This pattern is more consistent with STOP ASSESS PREPARE CALL."}, {"id": "b", "text": "When transitioning heparin to warfarin, overlap both drugs for at least 5–7 days."}, {"id": "c", "text": "Stop heparin the same day warfarin starts in this note."}, {"id": "d", "text": "Overlap is unnecessary if INR is pending in this note."}]'::jsonb, '["b"]'::jsonb, 'Correct because When transitioning heparin to warfarin, overlap both drugs for at least 5–7 days. Bridge prevents gaps in anticoagulation while warfarin effect develops.', 'Anticoagulants - NCLEX', false, 37, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which clinical judgment is most accurate regarding bridge discontinuation rule?', 'Which clinical judgment is most accurate regarding bridge discontinuation rule?', '[{"id": "a", "text": "Heparin stops after one therapeutic INR in this note."}, {"id": "b", "text": "Antidote planning is unnecessary when labs are elevated."}, {"id": "c", "text": "Require stable therapeutic INR before removing rapid-acting anticoagulant."}, {"id": "d", "text": "This pattern is more consistent with internal bleeding signs."}]'::jsonb, '["c"]'::jsonb, 'Correct because Do not stop heparin until INR is therapeutic 2–3 for two consecutive days. Require stable therapeutic INR before removing rapid-acting anticoagulant.', 'Anticoagulants - NCLEX', false, 38, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'In urgent triage, which conclusion aligns with stable INR follow-up?', 'In urgent triage, which conclusion aligns with stable INR follow-up?', '[{"id": "a", "text": "Warfarin monitoring is discontinued once stable in this note."}, {"id": "b", "text": "INR should be checked yearly only in this note."}, {"id": "c", "text": "This pattern is more consistent with dabigatran profile."}, {"id": "d", "text": "Once INR is stable, warfarin monitoring can be every 3 weeks per note."}]'::jsonb, '["d"]'::jsonb, 'Correct because Once INR is stable, warfarin monitoring can be every 3 weeks per note. Stable outpatient monitoring still requires routine checks.', 'Anticoagulants - NCLEX', false, 39, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which statement most appropriately reflects critical high-risk thresholds?', 'Which statement most appropriately reflects critical high-risk thresholds?', '[{"id": "a", "text": "Recognize threshold triggers for urgent safety response."}, {"id": "b", "text": "Blood pressure alone is enough for all anticoagulant safety decisions."}, {"id": "c", "text": "Antidote planning is unnecessary when labs are elevated."}, {"id": "d", "text": "This pattern is more consistent with factor Xa inhibitors profile."}]'::jsonb, '["a"]'::jsonb, 'Correct because INR greater than 4 or aPTT greater than 80 sec indicates high hemorrhage risk and immediate intervention. Recognize threshold triggers for urgent safety response.', 'Anticoagulants - NCLEX', false, 40, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which finding best supports STOP ASSESS PREPARE CALL in this anticoagulation scenario?', 'Which finding best supports STOP ASSESS PREPARE CALL in this anticoagulation scenario?', '[{"id": "a", "text": "Blood pressure alone is enough for all anticoagulant safety decisions."}, {"id": "b", "text": "Give antidote before assessment in this note."}, {"id": "c", "text": "This pattern is more consistent with enoxaparin profile."}, {"id": "d", "text": "NCLEX priority order for suspected internal bleeding is STOP anticoagulant, ASSESS vitals/bleeding, PREPARE antidote, then CALL provider."}]'::jsonb, '["d"]'::jsonb, 'Correct because NCLEX priority order for suspected internal bleeding is STOP anticoagulant, ASSESS vitals/bleeding, PREPARE antidote, then CALL provider. Sequence discipline improves emergency anticoagulant safety.', 'Anticoagulants - NCLEX', false, 41, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse reviews current data. Which interpretation best matches internal bleeding signs?', 'The nurse reviews current data. Which interpretation best matches internal bleeding signs?', '[{"id": "a", "text": "Bradycardia with hypertension is classic anticoagulant bleed in this note."}, {"id": "b", "text": "Combine hemodynamic and symptom clues for early detection."}, {"id": "c", "text": "Antidote planning is unnecessary when labs are elevated."}, {"id": "d", "text": "Hematuria is expected and not concerning in this note."}]'::jsonb, '["b"]'::jsonb, 'Correct because Signs of internal bleeding include low BP, high HR, melena, hematuria, and severe headache suggesting intracranial bleed. Combine hemodynamic and symptom clues for early detection.', 'Anticoagulants - NCLEX', false, 42, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which clinical judgment is most accurate regarding dabigatran profile?', 'Which clinical judgment is most accurate regarding dabigatran profile?', '[{"id": "a", "text": "Protamine is dabigatran antidote in this note."}, {"id": "b", "text": "Dabigatran is factor Xa inhibitor in this note."}, {"id": "c", "text": "Dabigatran is a direct thrombin inhibitor; monitor renal function and reverse with idarucizumab."}, {"id": "d", "text": "Blood pressure alone is enough for all anticoagulant safety decisions."}]'::jsonb, '["c"]'::jsonb, 'Correct because Dabigatran is a direct thrombin inhibitor; monitor renal function and reverse with idarucizumab. Match class and antidote accurately in urgent reversal decisions.', 'Anticoagulants - NCLEX', false, 43, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'In urgent triage, which conclusion aligns with factor Xa inhibitors profile?', 'In urgent triage, which conclusion aligns with factor Xa inhibitors profile?', '[{"id": "a", "text": "Differentiate Xa inhibitor reversal from other anticoagulants."}, {"id": "b", "text": "Xa inhibitors are monitored by daily INR in this note."}, {"id": "c", "text": "Antidote planning is unnecessary when labs are elevated."}, {"id": "d", "text": "Idarucizumab reverses apixaban in this note."}]'::jsonb, '["a"]'::jsonb, 'Correct because Rivaroxaban and apixaban are factor Xa inhibitors; monitor renal function/CBC and reverse with andexanet alfa. Differentiate Xa inhibitor reversal from other anticoagulants.', 'Anticoagulants - NCLEX', false, 44, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which statement most appropriately reflects enoxaparin profile?', 'Which statement most appropriately reflects enoxaparin profile?', '[{"id": "a", "text": "Enoxaparin is LMWH with anti-Xa monitoring if needed; protamine provides partial reversal."}, {"id": "b", "text": "Blood pressure alone is enough for all anticoagulant safety decisions."}, {"id": "c", "text": "Enoxaparin is fully reversed by vitamin K in this note."}, {"id": "d", "text": "Enoxaparin is monitored by INR only in this note."}]'::jsonb, '["a"]'::jsonb, 'Correct because Enoxaparin is LMWH with anti-Xa monitoring if needed; protamine provides partial reversal. Understand that reversal is partial, not complete.', 'Anticoagulants - NCLEX', false, 45, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which finding best supports lab-memory rule in this anticoagulation scenario?', 'Which finding best supports lab-memory rule in this anticoagulation scenario?', '[{"id": "a", "text": "Antidote planning is unnecessary when labs are elevated."}, {"id": "b", "text": "Heparin pairs with INR in this note."}, {"id": "c", "text": "Warfarin pairs only with anti-Xa in this note."}, {"id": "d", "text": "Use mnemonic for rapid exam-time lab matching."}]'::jsonb, '["d"]'::jsonb, 'Correct because Memory cue: H for Heparin equals aPTT; W for Warfarin equals INR. Use mnemonic for rapid exam-time lab matching.', 'Anticoagulants - NCLEX', false, 46, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse reviews current data. Which interpretation best matches monitoring distinction?', 'The nurse reviews current data. Which interpretation best matches monitoring distinction?', '[{"id": "a", "text": "Antidote planning is unnecessary when labs are elevated."}, {"id": "b", "text": "Warfarin titration uses q6h aPTT in this note."}, {"id": "c", "text": "Warfarin monitoring is INR/PT only, while heparin titration requires frequent aPTT checks every 6 hours."}, {"id": "d", "text": "This pattern is more consistent with heparin basics."}]'::jsonb, '["c"]'::jsonb, 'Correct because Warfarin monitoring is INR/PT only, while heparin titration requires frequent aPTT checks every 6 hours. Do not interchange heparin and warfarin monitoring labs.', 'Anticoagulants - NCLEX', false, 47, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which clinical judgment is most accurate regarding integrated anticoagulant safety?', 'Which clinical judgment is most accurate regarding integrated anticoagulant safety?', '[{"id": "a", "text": "Escalation sequence is optional in this note."}, {"id": "b", "text": "Most preventable harm comes from delayed recognition and delayed response."}, {"id": "c", "text": "Anticoagulants do not require routine monitoring in this note."}, {"id": "d", "text": "Blood pressure alone is enough for all anticoagulant safety decisions."}]'::jsonb, '["b"]'::jsonb, 'Correct because Safe anticoagulant care requires correct lab-drug pairing, bleeding surveillance, antidote readiness, and structured escalation. Most preventable harm comes from delayed recognition and delayed response.', 'Anticoagulants - NCLEX', false, 48, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'In urgent triage, which conclusion aligns with aPTT role?', 'In urgent triage, which conclusion aligns with aPTT role?', '[{"id": "a", "text": "This pattern is more consistent with aPTT above 80."}, {"id": "b", "text": "Blood pressure alone is enough for all anticoagulant safety decisions."}, {"id": "c", "text": "aPTT monitors heparin therapy; normal is about 30–40 sec and therapeutic heparin range is 45–80 sec."}, {"id": "d", "text": "Antidote planning is unnecessary when labs are elevated."}]'::jsonb, '["c"]'::jsonb, 'Correct because aPTT monitors heparin therapy; normal is about 30–40 sec and therapeutic heparin range is 45–80 sec. Trend aPTT during heparin titration to avoid under- or over-anticoagulation.', 'Anticoagulants - NCLEX', false, 49, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which statement most appropriately reflects PT/INR role?', 'Which statement most appropriately reflects PT/INR role?', '[{"id": "a", "text": "Antidote planning is unnecessary when labs are elevated."}, {"id": "b", "text": "Warfarin is monitored by aPTT only in this note."}, {"id": "c", "text": "This pattern is more consistent with HIT recognition."}, {"id": "d", "text": "Use INR trends to guide safe warfarin dosing."}]'::jsonb, '["d"]'::jsonb, 'Correct because PT/INR monitor warfarin; INR therapeutic range is 2–3 for most indications. Use INR trends to guide safe warfarin dosing.', 'Anticoagulants - NCLEX', false, 50, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'A patient is evaluated for aPTT role. Which findings/actions are appropriate? (Select all that apply)', 'A patient is evaluated for aPTT role. Which findings/actions are appropriate? (Select all that apply)', '[{"id": "a", "text": "Therapeutic heparin aPTT is below 20 sec in this note."}, {"id": "b", "text": "Normal aPTT is around 30–40 sec."}, {"id": "c", "text": "aPTT is the primary warfarin monitoring test in this note."}, {"id": "d", "text": "Therapeutic heparin aPTT is 45–80 sec."}, {"id": "e", "text": "aPTT is used to monitor heparin."}]'::jsonb, '["b", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: aPTT monitors heparin therapy; normal is about 30–40 sec and therapeutic heparin range is 45–80 sec.', 'Anticoagulants - NCLEX', true, 51, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'For management involving PT/INR role, which statements are correct? (Select all that apply)', 'For management involving PT/INR role, which statements are correct? (Select all that apply)', '[{"id": "a", "text": "Warfarin is monitored by aPTT only in this note."}, {"id": "b", "text": "INR goal for most patients is below 1 in this note."}, {"id": "c", "text": "INR is used for warfarin monitoring."}, {"id": "d", "text": "PT is associated with warfarin monitoring in this note."}, {"id": "e", "text": "Typical therapeutic INR is 2–3."}]'::jsonb, '["c", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: PT/INR monitor warfarin; INR therapeutic range is 2–3 for most indications.', 'Anticoagulants - NCLEX', true, 52, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse plans interventions around heparin basics. Which items belong in the plan? (Select all that apply)', 'The nurse plans interventions around heparin basics. Which items belong in the plan? (Select all that apply)', '[{"id": "a", "text": "DVT/PE/ACS are listed uses."}, {"id": "b", "text": "Heparin can be IV or SubQ."}, {"id": "c", "text": "IV heparin onset is immediate."}, {"id": "d", "text": "Heparin requires 2–5 days to start working in this note."}, {"id": "e", "text": "Heparin is oral only in this note."}]'::jsonb, '["a", "b", "c"]'::jsonb, 'Correct selections align with note-based facts: Heparin is given IV or SubQ, has immediate IV onset, and is used for DVT, PE, ACS, dialysis, and perioperative prevention.', 'Anticoagulants - NCLEX', true, 53, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'During reassessment, which observations support heparin antidote? (Select all that apply)', 'During reassessment, which observations support heparin antidote? (Select all that apply)', '[{"id": "a", "text": "Vitamin K is the heparin antidote in this note."}, {"id": "b", "text": "Protamine is linked with heparin overdose management."}, {"id": "c", "text": "Idarucizumab reverses heparin in this note."}, {"id": "d", "text": "Heparin has a named antidote in this note."}, {"id": "e", "text": "Protamine sulfate reverses heparin."}]'::jsonb, '["b", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: Protamine sulfate is the antidote for heparin.', 'Anticoagulants - NCLEX', true, 54, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which cues are consistent with aPTT above 80 in this note? (Select all that apply)', 'Which cues are consistent with aPTT above 80 in this note? (Select all that apply)', '[{"id": "a", "text": "Notify provider before antidote administration."}, {"id": "b", "text": "Give antidote before any assessment in this note."}, {"id": "c", "text": "Continue infusion and recheck next shift in this note."}, {"id": "d", "text": "Stop heparin infusion if aPTT is >80 sec."}, {"id": "e", "text": "Assess for bleeding signs like low BP and high HR."}]'::jsonb, '["a", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: If aPTT exceeds 80 sec: stop infusion, assess vitals for bleeding, prepare protamine, then notify provider before giving antidote.', 'Anticoagulants - NCLEX', true, 55, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'A patient is evaluated for HIT recognition. Which findings/actions are appropriate? (Select all that apply)', 'A patient is evaluated for HIT recognition. Which findings/actions are appropriate? (Select all that apply)', '[{"id": "a", "text": "Argatroban is listed as alternative."}, {"id": "b", "text": "Platelet drop >50% suggests HIT."}, {"id": "c", "text": "HIT primarily lowers clot risk in this note."}, {"id": "d", "text": "Continue heparin despite HIT signs in this note."}, {"id": "e", "text": "Heparin should be stopped in suspected HIT."}]'::jsonb, '["a", "b", "e"]'::jsonb, 'Correct selections align with note-based facts: HIT is suspected when platelets drop more than 50% on heparin; stop heparin and switch to argatroban.', 'Anticoagulants - NCLEX', true, 56, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'For management involving warfarin basics, which statements are correct? (Select all that apply)', 'For management involving warfarin basics, which statements are correct? (Select all that apply)', '[{"id": "a", "text": "Warfarin onset is delayed 2–5 days."}, {"id": "b", "text": "Warfarin has immediate IV onset in this note."}, {"id": "c", "text": "Warfarin is used for long-term anticoagulation."}, {"id": "d", "text": "Warfarin is only used during surgery in this note."}, {"id": "e", "text": "Warfarin is oral."}]'::jsonb, '["a", "c", "e"]'::jsonb, 'Correct selections align with note-based facts: Warfarin is oral and has delayed onset of 2–5 days, so it is used for long-term anticoagulation.', 'Anticoagulants - NCLEX', true, 57, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse plans interventions around warfarin therapeutic range. Which items belong in the plan? (Select all that apply)', 'The nurse plans interventions around warfarin therapeutic range. Which items belong in the plan? (Select all that apply)', '[{"id": "a", "text": "INR goal differs by indication."}, {"id": "b", "text": "Usual INR target is 2–3."}, {"id": "c", "text": "Mechanical valves may require INR 2.5–3.5."}, {"id": "d", "text": "Mechanical valve INR target is below 2 in this note."}, {"id": "e", "text": "Warfarin has one fixed INR for all patients in this note."}]'::jsonb, '["a", "b", "c"]'::jsonb, 'Correct selections align with note-based facts: Therapeutic INR is usually 2–3, but mechanical heart valves often target 2.5–3.5.', 'Anticoagulants - NCLEX', true, 58, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'During reassessment, which observations support warfarin antidote? (Select all that apply)', 'During reassessment, which observations support warfarin antidote? (Select all that apply)', '[{"id": "a", "text": "Phytonadione is vitamin K name in note."}, {"id": "b", "text": "Warfarin has specific antidote listed."}, {"id": "c", "text": "Andexanet alfa reverses warfarin in this note."}, {"id": "d", "text": "Vitamin K reverses warfarin."}, {"id": "e", "text": "Protamine reverses warfarin in this note."}]'::jsonb, '["a", "b", "d"]'::jsonb, 'Correct selections align with note-based facts: Vitamin K (phytonadione) is the reversal agent for warfarin.', 'Anticoagulants - NCLEX', true, 59, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which cues are consistent with warfarin teaching vitamin K in this note? (Select all that apply)', 'Which cues are consistent with warfarin teaching vitamin K in this note? (Select all that apply)', '[{"id": "a", "text": "Diet changes can alter warfarin effect."}, {"id": "b", "text": "Vitamin K intake should be consistent."}, {"id": "c", "text": "Patients should not completely avoid leafy greens."}, {"id": "d", "text": "Leafy greens must be eliminated forever in this note."}, {"id": "e", "text": "Vitamin K intake has no effect on warfarin in this note."}]'::jsonb, '["a", "b", "c"]'::jsonb, 'Correct selections align with note-based facts: Patients should keep vitamin K intake consistent rather than eliminating leafy greens entirely.', 'Anticoagulants - NCLEX', true, 60, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'A patient is evaluated for warfarin teaching interactions. Which findings/actions are appropriate? (Select all that apply)', 'A patient is evaluated for warfarin teaching interactions. Which findings/actions are appropriate? (Select all that apply)', '[{"id": "a", "text": "Warfarin patients should take NSAIDs for routine pain in this note."}, {"id": "b", "text": "Interaction teaching reduces bleeding risk."}, {"id": "c", "text": "NSAIDs should be avoided with warfarin."}, {"id": "d", "text": "Grapefruit is listed to avoid."}, {"id": "e", "text": "Grapefruit lowers warfarin effect safely in this note."}]'::jsonb, '["b", "c", "d"]'::jsonb, 'Correct selections align with note-based facts: Avoid NSAIDs and grapefruit while on warfarin due to increased bleeding risk or level changes.', 'Anticoagulants - NCLEX', true, 61, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'For management involving warfarin bleeding teaching, which statements are correct? (Select all that apply)', 'For management involving warfarin bleeding teaching, which statements are correct? (Select all that apply)', '[{"id": "a", "text": "Medical alert bracelet is recommended."}, {"id": "b", "text": "Report unusual bleeding immediately."}, {"id": "c", "text": "Blood in urine/stool is concerning."}, {"id": "d", "text": "Bleeding signs can be ignored if INR is therapeutic in this note."}, {"id": "e", "text": "Medical alert ID is unnecessary in this note."}]'::jsonb, '["a", "b", "c"]'::jsonb, 'Correct selections align with note-based facts: Teach patients to report unusual bleeding, hematuria, or blood in stool and wear a medical alert bracelet.', 'Anticoagulants - NCLEX', true, 62, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse plans interventions around bridge overlap duration. Which items belong in the plan? (Select all that apply)', 'The nurse plans interventions around bridge overlap duration. Which items belong in the plan? (Select all that apply)', '[{"id": "a", "text": "Heparin-warfarin overlap should be 5–7 days minimum."}, {"id": "b", "text": "Warfarin delay necessitates overlap."}, {"id": "c", "text": "Stop heparin the same day warfarin starts in this note."}, {"id": "d", "text": "Overlap is unnecessary if INR is pending in this note."}, {"id": "e", "text": "Heparin provides immediate effect during bridge."}]'::jsonb, '["a", "b", "e"]'::jsonb, 'Correct selections align with note-based facts: When transitioning heparin to warfarin, overlap both drugs for at least 5–7 days.', 'Anticoagulants - NCLEX', true, 63, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'During reassessment, which observations support bridge discontinuation rule? (Select all that apply)', 'During reassessment, which observations support bridge discontinuation rule? (Select all that apply)', '[{"id": "a", "text": "Heparin stops before INR reaches goal in this note."}, {"id": "b", "text": "Heparin continues until INR is therapeutic."}, {"id": "c", "text": "Therapeutic INR must persist two consecutive days."}, {"id": "d", "text": "Target INR for this bridge is 2–3."}, {"id": "e", "text": "Heparin stops after one therapeutic INR in this note."}]'::jsonb, '["b", "c", "d"]'::jsonb, 'Correct selections align with note-based facts: Do not stop heparin until INR is therapeutic 2–3 for two consecutive days.', 'Anticoagulants - NCLEX', true, 64, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which cues are consistent with stable INR follow-up in this note? (Select all that apply)', 'Which cues are consistent with stable INR follow-up in this note? (Select all that apply)', '[{"id": "a", "text": "Stable warfarin INR checks can be every 3 weeks."}, {"id": "b", "text": "INR should be checked yearly only in this note."}, {"id": "c", "text": "Warfarin monitoring is discontinued once stable in this note."}, {"id": "d", "text": "Monitoring frequency depends on stability."}, {"id": "e", "text": "INR monitoring continues long-term."}]'::jsonb, '["a", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: Once INR is stable, warfarin monitoring can be every 3 weeks per note.', 'Anticoagulants - NCLEX', true, 65, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'A patient is evaluated for critical high-risk thresholds. Which findings/actions are appropriate? (Select all that apply)', 'A patient is evaluated for critical high-risk thresholds. Which findings/actions are appropriate? (Select all that apply)', '[{"id": "a", "text": "INR >4 is high hemorrhage risk in note."}, {"id": "b", "text": "aPTT >80 sec is high hemorrhage risk in note."}, {"id": "c", "text": "Both trigger urgent intervention sequence."}, {"id": "d", "text": "aPTT >80 sec suggests under-anticoagulation in this note."}, {"id": "e", "text": "INR 4.5 is reassuring in this note."}]'::jsonb, '["a", "b", "c"]'::jsonb, 'Correct selections align with note-based facts: INR greater than 4 or aPTT greater than 80 sec indicates high hemorrhage risk and immediate intervention.', 'Anticoagulants - NCLEX', true, 66, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'For management involving STOP ASSESS PREPARE CALL, which statements are correct? (Select all that apply)', 'For management involving STOP ASSESS PREPARE CALL, which statements are correct? (Select all that apply)', '[{"id": "a", "text": "Give antidote before assessment in this note."}, {"id": "b", "text": "Prepare antidote then call provider."}, {"id": "c", "text": "Stop anticoagulant first."}, {"id": "d", "text": "Assess for low BP/high HR/pallor/bleeding."}, {"id": "e", "text": "Call provider before stopping active infusion in this note."}]'::jsonb, '["b", "c", "d"]'::jsonb, 'Correct selections align with note-based facts: NCLEX priority order for suspected internal bleeding is STOP anticoagulant, ASSESS vitals/bleeding, PREPARE antidote, then CALL provider.', 'Anticoagulants - NCLEX', true, 67, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse plans interventions around internal bleeding signs. Which items belong in the plan? (Select all that apply)', 'The nurse plans interventions around internal bleeding signs. Which items belong in the plan? (Select all that apply)', '[{"id": "a", "text": "Hematuria is expected and not concerning in this note."}, {"id": "b", "text": "Severe headache may indicate intracranial bleed."}, {"id": "c", "text": "Melena and hematuria are warning signs."}, {"id": "d", "text": "Bradycardia with hypertension is classic anticoagulant bleed in this note."}, {"id": "e", "text": "Low BP plus high HR can indicate internal bleeding."}]'::jsonb, '["b", "c", "e"]'::jsonb, 'Correct selections align with note-based facts: Signs of internal bleeding include low BP, high HR, melena, hematuria, and severe headache suggesting intracranial bleed.', 'Anticoagulants - NCLEX', true, 68, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'During reassessment, which observations support dabigatran profile? (Select all that apply)', 'During reassessment, which observations support dabigatran profile? (Select all that apply)', '[{"id": "a", "text": "Dabigatran is direct thrombin inhibitor."}, {"id": "b", "text": "Protamine is dabigatran antidote in this note."}, {"id": "c", "text": "Dabigatran is factor Xa inhibitor in this note."}, {"id": "d", "text": "Renal function monitoring is listed."}, {"id": "e", "text": "Idarucizumab is antidote."}]'::jsonb, '["a", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: Dabigatran is a direct thrombin inhibitor; monitor renal function and reverse with idarucizumab.', 'Anticoagulants - NCLEX', true, 69, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which cues are consistent with factor Xa inhibitors profile in this note? (Select all that apply)', 'Which cues are consistent with factor Xa inhibitors profile in this note? (Select all that apply)', '[{"id": "a", "text": "Idarucizumab reverses apixaban in this note."}, {"id": "b", "text": "Andexanet alfa is their listed antidote."}, {"id": "c", "text": "Rivaroxaban/apixaban are factor Xa inhibitors."}, {"id": "d", "text": "Renal function and CBC monitoring are listed."}, {"id": "e", "text": "Xa inhibitors are monitored by daily INR in this note."}]'::jsonb, '["b", "c", "d"]'::jsonb, 'Correct selections align with note-based facts: Rivaroxaban and apixaban are factor Xa inhibitors; monitor renal function/CBC and reverse with andexanet alfa.', 'Anticoagulants - NCLEX', true, 70, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'A patient is evaluated for enoxaparin profile. Which findings/actions are appropriate? (Select all that apply)', 'A patient is evaluated for enoxaparin profile. Which findings/actions are appropriate? (Select all that apply)', '[{"id": "a", "text": "Enoxaparin is monitored by INR only in this note."}, {"id": "b", "text": "Enoxaparin is LMWH."}, {"id": "c", "text": "Enoxaparin is fully reversed by vitamin K in this note."}, {"id": "d", "text": "Protamine gives partial reversal."}, {"id": "e", "text": "Anti-Xa may be checked when needed."}]'::jsonb, '["b", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: Enoxaparin is LMWH with anti-Xa monitoring if needed; protamine provides partial reversal.', 'Anticoagulants - NCLEX', true, 71, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'For management involving lab-memory rule, which statements are correct? (Select all that apply)', 'For management involving lab-memory rule, which statements are correct? (Select all that apply)', '[{"id": "a", "text": "Warfarin pairs only with anti-Xa in this note."}, {"id": "b", "text": "Heparin pairs with INR in this note."}, {"id": "c", "text": "Mnemonic supports quick recall."}, {"id": "d", "text": "Heparin pairs with aPTT."}, {"id": "e", "text": "Warfarin pairs with INR."}]'::jsonb, '["c", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: Memory cue: H for Heparin equals aPTT; W for Warfarin equals INR.', 'Anticoagulants - NCLEX', true, 72, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse plans interventions around monitoring distinction. Which items belong in the plan? (Select all that apply)', 'The nurse plans interventions around monitoring distinction. Which items belong in the plan? (Select all that apply)', '[{"id": "a", "text": "Warfarin titration uses q6h aPTT in this note."}, {"id": "b", "text": "Heparin titration uses q6h aPTT checks."}, {"id": "c", "text": "Warfarin is monitored with INR/PT."}, {"id": "d", "text": "Monitoring strategy differs by drug."}, {"id": "e", "text": "Both drugs are monitored with same lab in this note."}]'::jsonb, '["b", "c", "d"]'::jsonb, 'Correct selections align with note-based facts: Warfarin monitoring is INR/PT only, while heparin titration requires frequent aPTT checks every 6 hours.', 'Anticoagulants - NCLEX', true, 73, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'During reassessment, which observations support integrated anticoagulant safety? (Select all that apply)', 'During reassessment, which observations support integrated anticoagulant safety? (Select all that apply)', '[{"id": "a", "text": "Antidote readiness is emphasized in NCLEX priorities."}, {"id": "b", "text": "Anticoagulants do not require routine monitoring in this note."}, {"id": "c", "text": "Correct lab-drug matching is central to safety."}, {"id": "d", "text": "Escalation sequence is optional in this note."}, {"id": "e", "text": "Bleeding signs require immediate action."}]'::jsonb, '["a", "c", "e"]'::jsonb, 'Correct selections align with note-based facts: Safe anticoagulant care requires correct lab-drug pairing, bleeding surveillance, antidote readiness, and structured escalation.', 'Anticoagulants - NCLEX', true, 74, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which cues are consistent with aPTT role in this note? (Select all that apply)', 'Which cues are consistent with aPTT role in this note? (Select all that apply)', '[{"id": "a", "text": "aPTT is used to monitor heparin."}, {"id": "b", "text": "Therapeutic heparin aPTT is 45–80 sec."}, {"id": "c", "text": "Therapeutic heparin aPTT is below 20 sec in this note."}, {"id": "d", "text": "Normal aPTT is around 30–40 sec."}, {"id": "e", "text": "aPTT is the primary warfarin monitoring test in this note."}]'::jsonb, '["a", "b", "d"]'::jsonb, 'Correct selections align with note-based facts: aPTT monitors heparin therapy; normal is about 30–40 sec and therapeutic heparin range is 45–80 sec.', 'Anticoagulants - NCLEX', true, 75, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'A patient is evaluated for PT/INR role. Which findings/actions are appropriate? (Select all that apply)', 'A patient is evaluated for PT/INR role. Which findings/actions are appropriate? (Select all that apply)', '[{"id": "a", "text": "INR goal for most patients is below 1 in this note."}, {"id": "b", "text": "PT is associated with warfarin monitoring in this note."}, {"id": "c", "text": "Warfarin is monitored by aPTT only in this note."}, {"id": "d", "text": "Typical therapeutic INR is 2–3."}, {"id": "e", "text": "INR is used for warfarin monitoring."}]'::jsonb, '["b", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: PT/INR monitor warfarin; INR therapeutic range is 2–3 for most indications.', 'Anticoagulants - NCLEX', true, 76, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'For management involving heparin basics, which statements are correct? (Select all that apply)', 'For management involving heparin basics, which statements are correct? (Select all that apply)', '[{"id": "a", "text": "IV heparin onset is immediate."}, {"id": "b", "text": "Heparin is oral only in this note."}, {"id": "c", "text": "DVT/PE/ACS are listed uses."}, {"id": "d", "text": "Heparin requires 2–5 days to start working in this note."}, {"id": "e", "text": "Heparin can be IV or SubQ."}]'::jsonb, '["a", "c", "e"]'::jsonb, 'Correct selections align with note-based facts: Heparin is given IV or SubQ, has immediate IV onset, and is used for DVT, PE, ACS, dialysis, and perioperative prevention.', 'Anticoagulants - NCLEX', true, 77, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse plans interventions around heparin antidote. Which items belong in the plan? (Select all that apply)', 'The nurse plans interventions around heparin antidote. Which items belong in the plan? (Select all that apply)', '[{"id": "a", "text": "Vitamin K is the heparin antidote in this note."}, {"id": "b", "text": "Idarucizumab reverses heparin in this note."}, {"id": "c", "text": "Heparin has a named antidote in this note."}, {"id": "d", "text": "Protamine is linked with heparin overdose management."}, {"id": "e", "text": "Protamine sulfate reverses heparin."}]'::jsonb, '["c", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: Protamine sulfate is the antidote for heparin.', 'Anticoagulants - NCLEX', true, 78, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'During reassessment, which observations support aPTT above 80? (Select all that apply)', 'During reassessment, which observations support aPTT above 80? (Select all that apply)', '[{"id": "a", "text": "Notify provider before antidote administration."}, {"id": "b", "text": "Give antidote before any assessment in this note."}, {"id": "c", "text": "Assess for bleeding signs like low BP and high HR."}, {"id": "d", "text": "Stop heparin infusion if aPTT is >80 sec."}, {"id": "e", "text": "Continue infusion and recheck next shift in this note."}]'::jsonb, '["a", "c", "d"]'::jsonb, 'Correct selections align with note-based facts: If aPTT exceeds 80 sec: stop infusion, assess vitals for bleeding, prepare protamine, then notify provider before giving antidote.', 'Anticoagulants - NCLEX', true, 79, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which cues are consistent with HIT recognition in this note? (Select all that apply)', 'Which cues are consistent with HIT recognition in this note? (Select all that apply)', '[{"id": "a", "text": "Argatroban is listed as alternative."}, {"id": "b", "text": "Heparin should be stopped in suspected HIT."}, {"id": "c", "text": "HIT primarily lowers clot risk in this note."}, {"id": "d", "text": "Continue heparin despite HIT signs in this note."}, {"id": "e", "text": "Platelet drop >50% suggests HIT."}]'::jsonb, '["a", "b", "e"]'::jsonb, 'Correct selections align with note-based facts: HIT is suspected when platelets drop more than 50% on heparin; stop heparin and switch to argatroban.', 'Anticoagulants - NCLEX', true, 80, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'A patient is evaluated for warfarin basics. Which findings/actions are appropriate? (Select all that apply)', 'A patient is evaluated for warfarin basics. Which findings/actions are appropriate? (Select all that apply)', '[{"id": "a", "text": "Warfarin onset is delayed 2–5 days."}, {"id": "b", "text": "Warfarin is only used during surgery in this note."}, {"id": "c", "text": "Warfarin is used for long-term anticoagulation."}, {"id": "d", "text": "Warfarin has immediate IV onset in this note."}, {"id": "e", "text": "Warfarin is oral."}]'::jsonb, '["a", "c", "e"]'::jsonb, 'Correct selections align with note-based facts: Warfarin is oral and has delayed onset of 2–5 days, so it is used for long-term anticoagulation.', 'Anticoagulants - NCLEX', true, 81, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'For management involving warfarin therapeutic range, which statements are correct? (Select all that apply)', 'For management involving warfarin therapeutic range, which statements are correct? (Select all that apply)', '[{"id": "a", "text": "Mechanical valve INR target is below 2 in this note."}, {"id": "b", "text": "Warfarin has one fixed INR for all patients in this note."}, {"id": "c", "text": "Mechanical valves may require INR 2.5–3.5."}, {"id": "d", "text": "INR goal differs by indication."}, {"id": "e", "text": "Usual INR target is 2–3."}]'::jsonb, '["c", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: Therapeutic INR is usually 2–3, but mechanical heart valves often target 2.5–3.5.', 'Anticoagulants - NCLEX', true, 82, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse plans interventions around warfarin antidote. Which items belong in the plan? (Select all that apply)', 'The nurse plans interventions around warfarin antidote. Which items belong in the plan? (Select all that apply)', '[{"id": "a", "text": "Vitamin K reverses warfarin."}, {"id": "b", "text": "Warfarin has specific antidote listed."}, {"id": "c", "text": "Protamine reverses warfarin in this note."}, {"id": "d", "text": "Phytonadione is vitamin K name in note."}, {"id": "e", "text": "Andexanet alfa reverses warfarin in this note."}]'::jsonb, '["a", "b", "d"]'::jsonb, 'Correct selections align with note-based facts: Vitamin K (phytonadione) is the reversal agent for warfarin.', 'Anticoagulants - NCLEX', true, 83, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'During reassessment, which observations support warfarin teaching vitamin K? (Select all that apply)', 'During reassessment, which observations support warfarin teaching vitamin K? (Select all that apply)', '[{"id": "a", "text": "Leafy greens must be eliminated forever in this note."}, {"id": "b", "text": "Vitamin K intake has no effect on warfarin in this note."}, {"id": "c", "text": "Patients should not completely avoid leafy greens."}, {"id": "d", "text": "Diet changes can alter warfarin effect."}, {"id": "e", "text": "Vitamin K intake should be consistent."}]'::jsonb, '["c", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: Patients should keep vitamin K intake consistent rather than eliminating leafy greens entirely.', 'Anticoagulants - NCLEX', true, 84, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which cues are consistent with warfarin teaching interactions in this note? (Select all that apply)', 'Which cues are consistent with warfarin teaching interactions in this note? (Select all that apply)', '[{"id": "a", "text": "Grapefruit is listed to avoid."}, {"id": "b", "text": "NSAIDs should be avoided with warfarin."}, {"id": "c", "text": "Grapefruit lowers warfarin effect safely in this note."}, {"id": "d", "text": "Warfarin patients should take NSAIDs for routine pain in this note."}, {"id": "e", "text": "Interaction teaching reduces bleeding risk."}]'::jsonb, '["a", "b", "e"]'::jsonb, 'Correct selections align with note-based facts: Avoid NSAIDs and grapefruit while on warfarin due to increased bleeding risk or level changes.', 'Anticoagulants - NCLEX', true, 85, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'A patient is evaluated for warfarin bleeding teaching. Which findings/actions are appropriate? (Select all that apply)', 'A patient is evaluated for warfarin bleeding teaching. Which findings/actions are appropriate? (Select all that apply)', '[{"id": "a", "text": "Medical alert ID is unnecessary in this note."}, {"id": "b", "text": "Bleeding signs can be ignored if INR is therapeutic in this note."}, {"id": "c", "text": "Report unusual bleeding immediately."}, {"id": "d", "text": "Blood in urine/stool is concerning."}, {"id": "e", "text": "Medical alert bracelet is recommended."}]'::jsonb, '["c", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: Teach patients to report unusual bleeding, hematuria, or blood in stool and wear a medical alert bracelet.', 'Anticoagulants - NCLEX', true, 86, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'For management involving bridge overlap duration, which statements are correct? (Select all that apply)', 'For management involving bridge overlap duration, which statements are correct? (Select all that apply)', '[{"id": "a", "text": "Stop heparin the same day warfarin starts in this note."}, {"id": "b", "text": "Overlap is unnecessary if INR is pending in this note."}, {"id": "c", "text": "Heparin provides immediate effect during bridge."}, {"id": "d", "text": "Warfarin delay necessitates overlap."}, {"id": "e", "text": "Heparin-warfarin overlap should be 5–7 days minimum."}]'::jsonb, '["c", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: When transitioning heparin to warfarin, overlap both drugs for at least 5–7 days.', 'Anticoagulants - NCLEX', true, 87, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse plans interventions around bridge discontinuation rule. Which items belong in the plan? (Select all that apply)', 'The nurse plans interventions around bridge discontinuation rule. Which items belong in the plan? (Select all that apply)', '[{"id": "a", "text": "Heparin continues until INR is therapeutic."}, {"id": "b", "text": "Target INR for this bridge is 2–3."}, {"id": "c", "text": "Heparin stops after one therapeutic INR in this note."}, {"id": "d", "text": "Heparin stops before INR reaches goal in this note."}, {"id": "e", "text": "Therapeutic INR must persist two consecutive days."}]'::jsonb, '["a", "b", "e"]'::jsonb, 'Correct selections align with note-based facts: Do not stop heparin until INR is therapeutic 2–3 for two consecutive days.', 'Anticoagulants - NCLEX', true, 88, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'During reassessment, which observations support stable INR follow-up? (Select all that apply)', 'During reassessment, which observations support stable INR follow-up? (Select all that apply)', '[{"id": "a", "text": "Stable warfarin INR checks can be every 3 weeks."}, {"id": "b", "text": "INR monitoring continues long-term."}, {"id": "c", "text": "Warfarin monitoring is discontinued once stable in this note."}, {"id": "d", "text": "INR should be checked yearly only in this note."}, {"id": "e", "text": "Monitoring frequency depends on stability."}]'::jsonb, '["a", "b", "e"]'::jsonb, 'Correct selections align with note-based facts: Once INR is stable, warfarin monitoring can be every 3 weeks per note.', 'Anticoagulants - NCLEX', true, 89, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which cues are consistent with critical high-risk thresholds in this note? (Select all that apply)', 'Which cues are consistent with critical high-risk thresholds in this note? (Select all that apply)', '[{"id": "a", "text": "INR 4.5 is reassuring in this note."}, {"id": "b", "text": "aPTT >80 sec is high hemorrhage risk in note."}, {"id": "c", "text": "INR >4 is high hemorrhage risk in note."}, {"id": "d", "text": "aPTT >80 sec suggests under-anticoagulation in this note."}, {"id": "e", "text": "Both trigger urgent intervention sequence."}]'::jsonb, '["b", "c", "e"]'::jsonb, 'Correct selections align with note-based facts: INR greater than 4 or aPTT greater than 80 sec indicates high hemorrhage risk and immediate intervention.', 'Anticoagulants - NCLEX', true, 90, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'A patient is evaluated for STOP ASSESS PREPARE CALL. Which findings/actions are appropriate? (Select all that apply)', 'A patient is evaluated for STOP ASSESS PREPARE CALL. Which findings/actions are appropriate? (Select all that apply)', '[{"id": "a", "text": "Prepare antidote then call provider."}, {"id": "b", "text": "Assess for low BP/high HR/pallor/bleeding."}, {"id": "c", "text": "Stop anticoagulant first."}, {"id": "d", "text": "Call provider before stopping active infusion in this note."}, {"id": "e", "text": "Give antidote before assessment in this note."}]'::jsonb, '["a", "b", "c"]'::jsonb, 'Correct selections align with note-based facts: NCLEX priority order for suspected internal bleeding is STOP anticoagulant, ASSESS vitals/bleeding, PREPARE antidote, then CALL provider.', 'Anticoagulants - NCLEX', true, 91, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'For management involving internal bleeding signs, which statements are correct? (Select all that apply)', 'For management involving internal bleeding signs, which statements are correct? (Select all that apply)', '[{"id": "a", "text": "Hematuria is expected and not concerning in this note."}, {"id": "b", "text": "Severe headache may indicate intracranial bleed."}, {"id": "c", "text": "Bradycardia with hypertension is classic anticoagulant bleed in this note."}, {"id": "d", "text": "Melena and hematuria are warning signs."}, {"id": "e", "text": "Low BP plus high HR can indicate internal bleeding."}]'::jsonb, '["b", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: Signs of internal bleeding include low BP, high HR, melena, hematuria, and severe headache suggesting intracranial bleed.', 'Anticoagulants - NCLEX', true, 92, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse plans interventions around dabigatran profile. Which items belong in the plan? (Select all that apply)', 'The nurse plans interventions around dabigatran profile. Which items belong in the plan? (Select all that apply)', '[{"id": "a", "text": "Renal function monitoring is listed."}, {"id": "b", "text": "Dabigatran is direct thrombin inhibitor."}, {"id": "c", "text": "Dabigatran is factor Xa inhibitor in this note."}, {"id": "d", "text": "Idarucizumab is antidote."}, {"id": "e", "text": "Protamine is dabigatran antidote in this note."}]'::jsonb, '["a", "b", "d"]'::jsonb, 'Correct selections align with note-based facts: Dabigatran is a direct thrombin inhibitor; monitor renal function and reverse with idarucizumab.', 'Anticoagulants - NCLEX', true, 93, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'During reassessment, which observations support factor Xa inhibitors profile? (Select all that apply)', 'During reassessment, which observations support factor Xa inhibitors profile? (Select all that apply)', '[{"id": "a", "text": "Andexanet alfa is their listed antidote."}, {"id": "b", "text": "Rivaroxaban/apixaban are factor Xa inhibitors."}, {"id": "c", "text": "Renal function and CBC monitoring are listed."}, {"id": "d", "text": "Xa inhibitors are monitored by daily INR in this note."}, {"id": "e", "text": "Idarucizumab reverses apixaban in this note."}]'::jsonb, '["a", "b", "c"]'::jsonb, 'Correct selections align with note-based facts: Rivaroxaban and apixaban are factor Xa inhibitors; monitor renal function/CBC and reverse with andexanet alfa.', 'Anticoagulants - NCLEX', true, 94, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which cues are consistent with enoxaparin profile in this note? (Select all that apply)', 'Which cues are consistent with enoxaparin profile in this note? (Select all that apply)', '[{"id": "a", "text": "Anti-Xa may be checked when needed."}, {"id": "b", "text": "Protamine gives partial reversal."}, {"id": "c", "text": "Enoxaparin is monitored by INR only in this note."}, {"id": "d", "text": "Enoxaparin is fully reversed by vitamin K in this note."}, {"id": "e", "text": "Enoxaparin is LMWH."}]'::jsonb, '["a", "b", "e"]'::jsonb, 'Correct selections align with note-based facts: Enoxaparin is LMWH with anti-Xa monitoring if needed; protamine provides partial reversal.', 'Anticoagulants - NCLEX', true, 95, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'A patient is evaluated for lab-memory rule. Which findings/actions are appropriate? (Select all that apply)', 'A patient is evaluated for lab-memory rule. Which findings/actions are appropriate? (Select all that apply)', '[{"id": "a", "text": "Heparin pairs with INR in this note."}, {"id": "b", "text": "Mnemonic supports quick recall."}, {"id": "c", "text": "Warfarin pairs only with anti-Xa in this note."}, {"id": "d", "text": "Warfarin pairs with INR."}, {"id": "e", "text": "Heparin pairs with aPTT."}]'::jsonb, '["b", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: Memory cue: H for Heparin equals aPTT; W for Warfarin equals INR.', 'Anticoagulants - NCLEX', true, 96, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'For management involving monitoring distinction, which statements are correct? (Select all that apply)', 'For management involving monitoring distinction, which statements are correct? (Select all that apply)', '[{"id": "a", "text": "Monitoring strategy differs by drug."}, {"id": "b", "text": "Warfarin is monitored with INR/PT."}, {"id": "c", "text": "Heparin titration uses q6h aPTT checks."}, {"id": "d", "text": "Warfarin titration uses q6h aPTT in this note."}, {"id": "e", "text": "Both drugs are monitored with same lab in this note."}]'::jsonb, '["a", "b", "c"]'::jsonb, 'Correct selections align with note-based facts: Warfarin monitoring is INR/PT only, while heparin titration requires frequent aPTT checks every 6 hours.', 'Anticoagulants - NCLEX', true, 97, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse plans interventions around integrated anticoagulant safety. Which items belong in the plan? (Select all that apply)', 'The nurse plans interventions around integrated anticoagulant safety. Which items belong in the plan? (Select all that apply)', '[{"id": "a", "text": "Escalation sequence is optional in this note."}, {"id": "b", "text": "Correct lab-drug matching is central to safety."}, {"id": "c", "text": "Bleeding signs require immediate action."}, {"id": "d", "text": "Antidote readiness is emphasized in NCLEX priorities."}, {"id": "e", "text": "Anticoagulants do not require routine monitoring in this note."}]'::jsonb, '["b", "c", "d"]'::jsonb, 'Correct selections align with note-based facts: Safe anticoagulant care requires correct lab-drug pairing, bleeding surveillance, antidote readiness, and structured escalation.', 'Anticoagulants - NCLEX', true, 98, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'During reassessment, which observations support aPTT role? (Select all that apply)', 'During reassessment, which observations support aPTT role? (Select all that apply)', '[{"id": "a", "text": "Therapeutic heparin aPTT is below 20 sec in this note."}, {"id": "b", "text": "aPTT is the primary warfarin monitoring test in this note."}, {"id": "c", "text": "Normal aPTT is around 30–40 sec."}, {"id": "d", "text": "aPTT is used to monitor heparin."}, {"id": "e", "text": "Therapeutic heparin aPTT is 45–80 sec."}]'::jsonb, '["c", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: aPTT monitors heparin therapy; normal is about 30–40 sec and therapeutic heparin range is 45–80 sec.', 'Anticoagulants - NCLEX', true, 99, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which cues are consistent with PT/INR role in this note? (Select all that apply)', 'Which cues are consistent with PT/INR role in this note? (Select all that apply)', '[{"id": "a", "text": "PT is associated with warfarin monitoring in this note."}, {"id": "b", "text": "Typical therapeutic INR is 2–3."}, {"id": "c", "text": "INR goal for most patients is below 1 in this note."}, {"id": "d", "text": "Warfarin is monitored by aPTT only in this note."}, {"id": "e", "text": "INR is used for warfarin monitoring."}]'::jsonb, '["a", "b", "e"]'::jsonb, 'Correct selections align with note-based facts: PT/INR monitor warfarin; INR therapeutic range is 2–3 for most indications.', 'Anticoagulants - NCLEX', true, 100, 1, true);
END $$;
COMMIT;