BEGIN;
DO $$
DECLARE
  v_subject_id UUID;
  v_topic_id UUID;
  v_test_id BIGINT;
BEGIN
  SELECT id INTO v_subject_id FROM test_subjects WHERE name ILIKE '%cardio%' ORDER BY id LIMIT 1;
  IF v_subject_id IS NULL THEN
    INSERT INTO test_subjects (name, description) VALUES ('Cardiovascular System', 'Cardiovascular notes') RETURNING id INTO v_subject_id;
  END IF;
  SELECT id INTO v_topic_id FROM test_topics WHERE name = 'Cardiac Biomarkers' ORDER BY (SELECT COUNT(*) FROM test_questions q WHERE q.topic_id = test_topics.id) DESC, created_at ASC LIMIT 1;
  IF v_topic_id IS NULL THEN
    INSERT INTO test_topics (subject_id, name, description, status) VALUES (v_subject_id, 'Cardiac Biomarkers', 'Troponin CK-MB BNP and myoglobin interpretation', 'published') RETURNING id INTO v_topic_id;
  END IF;
  SELECT id INTO v_test_id FROM tests WHERE is_active = true ORDER BY id LIMIT 1;
  IF v_test_id IS NULL THEN
    INSERT INTO tests (test_name, system_category, description, is_active)
    VALUES ('Cardiovascular System - Cardiac Biomarkers (Generated)', 'Cardiovascular System', 'Auto-generated NCLEX question set', true)
    RETURNING id INTO v_test_id;
  END IF;
  DELETE FROM test_questions WHERE topic_id = v_topic_id AND category = 'Cardiac Biomarkers - NCLEX';
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which finding best supports Biomarker purpose in this biomarker scenario?', 'Which finding best supports Biomarker purpose in this biomarker scenario?', '[{"id": "a", "text": "Cardiac biomarkers are blood proteins released after cardiac cell injury and are used for MI/HF diagnosis and stress assessment."}, {"id": "b", "text": "Serial rechecks are unnecessary when first value is borderline."}, {"id": "c", "text": "Biomarkers only diagnose pulmonary embolism in this note."}, {"id": "d", "text": "This pattern is more consistent with Troponin T kinetics."}]'::jsonb, '["a"]'::jsonb, 'Correct because Cardiac biomarkers are blood proteins released after cardiac cell injury and are used for MI/HF diagnosis and stress assessment. Use biomarkers with clinical context to confirm or exclude acute cardiac injury.', 'Cardiac Biomarkers - NCLEX', false, 1, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse reviews lab trends; which interpretation best matches Serial testing principle?', 'The nurse reviews lab trends; which interpretation best matches Serial testing principle?', '[{"id": "a", "text": "Serial rechecks are unnecessary when first value is borderline."}, {"id": "b", "text": "Trend interpretation is safer than single-point interpretation."}, {"id": "c", "text": "This pattern is more consistent with hsTnT utility."}, {"id": "d", "text": "One elevated value always confirms MI in this note."}]'::jsonb, '["b"]'::jsonb, 'Correct because Serial values every 3–6 hours are needed, and a rise-and-fall pattern supports MI rather than one isolated elevation. Trend interpretation is safer than single-point interpretation.', 'Cardiac Biomarkers - NCLEX', false, 2, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which clinical judgment is most accurate regarding Troponin priority?', 'Which clinical judgment is most accurate regarding Troponin priority?', '[{"id": "a", "text": "This pattern is more consistent with CK isoform composition."}, {"id": "b", "text": "Serial rechecks are unnecessary when first value is borderline."}, {"id": "c", "text": "Myoglobin is more specific than troponin in this note."}, {"id": "d", "text": "Troponin is the most specific and sensitive biomarker for MI and is the gold standard in this note."}]'::jsonb, '["d"]'::jsonb, 'Correct because Troponin is the most specific and sensitive biomarker for MI and is the gold standard in this note. Prioritize troponin trend review in suspected ACS workflows.', 'Cardiac Biomarkers - NCLEX', false, 3, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'In urgent triage, which conclusion aligns with Troponin I kinetics?', 'In urgent triage, which conclusion aligns with Troponin I kinetics?', '[{"id": "a", "text": "Single-point interpretation is always definitive regardless trend direction."}, {"id": "b", "text": "Troponin I peak occurs at 2 hours in this note."}, {"id": "c", "text": "Use timing to detect delayed presentations and avoid false reassurance early."}, {"id": "d", "text": "Troponin I normalizes within 12 hours in this note."}]'::jsonb, '["c"]'::jsonb, 'Correct because Troponin I normal is <0.04 ng/mL, rises 3–6h, peaks 12–24h, normalizes in 7–10 days. Use timing to detect delayed presentations and avoid false reassurance early.', 'Cardiac Biomarkers - NCLEX', false, 4, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which statement most appropriately reflects Troponin T kinetics?', 'Which statement most appropriately reflects Troponin T kinetics?', '[{"id": "a", "text": "Troponin T has no normal reference in this note."}, {"id": "b", "text": "Troponin T normal is <0.01 ng/mL, rises 3–6h, peaks 12–24h, and normalizes over 10–14 days."}, {"id": "c", "text": "Troponin T is gone by 24 hours in this note."}, {"id": "d", "text": "Serial rechecks are unnecessary when first value is borderline."}]'::jsonb, '["b"]'::jsonb, 'Correct because Troponin T normal is <0.01 ng/mL, rises 3–6h, peaks 12–24h, and normalizes over 10–14 days. Recognize prolonged elevation window for recent MI detection.', 'Cardiac Biomarkers - NCLEX', false, 5, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which finding best supports hsTnT utility in this biomarker scenario?', 'Which finding best supports hsTnT utility in this biomarker scenario?', '[{"id": "a", "text": "hsTnT is used only for heart failure in this note."}, {"id": "b", "text": "Single-point interpretation is always definitive regardless trend direction."}, {"id": "c", "text": "hsTnT is less sensitive than CK-MB in this note."}, {"id": "d", "text": "Interpret small dynamic changes carefully in early injury."}]'::jsonb, '["d"]'::jsonb, 'Correct because High-sensitivity Troponin T can detect smaller myocardial infarctions. Interpret small dynamic changes carefully in early injury.', 'Cardiac Biomarkers - NCLEX', false, 6, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse reviews lab trends; which interpretation best matches CK isoform composition?', 'The nurse reviews lab trends; which interpretation best matches CK isoform composition?', '[{"id": "a", "text": "This pattern is more consistent with BNP physiology."}, {"id": "b", "text": "CK-MM is 96–100%, CK-MB is 0–5%, and CK-BB is about 0% in normal distribution listed."}, {"id": "c", "text": "Serial rechecks are unnecessary when first value is borderline."}, {"id": "d", "text": "CK-BB is dominant in healthy blood in this note."}]'::jsonb, '["b"]'::jsonb, 'Correct because CK-MM is 96–100%, CK-MB is 0–5%, and CK-BB is about 0% in normal distribution listed. Know isoform proportions to avoid misattributing skeletal injury as MI.', 'Cardiac Biomarkers - NCLEX', false, 7, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which clinical judgment is most accurate regarding CK-MB timeline/use?', 'Which clinical judgment is most accurate regarding CK-MB timeline/use?', '[{"id": "a", "text": "Serial rechecks are unnecessary when first value is borderline."}, {"id": "b", "text": "Use CK-MB especially when looking for reinfarction after initial event."}, {"id": "c", "text": "This pattern is more consistent with BNP ranges."}, {"id": "d", "text": "CK-MB remains elevated for 14 days in this note."}]'::jsonb, '["b"]'::jsonb, 'Correct because CK-MB rises 4–6h, peaks 18–24h, normalizes 48–72h, and is useful for MI and re-infarction detection. Use CK-MB especially when looking for reinfarction after initial event.', 'Cardiac Biomarkers - NCLEX', false, 8, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'In urgent triage, which conclusion aligns with CK-MM limitation?', 'In urgent triage, which conclusion aligns with CK-MM limitation?', '[{"id": "a", "text": "Serial rechecks are unnecessary when first value is borderline."}, {"id": "b", "text": "CK-MM reflects skeletal muscle injury such as rhabdomyolysis and is not cardiac-specific."}, {"id": "c", "text": "CK-MM is most cardiac-specific marker in this note."}, {"id": "d", "text": "CK-MM excludes muscle injury in this note."}]'::jsonb, '["b"]'::jsonb, 'Correct because CK-MM reflects skeletal muscle injury such as rhabdomyolysis and is not cardiac-specific. Avoid diagnosing MI from CK-MM elevation alone.', 'Cardiac Biomarkers - NCLEX', false, 9, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which statement most appropriately reflects CK-BB limitation?', 'Which statement most appropriately reflects CK-BB limitation?', '[{"id": "a", "text": "Keep CK-BB out of MI-focused biomarker decisions."}, {"id": "b", "text": "CK-BB comes from ventricular myocardium in this note."}, {"id": "c", "text": "This pattern is more consistent with BNP not MI marker."}, {"id": "d", "text": "CK-BB is preferred biomarker for MI in this note."}]'::jsonb, '["a"]'::jsonb, 'Correct because CK-BB is associated with brain/smooth muscle injury and is not used for cardiac monitoring. Keep CK-BB out of MI-focused biomarker decisions.', 'Cardiac Biomarkers - NCLEX', false, 10, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which finding best supports BNP physiology in this biomarker scenario?', 'Which finding best supports BNP physiology in this biomarker scenario?', '[{"id": "a", "text": "BNP is released from ventricular myocytes when stretched by volume overload."}, {"id": "b", "text": "This pattern is more consistent with NT-proBNP reference."}, {"id": "c", "text": "BNP is unrelated to ventricular stretch in this note."}, {"id": "d", "text": "Single-point interpretation is always definitive regardless trend direction."}]'::jsonb, '["a"]'::jsonb, 'Correct because BNP is released from ventricular myocytes when stretched by volume overload. Interpret BNP as volume-stress signal rather than infarction specificity.', 'Cardiac Biomarkers - NCLEX', false, 11, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse reviews lab trends; which interpretation best matches BNP ranges?', 'The nurse reviews lab trends; which interpretation best matches BNP ranges?', '[{"id": "a", "text": "Use BNP strata to grade heart-failure likelihood and urgency."}, {"id": "b", "text": "This pattern is more consistent with Myoglobin kinetics."}, {"id": "c", "text": "BNP <20 defines severe HF in this note."}, {"id": "d", "text": "Serial rechecks are unnecessary when first value is borderline."}]'::jsonb, '["a"]'::jsonb, 'Correct because BNP normal is <100 pg/mL; 100–400 possible HF; >400 likely HF exacerbation. Use BNP strata to grade heart-failure likelihood and urgency.', 'Cardiac Biomarkers - NCLEX', false, 12, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which clinical judgment is most accurate regarding BNP clinical use?', 'Which clinical judgment is most accurate regarding BNP clinical use?', '[{"id": "a", "text": "BNP helps differentiate cardiac from pulmonary dyspnea, guides diuresis/discharge, and higher BNP suggests worse prognosis."}, {"id": "b", "text": "BNP has no prognostic value in this note."}, {"id": "c", "text": "Single-point interpretation is always definitive regardless trend direction."}, {"id": "d", "text": "This pattern is more consistent with Myoglobin limitation/use."}]'::jsonb, '["a"]'::jsonb, 'Correct because BNP helps differentiate cardiac from pulmonary dyspnea, guides diuresis/discharge, and higher BNP suggests worse prognosis. Apply BNP trends to dyspnea triage and HF trajectory planning.', 'Cardiac Biomarkers - NCLEX', false, 13, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'In urgent triage, which conclusion aligns with BNP not MI marker?', 'In urgent triage, which conclusion aligns with BNP not MI marker?', '[{"id": "a", "text": "Do not substitute BNP for troponin in ACS diagnosis."}, {"id": "b", "text": "Serial rechecks are unnecessary when first value is borderline."}, {"id": "c", "text": "BNP is the most specific MI marker in this note."}, {"id": "d", "text": "This pattern is more consistent with Timeline comparison."}]'::jsonb, '["a"]'::jsonb, 'Correct because The note explicitly states BNP does not indicate MI; it indicates fluid overload/heart failure context. Do not substitute BNP for troponin in ACS diagnosis.', 'Cardiac Biomarkers - NCLEX', false, 14, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which statement most appropriately reflects NT-proBNP reference?', 'Which statement most appropriately reflects NT-proBNP reference?', '[{"id": "a", "text": "NT-proBNP has shorter half-life than BNP in this note."}, {"id": "b", "text": "NT-proBNP normal is listed as <300 pg/mL and has longer half-life."}, {"id": "c", "text": "This pattern is more consistent with BUN/creatinine interpretation."}, {"id": "d", "text": "Single-point interpretation is always definitive regardless trend direction."}]'::jsonb, '["b"]'::jsonb, 'Correct because NT-proBNP normal is listed as <300 pg/mL and has longer half-life. Account for assay type when interpreting natriuretic peptide results.', 'Cardiac Biomarkers - NCLEX', false, 15, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which finding best supports Myoglobin kinetics in this biomarker scenario?', 'Which finding best supports Myoglobin kinetics in this biomarker scenario?', '[{"id": "a", "text": "Use for very early phase support, then rely on specific markers."}, {"id": "b", "text": "Serial rechecks are unnecessary when first value is borderline."}, {"id": "c", "text": "Myoglobin stays elevated 10 days in this note."}, {"id": "d", "text": "Myoglobin rises after troponin peak in this note."}]'::jsonb, '["a"]'::jsonb, 'Correct because Myoglobin rises first at 1–3h after MI but normalizes quickly within 24h. Use for very early phase support, then rely on specific markers.', 'Cardiac Biomarkers - NCLEX', false, 16, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse reviews lab trends; which interpretation best matches Myoglobin limitation/use?', 'The nurse reviews lab trends; which interpretation best matches Myoglobin limitation/use?', '[{"id": "a", "text": "Myoglobin alone confirms MI in this note."}, {"id": "b", "text": "This pattern is more consistent with Lactate and ABG significance."}, {"id": "c", "text": "Serial rechecks are unnecessary when first value is borderline."}, {"id": "d", "text": "Myoglobin is not cardiac-specific and is used mainly for early rule-out when normal at around 3h."}]'::jsonb, '["d"]'::jsonb, 'Correct because Myoglobin is not cardiac-specific and is used mainly for early rule-out when normal at around 3h. Avoid overcalling MI from isolated myoglobin elevation.', 'Cardiac Biomarkers - NCLEX', false, 17, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which clinical judgment is most accurate regarding Timeline comparison?', 'Which clinical judgment is most accurate regarding Timeline comparison?', '[{"id": "a", "text": "Choose marker by time-from-onset and diagnostic objective."}, {"id": "b", "text": "Troponin clears before CK-MB in this note."}, {"id": "c", "text": "Single-point interpretation is always definitive regardless trend direction."}, {"id": "d", "text": "Serial rechecks are unnecessary when first value is borderline."}]'::jsonb, '["a"]'::jsonb, 'Correct because Timeline summary: myoglobin earliest/shortest, CK-MB intermediate, troponin longest duration. Choose marker by time-from-onset and diagnostic objective.', 'Cardiac Biomarkers - NCLEX', false, 18, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'In urgent triage, which conclusion aligns with BUN/creatinine interpretation?', 'In urgent triage, which conclusion aligns with BUN/creatinine interpretation?', '[{"id": "a", "text": "Single-point interpretation is always definitive regardless trend direction."}, {"id": "b", "text": "BUN 7–20 and creatinine 0.6–1.2 are listed normal; high BUN with normal creatinine suggests dehydration, while both high suggest renal impairment."}, {"id": "c", "text": "Normal creatinine excludes dehydration in this note."}, {"id": "d", "text": "High BUN with normal creatinine proves MI in this note."}]'::jsonb, '["b"]'::jsonb, 'Correct because BUN 7–20 and creatinine 0.6–1.2 are listed normal; high BUN with normal creatinine suggests dehydration, while both high suggest renal impairment. Use renal trends to separate prerenal dehydration from intrinsic decline.', 'Cardiac Biomarkers - NCLEX', false, 19, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which statement most appropriately reflects Low-output renal effect?', 'Which statement most appropriately reflects Low-output renal effect?', '[{"id": "a", "text": "Treat perfusion deficits to protect kidney function."}, {"id": "b", "text": "This pattern is more consistent with Biomarker purpose."}, {"id": "c", "text": "Single-point interpretation is always definitive regardless trend direction."}, {"id": "d", "text": "BUN/Cr are unrelated to hemodynamics in this note."}]'::jsonb, '["a"]'::jsonb, 'Correct because Reduced cardiac output can increase BUN/creatinine due to renal hypoperfusion. Treat perfusion deficits to protect kidney function.', 'Cardiac Biomarkers - NCLEX', false, 20, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which finding best supports Lactate and ABG significance in this biomarker scenario?', 'Which finding best supports Lactate and ABG significance in this biomarker scenario?', '[{"id": "a", "text": "Lactate <0.2 is the shock threshold in this note."}, {"id": "b", "text": "Serial rechecks are unnecessary when first value is borderline."}, {"id": "c", "text": "ABG is irrelevant in shock in this note."}, {"id": "d", "text": "Shock/MI may show metabolic acidosis; lactate >2 mmol/L indicates tissue hypoperfusion and helps gauge shock severity."}]'::jsonb, '["d"]'::jsonb, 'Correct because Shock/MI may show metabolic acidosis; lactate >2 mmol/L indicates tissue hypoperfusion and helps gauge shock severity. Escalate perfusion support when lactate and acidosis worsen.', 'Cardiac Biomarkers - NCLEX', false, 21, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse reviews lab trends; which interpretation best matches Lipid panel targets?', 'The nurse reviews lab trends; which interpretation best matches Lipid panel targets?', '[{"id": "a", "text": "LDL >160 is optimal in high-risk in this note."}, {"id": "b", "text": "HDL under 20 is protective in this note."}, {"id": "c", "text": "Incorporate lipid targets into long-term post-ACS risk reduction."}, {"id": "d", "text": "This pattern is more consistent with Troponin priority."}]'::jsonb, '["c"]'::jsonb, 'Correct because Desired lipids listed are total cholesterol <200, LDL <70 in high-risk patients, and HDL >60 as protective. Incorporate lipid targets into long-term post-ACS risk reduction.', 'Cardiac Biomarkers - NCLEX', false, 22, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which clinical judgment is most accurate regarding NCLEX synthesis?', 'Which clinical judgment is most accurate regarding NCLEX synthesis?', '[{"id": "a", "text": "NCLEX summary: Troponin is gold standard and longest-lasting, CK-MB best for reinfarction, BNP for HF dyspnea differentiation, myoglobin earliest but nonspecific."}, {"id": "b", "text": "This pattern is more consistent with Troponin I kinetics."}, {"id": "c", "text": "BNP replaces troponin for MI confirmation in this note."}, {"id": "d", "text": "Serial rechecks are unnecessary when first value is borderline."}]'::jsonb, '["a"]'::jsonb, 'Correct because NCLEX summary: Troponin is gold standard and longest-lasting, CK-MB best for reinfarction, BNP for HF dyspnea differentiation, myoglobin earliest but nonspecific. Match biomarker selection to the clinical question (diagnosis timing vs HF vs reinfarction).', 'Cardiac Biomarkers - NCLEX', false, 23, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'In urgent triage, which conclusion aligns with Biomarker purpose?', 'In urgent triage, which conclusion aligns with Biomarker purpose?', '[{"id": "a", "text": "Serial rechecks are unnecessary when first value is borderline."}, {"id": "b", "text": "This pattern is more consistent with Troponin T kinetics."}, {"id": "c", "text": "Use biomarkers with clinical context to confirm or exclude acute cardiac injury."}, {"id": "d", "text": "Single-point interpretation is always definitive regardless trend direction."}]'::jsonb, '["c"]'::jsonb, 'Correct because Cardiac biomarkers are blood proteins released after cardiac cell injury and are used for MI/HF diagnosis and stress assessment. Use biomarkers with clinical context to confirm or exclude acute cardiac injury.', 'Cardiac Biomarkers - NCLEX', false, 24, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which statement most appropriately reflects Serial testing principle?', 'Which statement most appropriately reflects Serial testing principle?', '[{"id": "a", "text": "One elevated value always confirms MI in this note."}, {"id": "b", "text": "Serial values every 3–6 hours are needed, and a rise-and-fall pattern supports MI rather than one isolated elevation."}, {"id": "c", "text": "This pattern is more consistent with hsTnT utility."}, {"id": "d", "text": "Serial testing is unnecessary in acute chest pain in this note."}]'::jsonb, '["b"]'::jsonb, 'Correct because Serial values every 3–6 hours are needed, and a rise-and-fall pattern supports MI rather than one isolated elevation. Trend interpretation is safer than single-point interpretation.', 'Cardiac Biomarkers - NCLEX', false, 25, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which finding best supports Troponin priority in this biomarker scenario?', 'Which finding best supports Troponin priority in this biomarker scenario?', '[{"id": "a", "text": "BNP is the gold standard for MI in this note."}, {"id": "b", "text": "Myoglobin is more specific than troponin in this note."}, {"id": "c", "text": "Serial rechecks are unnecessary when first value is borderline."}, {"id": "d", "text": "Prioritize troponin trend review in suspected ACS workflows."}]'::jsonb, '["d"]'::jsonb, 'Correct because Troponin is the most specific and sensitive biomarker for MI and is the gold standard in this note. Prioritize troponin trend review in suspected ACS workflows.', 'Cardiac Biomarkers - NCLEX', false, 26, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse reviews lab trends; which interpretation best matches Troponin I kinetics?', 'The nurse reviews lab trends; which interpretation best matches Troponin I kinetics?', '[{"id": "a", "text": "Troponin I peak occurs at 2 hours in this note."}, {"id": "b", "text": "This pattern is more consistent with CK-MB timeline/use."}, {"id": "c", "text": "Serial rechecks are unnecessary when first value is borderline."}, {"id": "d", "text": "Troponin I normal is <0.04 ng/mL, rises 3–6h, peaks 12–24h, normalizes in 7–10 days."}]'::jsonb, '["d"]'::jsonb, 'Correct because Troponin I normal is <0.04 ng/mL, rises 3–6h, peaks 12–24h, normalizes in 7–10 days. Use timing to detect delayed presentations and avoid false reassurance early.', 'Cardiac Biomarkers - NCLEX', false, 27, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which clinical judgment is most accurate regarding Troponin T kinetics?', 'Which clinical judgment is most accurate regarding Troponin T kinetics?', '[{"id": "a", "text": "Recognize prolonged elevation window for recent MI detection."}, {"id": "b", "text": "Single-point interpretation is always definitive regardless trend direction."}, {"id": "c", "text": "This pattern is more consistent with CK-MM limitation."}, {"id": "d", "text": "Serial rechecks are unnecessary when first value is borderline."}]'::jsonb, '["a"]'::jsonb, 'Correct because Troponin T normal is <0.01 ng/mL, rises 3–6h, peaks 12–24h, and normalizes over 10–14 days. Recognize prolonged elevation window for recent MI detection.', 'Cardiac Biomarkers - NCLEX', false, 28, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'In urgent triage, which conclusion aligns with hsTnT utility?', 'In urgent triage, which conclusion aligns with hsTnT utility?', '[{"id": "a", "text": "High-sensitivity Troponin T can detect smaller myocardial infarctions."}, {"id": "b", "text": "This pattern is more consistent with CK-BB limitation."}, {"id": "c", "text": "hsTnT is used only for heart failure in this note."}, {"id": "d", "text": "Serial rechecks are unnecessary when first value is borderline."}]'::jsonb, '["a"]'::jsonb, 'Correct because High-sensitivity Troponin T can detect smaller myocardial infarctions. Interpret small dynamic changes carefully in early injury.', 'Cardiac Biomarkers - NCLEX', false, 29, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which statement most appropriately reflects CK isoform composition?', 'Which statement most appropriately reflects CK isoform composition?', '[{"id": "a", "text": "Serial rechecks are unnecessary when first value is borderline."}, {"id": "b", "text": "This pattern is more consistent with BNP physiology."}, {"id": "c", "text": "Know isoform proportions to avoid misattributing skeletal injury as MI."}, {"id": "d", "text": "CK-BB is dominant in healthy blood in this note."}]'::jsonb, '["c"]'::jsonb, 'Correct because CK-MM is 96–100%, CK-MB is 0–5%, and CK-BB is about 0% in normal distribution listed. Know isoform proportions to avoid misattributing skeletal injury as MI.', 'Cardiac Biomarkers - NCLEX', false, 30, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which finding best supports CK-MB timeline/use in this biomarker scenario?', 'Which finding best supports CK-MB timeline/use in this biomarker scenario?', '[{"id": "a", "text": "This pattern is more consistent with BNP ranges."}, {"id": "b", "text": "CK-MB has no role in reinfarction in this note."}, {"id": "c", "text": "CK-MB rises 4–6h, peaks 18–24h, normalizes 48–72h, and is useful for MI and re-infarction detection."}, {"id": "d", "text": "Serial rechecks are unnecessary when first value is borderline."}]'::jsonb, '["c"]'::jsonb, 'Correct because CK-MB rises 4–6h, peaks 18–24h, normalizes 48–72h, and is useful for MI and re-infarction detection. Use CK-MB especially when looking for reinfarction after initial event.', 'Cardiac Biomarkers - NCLEX', false, 31, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse reviews lab trends; which interpretation best matches CK-MM limitation?', 'The nurse reviews lab trends; which interpretation best matches CK-MM limitation?', '[{"id": "a", "text": "CK-MM is most cardiac-specific marker in this note."}, {"id": "b", "text": "Avoid diagnosing MI from CK-MM elevation alone."}, {"id": "c", "text": "This pattern is more consistent with BNP clinical use."}, {"id": "d", "text": "CK-MM excludes muscle injury in this note."}]'::jsonb, '["b"]'::jsonb, 'Correct because CK-MM reflects skeletal muscle injury such as rhabdomyolysis and is not cardiac-specific. Avoid diagnosing MI from CK-MM elevation alone.', 'Cardiac Biomarkers - NCLEX', false, 32, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which clinical judgment is most accurate regarding CK-BB limitation?', 'Which clinical judgment is most accurate regarding CK-BB limitation?', '[{"id": "a", "text": "CK-BB is associated with brain/smooth muscle injury and is not used for cardiac monitoring."}, {"id": "b", "text": "Single-point interpretation is always definitive regardless trend direction."}, {"id": "c", "text": "CK-BB is preferred biomarker for MI in this note."}, {"id": "d", "text": "CK-BB comes from ventricular myocardium in this note."}]'::jsonb, '["a"]'::jsonb, 'Correct because CK-BB is associated with brain/smooth muscle injury and is not used for cardiac monitoring. Keep CK-BB out of MI-focused biomarker decisions.', 'Cardiac Biomarkers - NCLEX', false, 33, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'In urgent triage, which conclusion aligns with BNP physiology?', 'In urgent triage, which conclusion aligns with BNP physiology?', '[{"id": "a", "text": "Single-point interpretation is always definitive regardless trend direction."}, {"id": "b", "text": "Interpret BNP as volume-stress signal rather than infarction specificity."}, {"id": "c", "text": "BNP is unrelated to ventricular stretch in this note."}, {"id": "d", "text": "BNP rises only from skeletal injury in this note."}]'::jsonb, '["b"]'::jsonb, 'Correct because BNP is released from ventricular myocytes when stretched by volume overload. Interpret BNP as volume-stress signal rather than infarction specificity.', 'Cardiac Biomarkers - NCLEX', false, 34, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which statement most appropriately reflects BNP ranges?', 'Which statement most appropriately reflects BNP ranges?', '[{"id": "a", "text": "BNP <20 defines severe HF in this note."}, {"id": "b", "text": "Single-point interpretation is always definitive regardless trend direction."}, {"id": "c", "text": "BNP >400 excludes HF in this note."}, {"id": "d", "text": "BNP normal is <100 pg/mL; 100–400 possible HF; >400 likely HF exacerbation."}]'::jsonb, '["d"]'::jsonb, 'Correct because BNP normal is <100 pg/mL; 100–400 possible HF; >400 likely HF exacerbation. Use BNP strata to grade heart-failure likelihood and urgency.', 'Cardiac Biomarkers - NCLEX', false, 35, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which finding best supports BNP clinical use in this biomarker scenario?', 'Which finding best supports BNP clinical use in this biomarker scenario?', '[{"id": "a", "text": "BNP has no prognostic value in this note."}, {"id": "b", "text": "Single-point interpretation is always definitive regardless trend direction."}, {"id": "c", "text": "Apply BNP trends to dyspnea triage and HF trajectory planning."}, {"id": "d", "text": "Serial rechecks are unnecessary when first value is borderline."}]'::jsonb, '["c"]'::jsonb, 'Correct because BNP helps differentiate cardiac from pulmonary dyspnea, guides diuresis/discharge, and higher BNP suggests worse prognosis. Apply BNP trends to dyspnea triage and HF trajectory planning.', 'Cardiac Biomarkers - NCLEX', false, 36, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse reviews lab trends; which interpretation best matches BNP not MI marker?', 'The nurse reviews lab trends; which interpretation best matches BNP not MI marker?', '[{"id": "a", "text": "BNP rise alone proves STEMI in this note."}, {"id": "b", "text": "Single-point interpretation is always definitive regardless trend direction."}, {"id": "c", "text": "Serial rechecks are unnecessary when first value is borderline."}, {"id": "d", "text": "The note explicitly states BNP does not indicate MI; it indicates fluid overload/heart failure context."}]'::jsonb, '["d"]'::jsonb, 'Correct because The note explicitly states BNP does not indicate MI; it indicates fluid overload/heart failure context. Do not substitute BNP for troponin in ACS diagnosis.', 'Cardiac Biomarkers - NCLEX', false, 37, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which clinical judgment is most accurate regarding NT-proBNP reference?', 'Which clinical judgment is most accurate regarding NT-proBNP reference?', '[{"id": "a", "text": "This pattern is more consistent with BUN/creatinine interpretation."}, {"id": "b", "text": "Single-point interpretation is always definitive regardless trend direction."}, {"id": "c", "text": "NT-proBNP normal is <30 in this note."}, {"id": "d", "text": "Account for assay type when interpreting natriuretic peptide results."}]'::jsonb, '["d"]'::jsonb, 'Correct because NT-proBNP normal is listed as <300 pg/mL and has longer half-life. Account for assay type when interpreting natriuretic peptide results.', 'Cardiac Biomarkers - NCLEX', false, 38, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'In urgent triage, which conclusion aligns with Myoglobin kinetics?', 'In urgent triage, which conclusion aligns with Myoglobin kinetics?', '[{"id": "a", "text": "Single-point interpretation is always definitive regardless trend direction."}, {"id": "b", "text": "Myoglobin rises after troponin peak in this note."}, {"id": "c", "text": "Serial rechecks are unnecessary when first value is borderline."}, {"id": "d", "text": "Myoglobin rises first at 1–3h after MI but normalizes quickly within 24h."}]'::jsonb, '["d"]'::jsonb, 'Correct because Myoglobin rises first at 1–3h after MI but normalizes quickly within 24h. Use for very early phase support, then rely on specific markers.', 'Cardiac Biomarkers - NCLEX', false, 39, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which statement most appropriately reflects Myoglobin limitation/use?', 'Which statement most appropriately reflects Myoglobin limitation/use?', '[{"id": "a", "text": "Myoglobin is highly cardiac-specific in this note."}, {"id": "b", "text": "Avoid overcalling MI from isolated myoglobin elevation."}, {"id": "c", "text": "This pattern is more consistent with Lactate and ABG significance."}, {"id": "d", "text": "Single-point interpretation is always definitive regardless trend direction."}]'::jsonb, '["b"]'::jsonb, 'Correct because Myoglobin is not cardiac-specific and is used mainly for early rule-out when normal at around 3h. Avoid overcalling MI from isolated myoglobin elevation.', 'Cardiac Biomarkers - NCLEX', false, 40, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which finding best supports Timeline comparison in this biomarker scenario?', 'Which finding best supports Timeline comparison in this biomarker scenario?', '[{"id": "a", "text": "Myoglobin persists longest in this note."}, {"id": "b", "text": "This pattern is more consistent with Lipid panel targets."}, {"id": "c", "text": "Timeline summary: myoglobin earliest/shortest, CK-MB intermediate, troponin longest duration."}, {"id": "d", "text": "Troponin clears before CK-MB in this note."}]'::jsonb, '["c"]'::jsonb, 'Correct because Timeline summary: myoglobin earliest/shortest, CK-MB intermediate, troponin longest duration. Choose marker by time-from-onset and diagnostic objective.', 'Cardiac Biomarkers - NCLEX', false, 41, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse reviews lab trends; which interpretation best matches BUN/creatinine interpretation?', 'The nurse reviews lab trends; which interpretation best matches BUN/creatinine interpretation?', '[{"id": "a", "text": "Use renal trends to separate prerenal dehydration from intrinsic decline."}, {"id": "b", "text": "This pattern is more consistent with NCLEX synthesis."}, {"id": "c", "text": "High BUN with normal creatinine proves MI in this note."}, {"id": "d", "text": "Serial rechecks are unnecessary when first value is borderline."}]'::jsonb, '["a"]'::jsonb, 'Correct because BUN 7–20 and creatinine 0.6–1.2 are listed normal; high BUN with normal creatinine suggests dehydration, while both high suggest renal impairment. Use renal trends to separate prerenal dehydration from intrinsic decline.', 'Cardiac Biomarkers - NCLEX', false, 42, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which clinical judgment is most accurate regarding Low-output renal effect?', 'Which clinical judgment is most accurate regarding Low-output renal effect?', '[{"id": "a", "text": "This pattern is more consistent with Biomarker purpose."}, {"id": "b", "text": "BUN/Cr are unrelated to hemodynamics in this note."}, {"id": "c", "text": "Reduced cardiac output can increase BUN/creatinine due to renal hypoperfusion."}, {"id": "d", "text": "Renal perfusion is unaffected by cardiac output in this note."}]'::jsonb, '["c"]'::jsonb, 'Correct because Reduced cardiac output can increase BUN/creatinine due to renal hypoperfusion. Treat perfusion deficits to protect kidney function.', 'Cardiac Biomarkers - NCLEX', false, 43, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'In urgent triage, which conclusion aligns with Lactate and ABG significance?', 'In urgent triage, which conclusion aligns with Lactate and ABG significance?', '[{"id": "a", "text": "Lactate <0.2 is the shock threshold in this note."}, {"id": "b", "text": "ABG is irrelevant in shock in this note."}, {"id": "c", "text": "Escalate perfusion support when lactate and acidosis worsen."}, {"id": "d", "text": "Serial rechecks are unnecessary when first value is borderline."}]'::jsonb, '["c"]'::jsonb, 'Correct because Shock/MI may show metabolic acidosis; lactate >2 mmol/L indicates tissue hypoperfusion and helps gauge shock severity. Escalate perfusion support when lactate and acidosis worsen.', 'Cardiac Biomarkers - NCLEX', false, 44, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which statement most appropriately reflects Lipid panel targets?', 'Which statement most appropriately reflects Lipid panel targets?', '[{"id": "a", "text": "Desired lipids listed are total cholesterol <200, LDL <70 in high-risk patients, and HDL >60 as protective."}, {"id": "b", "text": "LDL >160 is optimal in high-risk in this note."}, {"id": "c", "text": "This pattern is more consistent with Troponin priority."}, {"id": "d", "text": "HDL under 20 is protective in this note."}]'::jsonb, '["a"]'::jsonb, 'Correct because Desired lipids listed are total cholesterol <200, LDL <70 in high-risk patients, and HDL >60 as protective. Incorporate lipid targets into long-term post-ACS risk reduction.', 'Cardiac Biomarkers - NCLEX', false, 45, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which finding best supports NCLEX synthesis in this biomarker scenario?', 'Which finding best supports NCLEX synthesis in this biomarker scenario?', '[{"id": "a", "text": "Match biomarker selection to the clinical question (diagnosis timing vs HF vs reinfarction)."}, {"id": "b", "text": "Myoglobin is best reinfarction marker in this note."}, {"id": "c", "text": "Single-point interpretation is always definitive regardless trend direction."}, {"id": "d", "text": "Serial rechecks are unnecessary when first value is borderline."}]'::jsonb, '["a"]'::jsonb, 'Correct because NCLEX summary: Troponin is gold standard and longest-lasting, CK-MB best for reinfarction, BNP for HF dyspnea differentiation, myoglobin earliest but nonspecific. Match biomarker selection to the clinical question (diagnosis timing vs HF vs reinfarction).', 'Cardiac Biomarkers - NCLEX', false, 46, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse reviews lab trends; which interpretation best matches Biomarker purpose?', 'The nurse reviews lab trends; which interpretation best matches Biomarker purpose?', '[{"id": "a", "text": "Cardiac biomarkers are blood proteins released after cardiac cell injury and are used for MI/HF diagnosis and stress assessment."}, {"id": "b", "text": "This pattern is more consistent with Troponin T kinetics."}, {"id": "c", "text": "Serial rechecks are unnecessary when first value is borderline."}, {"id": "d", "text": "Single-point interpretation is always definitive regardless trend direction."}]'::jsonb, '["a"]'::jsonb, 'Correct because Cardiac biomarkers are blood proteins released after cardiac cell injury and are used for MI/HF diagnosis and stress assessment. Use biomarkers with clinical context to confirm or exclude acute cardiac injury.', 'Cardiac Biomarkers - NCLEX', false, 47, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which clinical judgment is most accurate regarding Serial testing principle?', 'Which clinical judgment is most accurate regarding Serial testing principle?', '[{"id": "a", "text": "Single-point interpretation is always definitive regardless trend direction."}, {"id": "b", "text": "One elevated value always confirms MI in this note."}, {"id": "c", "text": "Serial rechecks are unnecessary when first value is borderline."}, {"id": "d", "text": "Trend interpretation is safer than single-point interpretation."}]'::jsonb, '["d"]'::jsonb, 'Correct because Serial values every 3–6 hours are needed, and a rise-and-fall pattern supports MI rather than one isolated elevation. Trend interpretation is safer than single-point interpretation.', 'Cardiac Biomarkers - NCLEX', false, 48, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'In urgent triage, which conclusion aligns with Troponin priority?', 'In urgent triage, which conclusion aligns with Troponin priority?', '[{"id": "a", "text": "This pattern is more consistent with CK isoform composition."}, {"id": "b", "text": "Myoglobin is more specific than troponin in this note."}, {"id": "c", "text": "BNP is the gold standard for MI in this note."}, {"id": "d", "text": "Troponin is the most specific and sensitive biomarker for MI and is the gold standard in this note."}]'::jsonb, '["d"]'::jsonb, 'Correct because Troponin is the most specific and sensitive biomarker for MI and is the gold standard in this note. Prioritize troponin trend review in suspected ACS workflows.', 'Cardiac Biomarkers - NCLEX', false, 49, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which statement most appropriately reflects Troponin I kinetics?', 'Which statement most appropriately reflects Troponin I kinetics?', '[{"id": "a", "text": "Troponin I normalizes within 12 hours in this note."}, {"id": "b", "text": "This pattern is more consistent with CK-MB timeline/use."}, {"id": "c", "text": "Serial rechecks are unnecessary when first value is borderline."}, {"id": "d", "text": "Use timing to detect delayed presentations and avoid false reassurance early."}]'::jsonb, '["d"]'::jsonb, 'Correct because Troponin I normal is <0.04 ng/mL, rises 3–6h, peaks 12–24h, normalizes in 7–10 days. Use timing to detect delayed presentations and avoid false reassurance early.', 'Cardiac Biomarkers - NCLEX', false, 50, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'A patient is evaluated for Biomarker purpose. Which findings/actions are appropriate? (Select all that apply)', 'A patient is evaluated for Biomarker purpose. Which findings/actions are appropriate? (Select all that apply)', '[{"id": "a", "text": "They assist MI and HF evaluation."}, {"id": "b", "text": "Cardiac injury does not alter biomarker levels in this note."}, {"id": "c", "text": "Biomarkers only diagnose pulmonary embolism in this note."}, {"id": "d", "text": "They assess cardiac stress patterns."}, {"id": "e", "text": "Biomarkers rise when cardiac cells are damaged."}]'::jsonb, '["a", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: Cardiac biomarkers are blood proteins released after cardiac cell injury and are used for MI/HF diagnosis and stress assessment.', 'Cardiac Biomarkers - NCLEX', true, 51, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'For care involving Serial testing principle, which statements are correct? (Select all that apply)', 'For care involving Serial testing principle, which statements are correct? (Select all that apply)', '[{"id": "a", "text": "Serial testing is unnecessary in acute chest pain in this note."}, {"id": "b", "text": "One elevated value always confirms MI in this note."}, {"id": "c", "text": "Single value alone is insufficient for MI confirmation."}, {"id": "d", "text": "Rise-and-fall pattern supports MI."}, {"id": "e", "text": "Serial q3–6h testing is listed."}]'::jsonb, '["c", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: Serial values every 3–6 hours are needed, and a rise-and-fall pattern supports MI rather than one isolated elevation.', 'Cardiac Biomarkers - NCLEX', true, 52, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse plans management around Troponin priority. Which items belong in the plan? (Select all that apply)', 'The nurse plans management around Troponin priority. Which items belong in the plan? (Select all that apply)', '[{"id": "a", "text": "BNP is the gold standard for MI in this note."}, {"id": "b", "text": "Troponin has highest NCLEX priority in this section."}, {"id": "c", "text": "Troponin is gold standard for MI in this note."}, {"id": "d", "text": "Troponin is both highly sensitive and specific in note."}, {"id": "e", "text": "Myoglobin is more specific than troponin in this note."}]'::jsonb, '["b", "c", "d"]'::jsonb, 'Correct selections align with note-based facts: Troponin is the most specific and sensitive biomarker for MI and is the gold standard in this note.', 'Cardiac Biomarkers - NCLEX', true, 53, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'During reassessment, which observations support Troponin I kinetics? (Select all that apply)', 'During reassessment, which observations support Troponin I kinetics? (Select all that apply)', '[{"id": "a", "text": "Troponin I normalizes within 12 hours in this note."}, {"id": "b", "text": "Peak is 12–24 hours."}, {"id": "c", "text": "Troponin I peak occurs at 2 hours in this note."}, {"id": "d", "text": "Troponin I can stay elevated for 7–10 days."}, {"id": "e", "text": "Troponin I rises at 3–6 hours."}]'::jsonb, '["b", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: Troponin I normal is <0.04 ng/mL, rises 3–6h, peaks 12–24h, normalizes in 7–10 days.', 'Cardiac Biomarkers - NCLEX', true, 54, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which cues are consistent with Troponin T kinetics in this note? (Select all that apply)', 'Which cues are consistent with Troponin T kinetics in this note? (Select all that apply)', '[{"id": "a", "text": "Troponin T normal is <0.01 ng/mL."}, {"id": "b", "text": "Troponin T has no normal reference in this note."}, {"id": "c", "text": "Duration extends up to 10–14 days."}, {"id": "d", "text": "Troponin T is gone by 24 hours in this note."}, {"id": "e", "text": "Rise/peak times mirror early troponin kinetics."}]'::jsonb, '["a", "c", "e"]'::jsonb, 'Correct selections align with note-based facts: Troponin T normal is <0.01 ng/mL, rises 3–6h, peaks 12–24h, and normalizes over 10–14 days.', 'Cardiac Biomarkers - NCLEX', true, 55, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'A patient is evaluated for hsTnT utility. Which findings/actions are appropriate? (Select all that apply)', 'A patient is evaluated for hsTnT utility. Which findings/actions are appropriate? (Select all that apply)', '[{"id": "a", "text": "Sensitivity is higher than conventional threshold-only approach."}, {"id": "b", "text": "hsTnT detects smaller infarcts in this note."}, {"id": "c", "text": "hsTnT is less sensitive than CK-MB in this note."}, {"id": "d", "text": "hsTnT is used only for heart failure in this note."}, {"id": "e", "text": "Useful in early subtle MI detection."}]'::jsonb, '["a", "b", "e"]'::jsonb, 'Correct selections align with note-based facts: High-sensitivity Troponin T can detect smaller myocardial infarctions.', 'Cardiac Biomarkers - NCLEX', true, 56, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'For care involving CK isoform composition, which statements are correct? (Select all that apply)', 'For care involving CK isoform composition, which statements are correct? (Select all that apply)', '[{"id": "a", "text": "CK-BB is minimal in routine blood profile here."}, {"id": "b", "text": "CK-BB is dominant in healthy blood in this note."}, {"id": "c", "text": "CK-MB normal proportion is small."}, {"id": "d", "text": "CK-MM is dominant fraction in this note."}, {"id": "e", "text": "CK-MB comprises most CK in this note."}]'::jsonb, '["a", "c", "d"]'::jsonb, 'Correct selections align with note-based facts: CK-MM is 96–100%, CK-MB is 0–5%, and CK-BB is about 0% in normal distribution listed.', 'Cardiac Biomarkers - NCLEX', true, 57, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse plans management around CK-MB timeline/use. Which items belong in the plan? (Select all that apply)', 'The nurse plans management around CK-MB timeline/use. Which items belong in the plan? (Select all that apply)', '[{"id": "a", "text": "CK-MB remains elevated for 14 days in this note."}, {"id": "b", "text": "Rise/peak/normalization windows are listed."}, {"id": "c", "text": "CK-MB normalizes faster than troponin."}, {"id": "d", "text": "CK-MB has no role in reinfarction in this note."}, {"id": "e", "text": "CK-MB is useful for reinfarction detection."}]'::jsonb, '["b", "c", "e"]'::jsonb, 'Correct selections align with note-based facts: CK-MB rises 4–6h, peaks 18–24h, normalizes 48–72h, and is useful for MI and re-infarction detection.', 'Cardiac Biomarkers - NCLEX', true, 58, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'During reassessment, which observations support CK-MM limitation? (Select all that apply)', 'During reassessment, which observations support CK-MM limitation? (Select all that apply)', '[{"id": "a", "text": "CK-MM excludes muscle injury in this note."}, {"id": "b", "text": "CK-MM source is skeletal muscle."}, {"id": "c", "text": "CK-MM is not cardiac-specific in this note."}, {"id": "d", "text": "CK-MM is most cardiac-specific marker in this note."}, {"id": "e", "text": "CK-MM can rise in rhabdomyolysis."}]'::jsonb, '["b", "c", "e"]'::jsonb, 'Correct selections align with note-based facts: CK-MM reflects skeletal muscle injury such as rhabdomyolysis and is not cardiac-specific.', 'Cardiac Biomarkers - NCLEX', true, 59, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which cues are consistent with CK-BB limitation in this note? (Select all that apply)', 'Which cues are consistent with CK-BB limitation in this note? (Select all that apply)', '[{"id": "a", "text": "CK-BB comes from ventricular myocardium in this note."}, {"id": "b", "text": "CK-BB can relate to bowel infarction in note."}, {"id": "c", "text": "CK-BB is linked to brain/smooth muscle."}, {"id": "d", "text": "CK-BB is not cardiac marker of choice."}, {"id": "e", "text": "CK-BB is preferred biomarker for MI in this note."}]'::jsonb, '["b", "c", "d"]'::jsonb, 'Correct selections align with note-based facts: CK-BB is associated with brain/smooth muscle injury and is not used for cardiac monitoring.', 'Cardiac Biomarkers - NCLEX', true, 60, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'A patient is evaluated for BNP physiology. Which findings/actions are appropriate? (Select all that apply)', 'A patient is evaluated for BNP physiology. Which findings/actions are appropriate? (Select all that apply)', '[{"id": "a", "text": "Volume overload increases BNP."}, {"id": "b", "text": "BNP reflects wall stress in this note."}, {"id": "c", "text": "BNP is unrelated to ventricular stretch in this note."}, {"id": "d", "text": "Ventricular stretch triggers BNP release."}, {"id": "e", "text": "BNP rises only from skeletal injury in this note."}]'::jsonb, '["a", "b", "d"]'::jsonb, 'Correct selections align with note-based facts: BNP is released from ventricular myocytes when stretched by volume overload.', 'Cardiac Biomarkers - NCLEX', true, 61, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'For care involving BNP ranges, which statements are correct? (Select all that apply)', 'For care involving BNP ranges, which statements are correct? (Select all that apply)', '[{"id": "a", "text": "100–400 suggests possible HF."}, {"id": "b", "text": "BNP <20 defines severe HF in this note."}, {"id": "c", "text": ">400 suggests likely HF exacerbation."}, {"id": "d", "text": "BNP >400 excludes HF in this note."}, {"id": "e", "text": "BNP <100 is normal in this note."}]'::jsonb, '["a", "c", "e"]'::jsonb, 'Correct selections align with note-based facts: BNP normal is <100 pg/mL; 100–400 possible HF; >400 likely HF exacerbation.', 'Cardiac Biomarkers - NCLEX', true, 62, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse plans management around BNP clinical use. Which items belong in the plan? (Select all that apply)', 'The nurse plans management around BNP clinical use. Which items belong in the plan? (Select all that apply)', '[{"id": "a", "text": "BNP has no prognostic value in this note."}, {"id": "b", "text": "BNP can separate cardiac vs pulmonary dyspnea causes."}, {"id": "c", "text": "BNP confirms MI infarct size directly in this note."}, {"id": "d", "text": "BNP helps guide diuretic and discharge decisions."}, {"id": "e", "text": "Higher BNP correlates with worse prognosis."}]'::jsonb, '["b", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: BNP helps differentiate cardiac from pulmonary dyspnea, guides diuresis/discharge, and higher BNP suggests worse prognosis.', 'Cardiac Biomarkers - NCLEX', true, 63, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'During reassessment, which observations support BNP not MI marker? (Select all that apply)', 'During reassessment, which observations support BNP not MI marker? (Select all that apply)', '[{"id": "a", "text": "Troponin remains MI marker priority."}, {"id": "b", "text": "BNP indicates volume overload, not infarction specificity."}, {"id": "c", "text": "BNP is the most specific MI marker in this note."}, {"id": "d", "text": "BNP rise alone proves STEMI in this note."}, {"id": "e", "text": "BNP is HF-oriented biomarker in note."}]'::jsonb, '["a", "b", "e"]'::jsonb, 'Correct selections align with note-based facts: The note explicitly states BNP does not indicate MI; it indicates fluid overload/heart failure context.', 'Cardiac Biomarkers - NCLEX', true, 64, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which cues are consistent with NT-proBNP reference in this note? (Select all that apply)', 'Which cues are consistent with NT-proBNP reference in this note? (Select all that apply)', '[{"id": "a", "text": "NT-proBNP has shorter half-life than BNP in this note."}, {"id": "b", "text": "NT-proBNP normal is <30 in this note."}, {"id": "c", "text": "NT-proBNP interpretation differs from BNP thresholds."}, {"id": "d", "text": "Longer half-life is noted."}, {"id": "e", "text": "NT-proBNP reference <300 is listed."}]'::jsonb, '["c", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: NT-proBNP normal is listed as <300 pg/mL and has longer half-life.', 'Cardiac Biomarkers - NCLEX', true, 65, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'A patient is evaluated for Myoglobin kinetics. Which findings/actions are appropriate? (Select all that apply)', 'A patient is evaluated for Myoglobin kinetics. Which findings/actions are appropriate? (Select all that apply)', '[{"id": "a", "text": "Rise occurs 1–3 hours."}, {"id": "b", "text": "Myoglobin rises after troponin peak in this note."}, {"id": "c", "text": "Myoglobin is earliest riser in note."}, {"id": "d", "text": "Normalization occurs by about 24 hours."}, {"id": "e", "text": "Myoglobin stays elevated 10 days in this note."}]'::jsonb, '["a", "c", "d"]'::jsonb, 'Correct selections align with note-based facts: Myoglobin rises first at 1–3h after MI but normalizes quickly within 24h.', 'Cardiac Biomarkers - NCLEX', true, 66, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'For care involving Myoglobin limitation/use, which statements are correct? (Select all that apply)', 'For care involving Myoglobin limitation/use, which statements are correct? (Select all that apply)', '[{"id": "a", "text": "Myoglobin comes from skeletal and cardiac muscle."}, {"id": "b", "text": "Normal early myoglobin lowers immediate MI likelihood."}, {"id": "c", "text": "Myoglobin alone confirms MI in this note."}, {"id": "d", "text": "Myoglobin is highly cardiac-specific in this note."}, {"id": "e", "text": "Specificity is limited in this note."}]'::jsonb, '["a", "b", "e"]'::jsonb, 'Correct selections align with note-based facts: Myoglobin is not cardiac-specific and is used mainly for early rule-out when normal at around 3h.', 'Cardiac Biomarkers - NCLEX', true, 67, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse plans management around Timeline comparison. Which items belong in the plan? (Select all that apply)', 'The nurse plans management around Timeline comparison. Which items belong in the plan? (Select all that apply)', '[{"id": "a", "text": "Myoglobin persists longest in this note."}, {"id": "b", "text": "CK-MB clears before troponin."}, {"id": "c", "text": "Myoglobin rises earliest in this note."}, {"id": "d", "text": "Troponin clears before CK-MB in this note."}, {"id": "e", "text": "Troponin persists the longest."}]'::jsonb, '["b", "c", "e"]'::jsonb, 'Correct selections align with note-based facts: Timeline summary: myoglobin earliest/shortest, CK-MB intermediate, troponin longest duration.', 'Cardiac Biomarkers - NCLEX', true, 68, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'During reassessment, which observations support BUN/creatinine interpretation? (Select all that apply)', 'During reassessment, which observations support BUN/creatinine interpretation? (Select all that apply)', '[{"id": "a", "text": "High BUN + high creatinine suggests renal impairment."}, {"id": "b", "text": "High BUN with normal creatinine proves MI in this note."}, {"id": "c", "text": "Creatinine normal 0.6–1.2 is listed."}, {"id": "d", "text": "Normal creatinine excludes dehydration in this note."}, {"id": "e", "text": "BUN normal range 7–20 is listed."}]'::jsonb, '["a", "c", "e"]'::jsonb, 'Correct selections align with note-based facts: BUN 7–20 and creatinine 0.6–1.2 are listed normal; high BUN with normal creatinine suggests dehydration, while both high suggest renal impairment.', 'Cardiac Biomarkers - NCLEX', true, 69, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which cues are consistent with Low-output renal effect in this note? (Select all that apply)', 'Which cues are consistent with Low-output renal effect in this note? (Select all that apply)', '[{"id": "a", "text": "BUN/Cr are unrelated to hemodynamics in this note."}, {"id": "b", "text": "Low cardiac output can impair renal perfusion."}, {"id": "c", "text": "Renal markers may rise in low-output states."}, {"id": "d", "text": "Cardiorenal relationship is explicitly noted."}, {"id": "e", "text": "Renal perfusion is unaffected by cardiac output in this note."}]'::jsonb, '["b", "c", "d"]'::jsonb, 'Correct selections align with note-based facts: Reduced cardiac output can increase BUN/creatinine due to renal hypoperfusion.', 'Cardiac Biomarkers - NCLEX', true, 70, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'A patient is evaluated for Lactate and ABG significance. Which findings/actions are appropriate? (Select all that apply)', 'A patient is evaluated for Lactate and ABG significance. Which findings/actions are appropriate? (Select all that apply)', '[{"id": "a", "text": "ABG is irrelevant in shock in this note."}, {"id": "b", "text": "Metabolic acidosis can occur in shock/MI."}, {"id": "c", "text": "ABG/lactate assist shock severity assessment."}, {"id": "d", "text": "Lactate >2 indicates hypoperfusion in note."}, {"id": "e", "text": "Lactate <0.2 is the shock threshold in this note."}]'::jsonb, '["b", "c", "d"]'::jsonb, 'Correct selections align with note-based facts: Shock/MI may show metabolic acidosis; lactate >2 mmol/L indicates tissue hypoperfusion and helps gauge shock severity.', 'Cardiac Biomarkers - NCLEX', true, 71, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'For care involving Lipid panel targets, which statements are correct? (Select all that apply)', 'For care involving Lipid panel targets, which statements are correct? (Select all that apply)', '[{"id": "a", "text": "LDL <70 is listed for high-risk."}, {"id": "b", "text": "Total cholesterol target <200 is listed."}, {"id": "c", "text": "HDL >60 is protective per note."}, {"id": "d", "text": "LDL >160 is optimal in high-risk in this note."}, {"id": "e", "text": "HDL under 20 is protective in this note."}]'::jsonb, '["a", "b", "c"]'::jsonb, 'Correct selections align with note-based facts: Desired lipids listed are total cholesterol <200, LDL <70 in high-risk patients, and HDL >60 as protective.', 'Cardiac Biomarkers - NCLEX', true, 72, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse plans management around NCLEX synthesis. Which items belong in the plan? (Select all that apply)', 'The nurse plans management around NCLEX synthesis. Which items belong in the plan? (Select all that apply)', '[{"id": "a", "text": "Myoglobin is best reinfarction marker in this note."}, {"id": "b", "text": "BNP replaces troponin for MI confirmation in this note."}, {"id": "c", "text": "CK-MB favored for reinfarction detection."}, {"id": "d", "text": "Troponin is top MI marker in NCLEX summary."}, {"id": "e", "text": "BNP and myoglobin have distinct non-overlapping roles."}]'::jsonb, '["c", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: NCLEX summary: Troponin is gold standard and longest-lasting, CK-MB best for reinfarction, BNP for HF dyspnea differentiation, myoglobin earliest but nonspecific.', 'Cardiac Biomarkers - NCLEX', true, 73, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'During reassessment, which observations support Biomarker purpose? (Select all that apply)', 'During reassessment, which observations support Biomarker purpose? (Select all that apply)', '[{"id": "a", "text": "They assist MI and HF evaluation."}, {"id": "b", "text": "Biomarkers only diagnose pulmonary embolism in this note."}, {"id": "c", "text": "They assess cardiac stress patterns."}, {"id": "d", "text": "Biomarkers rise when cardiac cells are damaged."}, {"id": "e", "text": "Cardiac injury does not alter biomarker levels in this note."}]'::jsonb, '["a", "c", "d"]'::jsonb, 'Correct selections align with note-based facts: Cardiac biomarkers are blood proteins released after cardiac cell injury and are used for MI/HF diagnosis and stress assessment.', 'Cardiac Biomarkers - NCLEX', true, 74, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which cues are consistent with Serial testing principle in this note? (Select all that apply)', 'Which cues are consistent with Serial testing principle in this note? (Select all that apply)', '[{"id": "a", "text": "One elevated value always confirms MI in this note."}, {"id": "b", "text": "Serial testing is unnecessary in acute chest pain in this note."}, {"id": "c", "text": "Single value alone is insufficient for MI confirmation."}, {"id": "d", "text": "Serial q3–6h testing is listed."}, {"id": "e", "text": "Rise-and-fall pattern supports MI."}]'::jsonb, '["c", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: Serial values every 3–6 hours are needed, and a rise-and-fall pattern supports MI rather than one isolated elevation.', 'Cardiac Biomarkers - NCLEX', true, 75, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'A patient is evaluated for Troponin priority. Which findings/actions are appropriate? (Select all that apply)', 'A patient is evaluated for Troponin priority. Which findings/actions are appropriate? (Select all that apply)', '[{"id": "a", "text": "Myoglobin is more specific than troponin in this note."}, {"id": "b", "text": "Troponin is both highly sensitive and specific in note."}, {"id": "c", "text": "BNP is the gold standard for MI in this note."}, {"id": "d", "text": "Troponin is gold standard for MI in this note."}, {"id": "e", "text": "Troponin has highest NCLEX priority in this section."}]'::jsonb, '["b", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: Troponin is the most specific and sensitive biomarker for MI and is the gold standard in this note.', 'Cardiac Biomarkers - NCLEX', true, 76, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'For care involving Troponin I kinetics, which statements are correct? (Select all that apply)', 'For care involving Troponin I kinetics, which statements are correct? (Select all that apply)', '[{"id": "a", "text": "Troponin I normalizes within 12 hours in this note."}, {"id": "b", "text": "Troponin I can stay elevated for 7–10 days."}, {"id": "c", "text": "Troponin I peak occurs at 2 hours in this note."}, {"id": "d", "text": "Troponin I rises at 3–6 hours."}, {"id": "e", "text": "Peak is 12–24 hours."}]'::jsonb, '["b", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: Troponin I normal is <0.04 ng/mL, rises 3–6h, peaks 12–24h, normalizes in 7–10 days.', 'Cardiac Biomarkers - NCLEX', true, 77, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse plans management around Troponin T kinetics. Which items belong in the plan? (Select all that apply)', 'The nurse plans management around Troponin T kinetics. Which items belong in the plan? (Select all that apply)', '[{"id": "a", "text": "Rise/peak times mirror early troponin kinetics."}, {"id": "b", "text": "Troponin T normal is <0.01 ng/mL."}, {"id": "c", "text": "Troponin T is gone by 24 hours in this note."}, {"id": "d", "text": "Duration extends up to 10–14 days."}, {"id": "e", "text": "Troponin T has no normal reference in this note."}]'::jsonb, '["a", "b", "d"]'::jsonb, 'Correct selections align with note-based facts: Troponin T normal is <0.01 ng/mL, rises 3–6h, peaks 12–24h, and normalizes over 10–14 days.', 'Cardiac Biomarkers - NCLEX', true, 78, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'During reassessment, which observations support hsTnT utility? (Select all that apply)', 'During reassessment, which observations support hsTnT utility? (Select all that apply)', '[{"id": "a", "text": "Useful in early subtle MI detection."}, {"id": "b", "text": "hsTnT is used only for heart failure in this note."}, {"id": "c", "text": "hsTnT detects smaller infarcts in this note."}, {"id": "d", "text": "hsTnT is less sensitive than CK-MB in this note."}, {"id": "e", "text": "Sensitivity is higher than conventional threshold-only approach."}]'::jsonb, '["a", "c", "e"]'::jsonb, 'Correct selections align with note-based facts: High-sensitivity Troponin T can detect smaller myocardial infarctions.', 'Cardiac Biomarkers - NCLEX', true, 79, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which cues are consistent with CK isoform composition in this note? (Select all that apply)', 'Which cues are consistent with CK isoform composition in this note? (Select all that apply)', '[{"id": "a", "text": "CK-BB is minimal in routine blood profile here."}, {"id": "b", "text": "CK-MM is dominant fraction in this note."}, {"id": "c", "text": "CK-MB normal proportion is small."}, {"id": "d", "text": "CK-MB comprises most CK in this note."}, {"id": "e", "text": "CK-BB is dominant in healthy blood in this note."}]'::jsonb, '["a", "b", "c"]'::jsonb, 'Correct selections align with note-based facts: CK-MM is 96–100%, CK-MB is 0–5%, and CK-BB is about 0% in normal distribution listed.', 'Cardiac Biomarkers - NCLEX', true, 80, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'A patient is evaluated for CK-MB timeline/use. Which findings/actions are appropriate? (Select all that apply)', 'A patient is evaluated for CK-MB timeline/use. Which findings/actions are appropriate? (Select all that apply)', '[{"id": "a", "text": "CK-MB is useful for reinfarction detection."}, {"id": "b", "text": "CK-MB normalizes faster than troponin."}, {"id": "c", "text": "Rise/peak/normalization windows are listed."}, {"id": "d", "text": "CK-MB has no role in reinfarction in this note."}, {"id": "e", "text": "CK-MB remains elevated for 14 days in this note."}]'::jsonb, '["a", "b", "c"]'::jsonb, 'Correct selections align with note-based facts: CK-MB rises 4–6h, peaks 18–24h, normalizes 48–72h, and is useful for MI and re-infarction detection.', 'Cardiac Biomarkers - NCLEX', true, 81, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'For care involving CK-MM limitation, which statements are correct? (Select all that apply)', 'For care involving CK-MM limitation, which statements are correct? (Select all that apply)', '[{"id": "a", "text": "CK-MM can rise in rhabdomyolysis."}, {"id": "b", "text": "CK-MM is most cardiac-specific marker in this note."}, {"id": "c", "text": "CK-MM is not cardiac-specific in this note."}, {"id": "d", "text": "CK-MM excludes muscle injury in this note."}, {"id": "e", "text": "CK-MM source is skeletal muscle."}]'::jsonb, '["a", "c", "e"]'::jsonb, 'Correct selections align with note-based facts: CK-MM reflects skeletal muscle injury such as rhabdomyolysis and is not cardiac-specific.', 'Cardiac Biomarkers - NCLEX', true, 82, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse plans management around CK-BB limitation. Which items belong in the plan? (Select all that apply)', 'The nurse plans management around CK-BB limitation. Which items belong in the plan? (Select all that apply)', '[{"id": "a", "text": "CK-BB is linked to brain/smooth muscle."}, {"id": "b", "text": "CK-BB is preferred biomarker for MI in this note."}, {"id": "c", "text": "CK-BB can relate to bowel infarction in note."}, {"id": "d", "text": "CK-BB comes from ventricular myocardium in this note."}, {"id": "e", "text": "CK-BB is not cardiac marker of choice."}]'::jsonb, '["a", "c", "e"]'::jsonb, 'Correct selections align with note-based facts: CK-BB is associated with brain/smooth muscle injury and is not used for cardiac monitoring.', 'Cardiac Biomarkers - NCLEX', true, 83, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'During reassessment, which observations support BNP physiology? (Select all that apply)', 'During reassessment, which observations support BNP physiology? (Select all that apply)', '[{"id": "a", "text": "Ventricular stretch triggers BNP release."}, {"id": "b", "text": "Volume overload increases BNP."}, {"id": "c", "text": "BNP rises only from skeletal injury in this note."}, {"id": "d", "text": "BNP reflects wall stress in this note."}, {"id": "e", "text": "BNP is unrelated to ventricular stretch in this note."}]'::jsonb, '["a", "b", "d"]'::jsonb, 'Correct selections align with note-based facts: BNP is released from ventricular myocytes when stretched by volume overload.', 'Cardiac Biomarkers - NCLEX', true, 84, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which cues are consistent with BNP ranges in this note? (Select all that apply)', 'Which cues are consistent with BNP ranges in this note? (Select all that apply)', '[{"id": "a", "text": "BNP <20 defines severe HF in this note."}, {"id": "b", "text": "BNP >400 excludes HF in this note."}, {"id": "c", "text": "100–400 suggests possible HF."}, {"id": "d", "text": "BNP <100 is normal in this note."}, {"id": "e", "text": ">400 suggests likely HF exacerbation."}]'::jsonb, '["c", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: BNP normal is <100 pg/mL; 100–400 possible HF; >400 likely HF exacerbation.', 'Cardiac Biomarkers - NCLEX', true, 85, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'A patient is evaluated for BNP clinical use. Which findings/actions are appropriate? (Select all that apply)', 'A patient is evaluated for BNP clinical use. Which findings/actions are appropriate? (Select all that apply)', '[{"id": "a", "text": "Higher BNP correlates with worse prognosis."}, {"id": "b", "text": "BNP can separate cardiac vs pulmonary dyspnea causes."}, {"id": "c", "text": "BNP has no prognostic value in this note."}, {"id": "d", "text": "BNP confirms MI infarct size directly in this note."}, {"id": "e", "text": "BNP helps guide diuretic and discharge decisions."}]'::jsonb, '["a", "b", "e"]'::jsonb, 'Correct selections align with note-based facts: BNP helps differentiate cardiac from pulmonary dyspnea, guides diuresis/discharge, and higher BNP suggests worse prognosis.', 'Cardiac Biomarkers - NCLEX', true, 86, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'For care involving BNP not MI marker, which statements are correct? (Select all that apply)', 'For care involving BNP not MI marker, which statements are correct? (Select all that apply)', '[{"id": "a", "text": "BNP indicates volume overload, not infarction specificity."}, {"id": "b", "text": "BNP is the most specific MI marker in this note."}, {"id": "c", "text": "BNP rise alone proves STEMI in this note."}, {"id": "d", "text": "BNP is HF-oriented biomarker in note."}, {"id": "e", "text": "Troponin remains MI marker priority."}]'::jsonb, '["a", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: The note explicitly states BNP does not indicate MI; it indicates fluid overload/heart failure context.', 'Cardiac Biomarkers - NCLEX', true, 87, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse plans management around NT-proBNP reference. Which items belong in the plan? (Select all that apply)', 'The nurse plans management around NT-proBNP reference. Which items belong in the plan? (Select all that apply)', '[{"id": "a", "text": "NT-proBNP has shorter half-life than BNP in this note."}, {"id": "b", "text": "NT-proBNP interpretation differs from BNP thresholds."}, {"id": "c", "text": "NT-proBNP normal is <30 in this note."}, {"id": "d", "text": "NT-proBNP reference <300 is listed."}, {"id": "e", "text": "Longer half-life is noted."}]'::jsonb, '["b", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: NT-proBNP normal is listed as <300 pg/mL and has longer half-life.', 'Cardiac Biomarkers - NCLEX', true, 88, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'During reassessment, which observations support Myoglobin kinetics? (Select all that apply)', 'During reassessment, which observations support Myoglobin kinetics? (Select all that apply)', '[{"id": "a", "text": "Myoglobin stays elevated 10 days in this note."}, {"id": "b", "text": "Normalization occurs by about 24 hours."}, {"id": "c", "text": "Myoglobin rises after troponin peak in this note."}, {"id": "d", "text": "Myoglobin is earliest riser in note."}, {"id": "e", "text": "Rise occurs 1–3 hours."}]'::jsonb, '["b", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: Myoglobin rises first at 1–3h after MI but normalizes quickly within 24h.', 'Cardiac Biomarkers - NCLEX', true, 89, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which cues are consistent with Myoglobin limitation/use in this note? (Select all that apply)', 'Which cues are consistent with Myoglobin limitation/use in this note? (Select all that apply)', '[{"id": "a", "text": "Myoglobin comes from skeletal and cardiac muscle."}, {"id": "b", "text": "Normal early myoglobin lowers immediate MI likelihood."}, {"id": "c", "text": "Myoglobin alone confirms MI in this note."}, {"id": "d", "text": "Specificity is limited in this note."}, {"id": "e", "text": "Myoglobin is highly cardiac-specific in this note."}]'::jsonb, '["a", "b", "d"]'::jsonb, 'Correct selections align with note-based facts: Myoglobin is not cardiac-specific and is used mainly for early rule-out when normal at around 3h.', 'Cardiac Biomarkers - NCLEX', true, 90, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'A patient is evaluated for Timeline comparison. Which findings/actions are appropriate? (Select all that apply)', 'A patient is evaluated for Timeline comparison. Which findings/actions are appropriate? (Select all that apply)', '[{"id": "a", "text": "Troponin persists the longest."}, {"id": "b", "text": "CK-MB clears before troponin."}, {"id": "c", "text": "Troponin clears before CK-MB in this note."}, {"id": "d", "text": "Myoglobin rises earliest in this note."}, {"id": "e", "text": "Myoglobin persists longest in this note."}]'::jsonb, '["a", "b", "d"]'::jsonb, 'Correct selections align with note-based facts: Timeline summary: myoglobin earliest/shortest, CK-MB intermediate, troponin longest duration.', 'Cardiac Biomarkers - NCLEX', true, 91, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'For care involving BUN/creatinine interpretation, which statements are correct? (Select all that apply)', 'For care involving BUN/creatinine interpretation, which statements are correct? (Select all that apply)', '[{"id": "a", "text": "Normal creatinine excludes dehydration in this note."}, {"id": "b", "text": "BUN normal range 7–20 is listed."}, {"id": "c", "text": "High BUN with normal creatinine proves MI in this note."}, {"id": "d", "text": "Creatinine normal 0.6–1.2 is listed."}, {"id": "e", "text": "High BUN + high creatinine suggests renal impairment."}]'::jsonb, '["b", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: BUN 7–20 and creatinine 0.6–1.2 are listed normal; high BUN with normal creatinine suggests dehydration, while both high suggest renal impairment.', 'Cardiac Biomarkers - NCLEX', true, 92, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse plans management around Low-output renal effect. Which items belong in the plan? (Select all that apply)', 'The nurse plans management around Low-output renal effect. Which items belong in the plan? (Select all that apply)', '[{"id": "a", "text": "Cardiorenal relationship is explicitly noted."}, {"id": "b", "text": "Renal markers may rise in low-output states."}, {"id": "c", "text": "BUN/Cr are unrelated to hemodynamics in this note."}, {"id": "d", "text": "Renal perfusion is unaffected by cardiac output in this note."}, {"id": "e", "text": "Low cardiac output can impair renal perfusion."}]'::jsonb, '["a", "b", "e"]'::jsonb, 'Correct selections align with note-based facts: Reduced cardiac output can increase BUN/creatinine due to renal hypoperfusion.', 'Cardiac Biomarkers - NCLEX', true, 93, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'During reassessment, which observations support Lactate and ABG significance? (Select all that apply)', 'During reassessment, which observations support Lactate and ABG significance? (Select all that apply)', '[{"id": "a", "text": "Lactate <0.2 is the shock threshold in this note."}, {"id": "b", "text": "Metabolic acidosis can occur in shock/MI."}, {"id": "c", "text": "ABG/lactate assist shock severity assessment."}, {"id": "d", "text": "Lactate >2 indicates hypoperfusion in note."}, {"id": "e", "text": "ABG is irrelevant in shock in this note."}]'::jsonb, '["b", "c", "d"]'::jsonb, 'Correct selections align with note-based facts: Shock/MI may show metabolic acidosis; lactate >2 mmol/L indicates tissue hypoperfusion and helps gauge shock severity.', 'Cardiac Biomarkers - NCLEX', true, 94, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which cues are consistent with Lipid panel targets in this note? (Select all that apply)', 'Which cues are consistent with Lipid panel targets in this note? (Select all that apply)', '[{"id": "a", "text": "Total cholesterol target <200 is listed."}, {"id": "b", "text": "LDL >160 is optimal in high-risk in this note."}, {"id": "c", "text": "HDL under 20 is protective in this note."}, {"id": "d", "text": "HDL >60 is protective per note."}, {"id": "e", "text": "LDL <70 is listed for high-risk."}]'::jsonb, '["a", "d", "e"]'::jsonb, 'Correct selections align with note-based facts: Desired lipids listed are total cholesterol <200, LDL <70 in high-risk patients, and HDL >60 as protective.', 'Cardiac Biomarkers - NCLEX', true, 95, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'A patient is evaluated for NCLEX synthesis. Which findings/actions are appropriate? (Select all that apply)', 'A patient is evaluated for NCLEX synthesis. Which findings/actions are appropriate? (Select all that apply)', '[{"id": "a", "text": "BNP and myoglobin have distinct non-overlapping roles."}, {"id": "b", "text": "Myoglobin is best reinfarction marker in this note."}, {"id": "c", "text": "Troponin is top MI marker in NCLEX summary."}, {"id": "d", "text": "CK-MB favored for reinfarction detection."}, {"id": "e", "text": "BNP replaces troponin for MI confirmation in this note."}]'::jsonb, '["a", "c", "d"]'::jsonb, 'Correct selections align with note-based facts: NCLEX summary: Troponin is gold standard and longest-lasting, CK-MB best for reinfarction, BNP for HF dyspnea differentiation, myoglobin earliest but nonspecific.', 'Cardiac Biomarkers - NCLEX', true, 96, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'For care involving Biomarker purpose, which statements are correct? (Select all that apply)', 'For care involving Biomarker purpose, which statements are correct? (Select all that apply)', '[{"id": "a", "text": "Biomarkers rise when cardiac cells are damaged."}, {"id": "b", "text": "They assess cardiac stress patterns."}, {"id": "c", "text": "They assist MI and HF evaluation."}, {"id": "d", "text": "Cardiac injury does not alter biomarker levels in this note."}, {"id": "e", "text": "Biomarkers only diagnose pulmonary embolism in this note."}]'::jsonb, '["a", "b", "c"]'::jsonb, 'Correct selections align with note-based facts: Cardiac biomarkers are blood proteins released after cardiac cell injury and are used for MI/HF diagnosis and stress assessment.', 'Cardiac Biomarkers - NCLEX', true, 97, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'The nurse plans management around Serial testing principle. Which items belong in the plan? (Select all that apply)', 'The nurse plans management around Serial testing principle. Which items belong in the plan? (Select all that apply)', '[{"id": "a", "text": "One elevated value always confirms MI in this note."}, {"id": "b", "text": "Single value alone is insufficient for MI confirmation."}, {"id": "c", "text": "Rise-and-fall pattern supports MI."}, {"id": "d", "text": "Serial testing is unnecessary in acute chest pain in this note."}, {"id": "e", "text": "Serial q3–6h testing is listed."}]'::jsonb, '["b", "c", "e"]'::jsonb, 'Correct selections align with note-based facts: Serial values every 3–6 hours are needed, and a rise-and-fall pattern supports MI rather than one isolated elevation.', 'Cardiac Biomarkers - NCLEX', true, 98, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'During reassessment, which observations support Troponin priority? (Select all that apply)', 'During reassessment, which observations support Troponin priority? (Select all that apply)', '[{"id": "a", "text": "Troponin has highest NCLEX priority in this section."}, {"id": "b", "text": "Troponin is both highly sensitive and specific in note."}, {"id": "c", "text": "Myoglobin is more specific than troponin in this note."}, {"id": "d", "text": "Troponin is gold standard for MI in this note."}, {"id": "e", "text": "BNP is the gold standard for MI in this note."}]'::jsonb, '["a", "b", "d"]'::jsonb, 'Correct selections align with note-based facts: Troponin is the most specific and sensitive biomarker for MI and is the gold standard in this note.', 'Cardiac Biomarkers - NCLEX', true, 99, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (v_test_id, v_topic_id, 'Which cues are consistent with Troponin I kinetics in this note? (Select all that apply)', 'Which cues are consistent with Troponin I kinetics in this note? (Select all that apply)', '[{"id": "a", "text": "Troponin I can stay elevated for 7–10 days."}, {"id": "b", "text": "Troponin I peak occurs at 2 hours in this note."}, {"id": "c", "text": "Troponin I rises at 3–6 hours."}, {"id": "d", "text": "Troponin I normalizes within 12 hours in this note."}, {"id": "e", "text": "Peak is 12–24 hours."}]'::jsonb, '["a", "c", "e"]'::jsonb, 'Correct selections align with note-based facts: Troponin I normal is <0.04 ng/mL, rises 3–6h, peaks 12–24h, normalizes in 7–10 days.', 'Cardiac Biomarkers - NCLEX', true, 100, 1, true);
END $$;
COMMIT;