BEGIN;
DO $$
DECLARE
  subject_id UUID;
  topic_id UUID;
  test_id BIGINT;
BEGIN
  SELECT id INTO subject_id FROM test_subjects WHERE name ILIKE '%cardio%' LIMIT 1;
  SELECT test_id INTO test_id FROM test_configs WHERE subject_id = subject_id LIMIT 1;
  SELECT id INTO topic_id FROM test_topics WHERE name ILIKE '%ekg%' LIMIT 1;
  IF topic_id IS NULL THEN
    IF subject_id IS NULL THEN
      INSERT INTO test_subjects (name, description) VALUES ('Cardiovascular', 'Cardio notes') RETURNING id INTO subject_id;
    END IF;
    INSERT INTO test_topics (subject_id, name, description, status) VALUES (subject_id, 'EKG', 'Electrocardiogram analysis', 'published') RETURNING id INTO topic_id;
  END IF;

  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'When analyzing the cardiac conduction system, which component accurately reflects SA Node?', 'When analyzing the cardiac conduction system, which component accurately reflects SA Node?', '[{"id": "a", "text": "An irregular rate without pacemaker of the heart"}, {"id": "b", "text": "fires at 60-100 bpm only"}, {"id": "c", "text": "sends wave through atria alone without pacemaker of the heart"}, {"id": "d", "text": "pacemaker of the heart, which fires at 60-100 bpm, and sends wave through atria"}]'::jsonb, '["d"]', 'SA Node is associated with pacemaker of the heart. It fires at 60-100 bpm, and sends wave through atria.', 'EKG', false, 1, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'The nurse is evaluating an ECG strip and identifies characteristics of AV Node. Which finding confirms this?', 'The nurse is evaluating an ECG strip and identifies characteristics of AV Node. Which finding confirms this?', '[{"id": "a", "text": "Complete absence of P waves"}, {"id": "b", "text": "Pauses the signal to let the atria empty before the ventricles contract"}, {"id": "c", "text": "gatekeeper"}, {"id": "d", "text": "An inverted T wave with shortened PR"}]'::jsonb, '["c"]', 'The key characteristic of the AV node is its gatekeeper role; it pauses the signal to let the atria empty before the ventricles contract.', 'EKG', false, 2, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A client''s rhythm strip demonstrates features of Bundle of His. What is the priority nursing intervention or key finding?', 'A client''s rhythm strip demonstrates features of Bundle of His. What is the priority nursing intervention or key finding?', '[{"id": "a", "text": "Administer epinephrine immediately"}, {"id": "b", "text": "Ignore the rhythm as it is an artifact"}, {"id": "c", "text": "Perform unsynchronized defibrillation"}, {"id": "d", "text": "ventricles contract"}]'::jsonb, '["d"]', 'For the Bundle of His, a key finding is ventricular contraction. It is the pathway to the left and right bundle branches and leads to Purkinje fibers.', 'EKG', false, 3, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'Which statement regarding Depolarization is correct based on standard ECG analysis?', 'Which statement regarding Depolarization is correct based on standard ECG analysis?', '[{"id": "a", "text": "It requires immediate defibrillation regardless of pulse"}, {"id": "b", "text": "It is represented by Na+ entering the cell"}, {"id": "c", "text": "It is defined by the charge going from negative to positive"}, {"id": "d", "text": "It indicates normal ventricular repolarization"}]'::jsonb, '["c"]', 'Characteristics of depolarization include Na+ entering the cell and the charge changing from negative to positive.', 'EKG', false, 4, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A novice nurse is asking about Repolarization. The preceptor provides correct teaching by stating:', 'A novice nurse is asking about Repolarization. The preceptor provides correct teaching by stating:', '[{"id": "a", "text": "It is characterized strictly by an absent QRS."}, {"id": "b", "text": "It always requires synchronized cardioversion."}, {"id": "c", "text": "It represents normal atrial repolarization."}, {"id": "d", "text": "It involves cell resets and positive to negative."}]'::jsonb, '["d"]', 'Repolarization involves cell resets and positive to negative. Toward lead = dip DOWN; Away = bump UP.', 'EKG', false, 5, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'When analyzing the cardiac conduction system, which component accurately reflects P Wave?', 'When analyzing the cardiac conduction system, which component accurately reflects P Wave?', '[{"id": "a", "text": "0.08\u20130.10 sec only"}, {"id": "b", "text": "2\u20132.5 small boxes alone without Atrial depolarization"}, {"id": "c", "text": "An irregular rate without Atrial depolarization"}, {"id": "d", "text": "Atrial depolarization, which 0.08\u20130.10 sec, and 2\u20132.5 small boxes"}]'::jsonb, '["d"]', 'P Wave is associated with Atrial depolarization. It 0.08–0.10 sec, and 2–2.5 small boxes.', 'EKG', false, 6, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'The nurse is evaluating an ECG strip and identifies characteristics of PR Interval. Which finding confirms this?', 'The nurse is evaluating an ECG strip and identifies characteristics of PR Interval. Which finding confirms this?', '[{"id": "a", "text": "0.12\u20130.20 sec but with opposing 3\u20135 small boxes"}, {"id": "b", "text": "An inverted T wave with shortened PR"}, {"id": "c", "text": "SA to AV node conduction time"}, {"id": "d", "text": "Complete absence of P waves"}]'::jsonb, '["c"]', 'The key characteristic of PR Interval is SA to AV node conduction time. 0.12–0.20 sec may also be seen.', 'EKG', false, 7, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A client''s rhythm strip demonstrates features of PR Segment. What is the priority nursing intervention or key finding?', 'A client''s rhythm strip demonstrates features of PR Segment. What is the priority nursing intervention or key finding?', '[{"id": "a", "text": "Administer epinephrine immediately"}, {"id": "b", "text": "Ignore the rhythm as it is an artifact"}, {"id": "c", "text": "1\u20133 small boxes"}, {"id": "d", "text": "Perform unsynchronized defibrillation"}]'::jsonb, '["c"]', 'For the PR segment, a key finding is 1–3 small boxes. It reflects AV node delay and typically lasts 0.04–0.12 sec.', 'EKG', false, 8, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'Which statement regarding QRS Complex is correct based on standard ECG analysis?', 'Which statement regarding QRS Complex is correct based on standard ECG analysis?', '[{"id": "a", "text": "It is defined by <0.12 sec (narrow)"}, {"id": "b", "text": "It is represented by Ventricular depolarization but only when >150 bpm"}, {"id": "c", "text": "It requires immediate defibrillation regardless of pulse"}, {"id": "d", "text": "It indicates normal ventricular repolarization"}]'::jsonb, '["a"]', 'Characteristics of the QRS complex include ventricular depolarization and a normal width of <0.12 sec (narrow).', 'EKG', false, 9, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A novice nurse is asking about T Wave. The preceptor provides correct teaching by stating:', 'A novice nurse is asking about T Wave. The preceptor provides correct teaching by stating:', '[{"id": "a", "text": "It always requires synchronized cardioversion."}, {"id": "b", "text": "It represents normal atrial repolarization."}, {"id": "c", "text": "It involves ventricular repolarization and has a variable duration of 0.10\u20130.25 sec."}, {"id": "d", "text": "It is characterized strictly by an absent QRS."}]'::jsonb, '["c"]', 'The T wave reflects ventricular repolarization and has a variable duration of approximately 0.10–0.25 sec.', 'EKG', false, 10, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'When analyzing the cardiac conduction system, which component accurately reflects U Wave?', 'When analyzing the cardiac conduction system, which component accurately reflects U Wave?', '[{"id": "a", "text": "It is always present in all normal ECGs"}, {"id": "b", "text": "It may indicate hypokalemia"}, {"id": "c", "text": "It is a marker of acute STEMI"}, {"id": "d", "text": "It is not always present and may indicate hypokalemia when prominent"}]'::jsonb, '["d"]', 'The U wave is not always present; when prominent, it may indicate hypokalemia.', 'EKG', false, 11, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'The nurse is evaluating an ECG strip and identifies characteristics of Cardioversion. Which finding confirms this?', 'The nurse is evaluating an ECG strip and identifies characteristics of Cardioversion. Which finding confirms this?', '[{"id": "a", "text": "Complete absence of P waves"}, {"id": "b", "text": "LOW energy, SYNC ON (R wave) but with opposing SVT, A-Fib, A-Flutter, V-Tach with pulse"}, {"id": "c", "text": "An inverted T wave with shortened PR"}, {"id": "d", "text": "Patient HAS a pulse"}]'::jsonb, '["d"]', 'The key characteristic of Cardioversion is Patient HAS a pulse. LOW energy, SYNC ON (R wave) may also be seen.', 'EKG', false, 12, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A client''s rhythm strip demonstrates features of Defibrillation. What is the priority nursing intervention or key finding?', 'A client''s rhythm strip demonstrates features of Defibrillation. What is the priority nursing intervention or key finding?', '[{"id": "a", "text": "Ignore the rhythm as it is an artifact"}, {"id": "b", "text": "Administer epinephrine immediately"}, {"id": "c", "text": "V-Fib, pulseless V-Tach. Needs CPR"}, {"id": "d", "text": "Perform unsynchronized defibrillation"}]'::jsonb, '["c"]', 'For defibrillation, a key indication is V-Fib or pulseless V-Tach requiring CPR. The patient has no pulse, and high energy is delivered with SYNC OFF (immediate).', 'EKG', false, 13, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'Which statement regarding Grid Paper Speed is correct based on standard ECG analysis?', 'Which statement regarding Grid Paper Speed is correct based on standard ECG analysis?', '[{"id": "a", "text": "It is represented by 25 mm/sec but only when >150 bpm"}, {"id": "b", "text": "It indicates normal ventricular repolarization"}, {"id": "c", "text": "It requires immediate defibrillation regardless of pulse"}, {"id": "d", "text": "It is defined by standard speed"}]'::jsonb, '["d"]', 'Characteristics of ECG grid paper speed include 25 mm/sec, which is the standard recording speed.', 'EKG', false, 14, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A novice nurse is asking about Small Box. The preceptor provides correct teaching by stating:', 'A novice nurse is asking about Small Box. The preceptor provides correct teaching by stating:', '[{"id": "a", "text": "It involves 0.04 s and 1 mm width."}, {"id": "b", "text": "It is characterized strictly by an absent QRS."}, {"id": "c", "text": "It represents normal atrial repolarization."}, {"id": "d", "text": "It always requires synchronized cardioversion."}]'::jsonb, '["a"]', 'Small Box involves 0.04 s and 1 mm width. QRS width, P-wave duration.', 'EKG', false, 15, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'When analyzing the cardiac conduction system, which component accurately reflects Large Box?', 'When analyzing the cardiac conduction system, which component accurately reflects Large Box?', '[{"id": "a", "text": "PR interval, QRS duration alone without 0.20 s"}, {"id": "b", "text": "0.20 s, which 5 small boxes, and PR interval, QRS duration"}, {"id": "c", "text": "An irregular rate without 0.20 s"}, {"id": "d", "text": "5 small boxes only"}]'::jsonb, '["b"]', 'Large Box is associated with 0.20 s. It 5 small boxes, and PR interval, QRS duration.', 'EKG', false, 16, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'The nurse is evaluating an ECG strip and identifies characteristics of One Second. Which finding confirms this?', 'The nurse is evaluating an ECG strip and identifies characteristics of One Second. Which finding confirms this?', '[{"id": "a", "text": "An inverted T wave with shortened PR"}, {"id": "b", "text": "Complete absence of P waves"}, {"id": "c", "text": "5 large boxes but with opposing HR Calculation"}, {"id": "d", "text": "1.00 s"}]'::jsonb, '["d"]', 'The key characteristic of One Second is 1.00 s. 5 large boxes may also be seen.', 'EKG', false, 17, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A client''s rhythm strip demonstrates features of Heart Rate: Regular. What is the priority nursing intervention or key finding?', 'A client''s rhythm strip demonstrates features of Heart Rate: Regular. What is the priority nursing intervention or key finding?', '[{"id": "a", "text": "Administer epinephrine immediately"}, {"id": "b", "text": "Ignore the rhythm as it is an artifact"}, {"id": "c", "text": "None of the above"}, {"id": "d", "text": "Perform unsynchronized defibrillation"}]'::jsonb, '["c"]', 'For Heart Rate: Regular, the key finding/intervention is . It 300 ÷ Large Boxes and between two R-wave peaks.', 'EKG', false, 18, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'Which statement regarding Heart Rate: Irregular is correct based on standard ECG analysis?', 'Which statement regarding Heart Rate: Irregular is correct based on standard ECG analysis?', '[{"id": "a", "text": "It indicates normal ventricular repolarization"}, {"id": "b", "text": "It is represented by QRS Count \u00d7 10 but only when >150 bpm"}, {"id": "c", "text": "It requires immediate defibrillation regardless of pulse"}, {"id": "d", "text": "It is defined by in a 6-second strip (30 large boxes)"}]'::jsonb, '["d"]', 'Characteristics of Heart Rate: Irregular include: QRS Count × 10. It in a 6-second strip (30 large boxes).', 'EKG', false, 19, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A novice nurse is asking about Heart Rate: Quick. The preceptor provides correct teaching by stating:', 'A novice nurse is asking about Heart Rate: Quick. The preceptor provides correct teaching by stating:', '[{"id": "a", "text": "It involves 300, 150, 100, 75, 60, 50 and memorization rule."}, {"id": "b", "text": "It is characterized strictly by an absent QRS."}, {"id": "c", "text": "It always requires synchronized cardioversion."}, {"id": "d", "text": "It represents normal atrial repolarization."}]'::jsonb, '["a"]', 'Heart Rate: Quick involves 300, 150, 100, 75, 60, 50 and memorization rule. .', 'EKG', false, 20, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'When analyzing the cardiac conduction system, which component accurately reflects Normal Sinus Rhythm?', 'When analyzing the cardiac conduction system, which component accurately reflects Normal Sinus Rhythm?', '[{"id": "a", "text": "60-100 bpm, which Regular rhythm, consistent P waves, PR 0.12-0.20, and No treatment needed"}, {"id": "b", "text": "An irregular rate without 60-100 bpm"}, {"id": "c", "text": "No treatment needed alone without 60-100 bpm"}, {"id": "d", "text": "Regular rhythm, consistent P waves, PR 0.12-0.20 only"}]'::jsonb, '["a"]', 'Normal Sinus Rhythm is associated with 60-100 bpm. It Regular rhythm, consistent P waves, PR 0.12-0.20, and No treatment needed.', 'EKG', false, 21, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'The nurse is evaluating an ECG strip and identifies characteristics of Sinus Bradycardia. Which finding confirms this?', 'The nurse is evaluating an ECG strip and identifies characteristics of Sinus Bradycardia. Which finding confirms this?', '[{"id": "a", "text": "<60 bpm"}, {"id": "b", "text": "Complete absence of P waves"}, {"id": "c", "text": "Regular, normal P waves but with opposing Symptomatic: Atropine. Asymptomatic: Monitor"}, {"id": "d", "text": "An inverted T wave with shortened PR"}]'::jsonb, '["a"]', 'The key characteristic of Sinus Bradycardia is <60 bpm. Regular, normal P waves may also be seen.', 'EKG', false, 22, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A client''s rhythm strip demonstrates features of Sinus Tachycardia. What is the priority nursing intervention or key finding?', 'A client''s rhythm strip demonstrates features of Sinus Tachycardia. What is the priority nursing intervention or key finding?', '[{"id": "a", "text": "Administer epinephrine immediately"}, {"id": "b", "text": "Ignore the rhythm as it is an artifact"}, {"id": "c", "text": "Perform unsynchronized defibrillation"}, {"id": "d", "text": "Calcium Channel Blockers, Beta-Blockers, Digoxin"}]'::jsonb, '["d"]', 'For Sinus Tachycardia, the key finding/intervention is Calcium Channel Blockers, Beta-Blockers, Digoxin. It 100-150 bpm and Regular, normal P.', 'EKG', false, 23, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'Which statement regarding SVT is correct based on standard ECG analysis?', 'Which statement regarding SVT is correct based on standard ECG analysis?', '[{"id": "a", "text": "It is represented by >150 bpm but only when >150 bpm"}, {"id": "b", "text": "It indicates normal ventricular repolarization"}, {"id": "c", "text": "It is defined by Regular, narrow QRS, P hidden"}, {"id": "d", "text": "It requires immediate defibrillation regardless of pulse"}]'::jsonb, '["c"]', 'Characteristics of SVT include: >150 bpm. It Regular, narrow QRS, P hidden.', 'EKG', false, 24, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A novice nurse is asking about Atrial Flutter. The preceptor provides correct teaching by stating:', 'A novice nurse is asking about Atrial Flutter. The preceptor provides correct teaching by stating:', '[{"id": "a", "text": "It always requires synchronized cardioversion."}, {"id": "b", "text": "It involves 250-350 bpm (atria) and Sawtooth F waves."}, {"id": "c", "text": "It is characterized strictly by an absent QRS."}, {"id": "d", "text": "It represents normal atrial repolarization."}]'::jsonb, '["b"]', 'Atrial Flutter involves 250-350 bpm (atria) and Sawtooth F waves. Anticoagulants, Beta-Blockers, Cardioversion.', 'EKG', false, 25, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'When analyzing the cardiac conduction system, which component accurately reflects Atrial Fibrillation?', 'When analyzing the cardiac conduction system, which component accurately reflects Atrial Fibrillation?', '[{"id": "a", "text": "Wavy/chaotic baseline, no distinct P only"}, {"id": "b", "text": "Anticoagulants, Rate/Rhythm control alone without Irregular rate"}, {"id": "c", "text": "Irregular rate, which Wavy/chaotic baseline, no distinct P, and Anticoagulants, Rate/Rhythm control"}, {"id": "d", "text": "An irregular rate without Irregular rate"}]'::jsonb, '["c"]', 'Atrial Fibrillation is associated with Irregular rate. It Wavy/chaotic baseline, no distinct P, and Anticoagulants, Rate/Rhythm control.', 'EKG', false, 26, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'The nurse is evaluating an ECG strip and identifies characteristics of V-Tach. Which finding confirms this?', 'The nurse is evaluating an ECG strip and identifies characteristics of V-Tach. Which finding confirms this?', '[{"id": "a", "text": "Complete absence of P waves"}, {"id": "b", "text": "Wide, bizarre QRS, no P but with opposing Pulse: Cardiovert. No Pulse: Defib + CPR"}, {"id": "c", "text": "An inverted T wave with shortened PR"}, {"id": "d", "text": "100-250 bpm"}]'::jsonb, '["d"]', 'The key characteristic of V-Tach is 100-250 bpm. Wide, bizarre QRS, no P may also be seen.', 'EKG', false, 27, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A client''s rhythm strip demonstrates features of V-Fib. What is the priority nursing intervention or key finding?', 'A client''s rhythm strip demonstrates features of V-Fib. What is the priority nursing intervention or key finding?', '[{"id": "a", "text": "Administer epinephrine immediately"}, {"id": "b", "text": "Ignore the rhythm as it is an artifact"}, {"id": "c", "text": "Defibrillation (unsync), CPR, Epi, Amiodarone"}, {"id": "d", "text": "Perform unsynchronized defibrillation"}]'::jsonb, '["c"]', 'For V-Fib, the key finding/intervention is Defibrillation (unsync), CPR, Epi, Amiodarone. It No effective pulse and Chaotic, no QRS/P.', 'EKG', false, 28, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'Which statement regarding PVCs is correct based on standard ECG analysis?', 'Which statement regarding PVCs is correct based on standard ECG analysis?', '[{"id": "a", "text": "It indicates normal ventricular repolarization"}, {"id": "b", "text": "It requires immediate defibrillation regardless of pulse"}, {"id": "c", "text": "It is defined by Wide bizarre QRS, no preceding P"}, {"id": "d", "text": "It is represented by Occasional irregular beat but only when >150 bpm"}]'::jsonb, '["c"]', 'Characteristics of PVCs include: Occasional irregular beat. It Wide bizarre QRS, no preceding P.', 'EKG', false, 29, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A novice nurse is asking about 1st Degree AV Block. The preceptor provides correct teaching by stating:', 'A novice nurse is asking about 1st Degree AV Block. The preceptor provides correct teaching by stating:', '[{"id": "a", "text": "It involves 60-100 bpm and Prolonged PR (>0.20)."}, {"id": "b", "text": "It is characterized strictly by an absent QRS."}, {"id": "c", "text": "It always requires synchronized cardioversion."}, {"id": "d", "text": "It represents normal atrial repolarization."}]'::jsonb, '["a"]', '1st Degree AV Block involves 60-100 bpm and Prolonged PR (>0.20). No treatment needed.', 'EKG', false, 30, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'When analyzing the cardiac conduction system, which component accurately reflects 2nd Degree Type I?', 'When analyzing the cardiac conduction system, which component accurately reflects 2nd Degree Type I?', '[{"id": "a", "text": "An irregular rate without Variable rate"}, {"id": "b", "text": "Variable rate, which PR progressively lengthens until QRS dropped, and Pacemaker needed"}, {"id": "c", "text": "Pacemaker needed alone without Variable rate"}, {"id": "d", "text": "PR progressively lengthens until QRS dropped only"}]'::jsonb, '["b"]', '2nd Degree Type I is associated with Variable rate. It PR progressively lengthens until QRS dropped, and Pacemaker needed.', 'EKG', false, 31, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'The nurse is evaluating an ECG strip and identifies characteristics of 2nd Degree Type II. Which finding confirms this?', 'The nurse is evaluating an ECG strip and identifies characteristics of 2nd Degree Type II. Which finding confirms this?', '[{"id": "a", "text": "30-50 bpm"}, {"id": "b", "text": "Complete absence of P waves"}, {"id": "c", "text": "Constant PR, dropped QRS but with opposing Pacemaker required urgently"}, {"id": "d", "text": "An inverted T wave with shortened PR"}]'::jsonb, '["a"]', 'The key characteristic of 2nd Degree Type II is 30-50 bpm. Constant PR, dropped QRS may also be seen.', 'EKG', false, 32, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A client''s rhythm strip demonstrates features of 3rd Degree Block. What is the priority nursing intervention or key finding?', 'A client''s rhythm strip demonstrates features of 3rd Degree Block. What is the priority nursing intervention or key finding?', '[{"id": "a", "text": "Emergency pacemaker required"}, {"id": "b", "text": "Administer epinephrine immediately"}, {"id": "c", "text": "Perform unsynchronized defibrillation"}, {"id": "d", "text": "Ignore the rhythm as it is an artifact"}]'::jsonb, '["a"]', 'For 3rd Degree Block, the key finding/intervention is Emergency pacemaker required. It 30-40 bpm and P and QRS completely independent.', 'EKG', false, 33, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'Which statement regarding Artificial Pacemaker is correct based on standard ECG analysis?', 'Which statement regarding Artificial Pacemaker is correct based on standard ECG analysis?', '[{"id": "a", "text": "It requires immediate defibrillation regardless of pulse"}, {"id": "b", "text": "It indicates normal ventricular repolarization"}, {"id": "c", "text": "It is defined by Pacing spikes before P or QRS"}, {"id": "d", "text": "It is represented by Regular paced rate but only when >150 bpm"}]'::jsonb, '["c"]', 'Characteristics of Artificial Pacemaker include: Regular paced rate. It Pacing spikes before P or QRS.', 'EKG', false, 34, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A novice nurse is asking about Asystole. The preceptor provides correct teaching by stating:', 'A novice nurse is asking about Asystole. The preceptor provides correct teaching by stating:', '[{"id": "a", "text": "It is characterized strictly by an absent QRS."}, {"id": "b", "text": "It always requires synchronized cardioversion."}, {"id": "c", "text": "It involves No HR and Flat line. Non-shockable."}, {"id": "d", "text": "It represents normal atrial repolarization."}]'::jsonb, '["c"]', 'Asystole involves No HR and Flat line. Non-shockable. CPR + Epi. Confirm in 2 leads.', 'EKG', false, 35, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'When analyzing the cardiac conduction system, which component accurately reflects Torsades de Pointes?', 'When analyzing the cardiac conduction system, which component accurately reflects Torsades de Pointes?', '[{"id": "a", "text": "QRS twists around baseline only"}, {"id": "b", "text": "An irregular rate without >200 bpm"}, {"id": "c", "text": "IV Magnesium Sulfate alone without >200 bpm"}, {"id": "d", "text": ">200 bpm, which QRS twists around baseline, and IV Magnesium Sulfate"}]'::jsonb, '["d"]', 'Torsades de Pointes is associated with >200 bpm. It QRS twists around baseline, and IV Magnesium Sulfate.', 'EKG', false, 36, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'The nurse is evaluating an ECG strip and identifies characteristics of Cardiac Tamponade. Which finding confirms this?', 'The nurse is evaluating an ECG strip and identifies characteristics of Cardiac Tamponade. Which finding confirms this?', '[{"id": "a", "text": "An inverted T wave with shortened PR"}, {"id": "b", "text": "Electrical Alternans"}, {"id": "c", "text": "Low Voltage QRS, Sinus Tachy but with opposing PR Segment Depression"}, {"id": "d", "text": "Complete absence of P waves"}]'::jsonb, '["b"]', 'The key characteristic of Cardiac Tamponade is Electrical Alternans. Low Voltage QRS, Sinus Tachy may also be seen.', 'EKG', false, 37, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A client''s rhythm strip demonstrates features of SA Node. What is the priority nursing intervention or key finding?', 'A client''s rhythm strip demonstrates features of SA Node. What is the priority nursing intervention or key finding?', '[{"id": "a", "text": "sends wave through atria"}, {"id": "b", "text": "Perform unsynchronized defibrillation"}, {"id": "c", "text": "Administer epinephrine immediately"}, {"id": "d", "text": "Ignore the rhythm as it is an artifact"}]'::jsonb, '["a"]', 'For SA Node, the key finding/intervention is sends wave through atria. It pacemaker of the heart and fires at 60-100 bpm.', 'EKG', false, 38, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'Which statement regarding AV Node is correct based on standard ECG analysis?', 'Which statement regarding AV Node is correct based on standard ECG analysis?', '[{"id": "a", "text": "It requires immediate defibrillation regardless of pulse"}, {"id": "b", "text": "It is defined by pauses signal to let atria dump blood"}, {"id": "c", "text": "It indicates normal ventricular repolarization"}, {"id": "d", "text": "It is represented by gatekeeper but only when >150 bpm"}]'::jsonb, '["b"]', 'Characteristics of AV Node include: gatekeeper. It pauses signal to let atria dump blood.', 'EKG', false, 39, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A novice nurse is asking about Bundle of His. The preceptor provides correct teaching by stating:', 'A novice nurse is asking about Bundle of His. The preceptor provides correct teaching by stating:', '[{"id": "a", "text": "It represents normal atrial repolarization."}, {"id": "b", "text": "It is characterized strictly by an absent QRS."}, {"id": "c", "text": "It always requires synchronized cardioversion."}, {"id": "d", "text": "It involves pathway to left and right bundle branches and leads to Purkinje Fibers."}]'::jsonb, '["d"]', 'Bundle of His involves pathway to left and right bundle branches and leads to Purkinje Fibers. ventricles contract.', 'EKG', false, 40, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'When analyzing the cardiac conduction system, which component accurately reflects Depolarization?', 'When analyzing the cardiac conduction system, which component accurately reflects Depolarization?', '[{"id": "a", "text": "Toward a lead = bump UP; Away = dip DOWN alone without Na+ enters cell"}, {"id": "b", "text": "charge goes negative to positive only"}, {"id": "c", "text": "Na+ enters cell, which charge goes negative to positive, and Toward a lead = bump UP; Away = dip DOWN"}, {"id": "d", "text": "An irregular rate without Na+ enters cell"}]'::jsonb, '["c"]', 'Depolarization is associated with Na+ enters cell. It charge goes negative to positive, and Toward a lead = bump UP; Away = dip DOWN.', 'EKG', false, 41, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'The nurse is evaluating an ECG strip and identifies characteristics of Repolarization. Which finding confirms this?', 'The nurse is evaluating an ECG strip and identifies characteristics of Repolarization. Which finding confirms this?', '[{"id": "a", "text": "positive to negative but with opposing Toward lead = dip DOWN; Away = bump UP"}, {"id": "b", "text": "An inverted T wave with shortened PR"}, {"id": "c", "text": "cell resets"}, {"id": "d", "text": "Complete absence of P waves"}]'::jsonb, '["c"]', 'The key characteristic of Repolarization is cell resets. positive to negative may also be seen.', 'EKG', false, 42, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A client''s rhythm strip demonstrates features of P Wave. What is the priority nursing intervention or key finding?', 'A client''s rhythm strip demonstrates features of P Wave. What is the priority nursing intervention or key finding?', '[{"id": "a", "text": "Ignore the rhythm as it is an artifact"}, {"id": "b", "text": "Administer epinephrine immediately"}, {"id": "c", "text": "Perform unsynchronized defibrillation"}, {"id": "d", "text": "2\u20132.5 small boxes"}]'::jsonb, '["d"]', 'For P Wave, the key finding/intervention is 2–2.5 small boxes. It Atrial depolarization and 0.08–0.10 sec.', 'EKG', false, 43, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'Which statement regarding PR Interval is correct based on standard ECG analysis?', 'Which statement regarding PR Interval is correct based on standard ECG analysis?', '[{"id": "a", "text": "It indicates normal ventricular repolarization"}, {"id": "b", "text": "It is defined by 0.12\u20130.20 sec"}, {"id": "c", "text": "It is represented by SA to AV node conduction time but only when >150 bpm"}, {"id": "d", "text": "It requires immediate defibrillation regardless of pulse"}]'::jsonb, '["b"]', 'Characteristics of PR Interval include: SA to AV node conduction time. It 0.12–0.20 sec.', 'EKG', false, 44, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A novice nurse is asking about PR Segment. The preceptor provides correct teaching by stating:', 'A novice nurse is asking about PR Segment. The preceptor provides correct teaching by stating:', '[{"id": "a", "text": "It is characterized strictly by an absent QRS."}, {"id": "b", "text": "It involves AV node delay and 0.04\u20130.12 sec."}, {"id": "c", "text": "It represents normal atrial repolarization."}, {"id": "d", "text": "It always requires synchronized cardioversion."}]'::jsonb, '["b"]', 'PR Segment involves AV node delay and 0.04–0.12 sec. 1–3 small boxes.', 'EKG', false, 45, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'When analyzing the cardiac conduction system, which component accurately reflects QRS Complex?', 'When analyzing the cardiac conduction system, which component accurately reflects QRS Complex?', '[{"id": "a", "text": "An irregular rate without Ventricular depolarization"}, {"id": "b", "text": "Ventricular depolarization, which <0.12 sec (narrow), and >0.12 sec is wide/abnormal"}, {"id": "c", "text": ">0.12 sec is wide/abnormal alone without Ventricular depolarization"}, {"id": "d", "text": "<0.12 sec (narrow) only"}]'::jsonb, '["b"]', 'QRS Complex is associated with Ventricular depolarization. It <0.12 sec (narrow), and >0.12 sec is wide/abnormal.', 'EKG', false, 46, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'The nurse is evaluating an ECG strip and identifies characteristics of T Wave. Which finding confirms this?', 'The nurse is evaluating an ECG strip and identifies characteristics of T Wave. Which finding confirms this?', '[{"id": "a", "text": "Complete absence of P waves"}, {"id": "b", "text": "An inverted T wave with shortened PR"}, {"id": "c", "text": "variable 0.10\u20130.25 sec but with opposing "}, {"id": "d", "text": "Ventricular repolarization"}]'::jsonb, '["d"]', 'The key characteristic of T Wave is Ventricular repolarization. variable 0.10–0.25 sec may also be seen.', 'EKG', false, 47, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A client''s rhythm strip demonstrates features of U Wave. What is the priority nursing intervention or key finding?', 'A client''s rhythm strip demonstrates features of U Wave. What is the priority nursing intervention or key finding?', '[{"id": "a", "text": "Administer epinephrine immediately"}, {"id": "b", "text": "Perform unsynchronized defibrillation"}, {"id": "c", "text": "None of the above"}, {"id": "d", "text": "Ignore the rhythm as it is an artifact"}]'::jsonb, '["c"]', 'For U Wave, the key finding/intervention is . It Not always present and may indicate hypokalemia.', 'EKG', false, 48, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'Which statement regarding Cardioversion is correct based on standard ECG analysis?', 'Which statement regarding Cardioversion is correct based on standard ECG analysis?', '[{"id": "a", "text": "It indicates normal ventricular repolarization"}, {"id": "b", "text": "It is defined by LOW energy, SYNC ON (R wave)"}, {"id": "c", "text": "It requires immediate defibrillation regardless of pulse"}, {"id": "d", "text": "It is represented by Patient HAS a pulse but only when >150 bpm"}]'::jsonb, '["b"]', 'Characteristics of Cardioversion include: Patient HAS a pulse. It LOW energy, SYNC ON (R wave).', 'EKG', false, 49, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A novice nurse is asking about Defibrillation. The preceptor provides correct teaching by stating:', 'A novice nurse is asking about Defibrillation. The preceptor provides correct teaching by stating:', '[{"id": "a", "text": "It is characterized strictly by an absent QRS."}, {"id": "b", "text": "It always requires synchronized cardioversion."}, {"id": "c", "text": "It represents normal atrial repolarization."}, {"id": "d", "text": "It involves Patient has NO pulse and HIGH energy, SYNC OFF (immediate)."}]'::jsonb, '["d"]', 'Defibrillation involves Patient has NO pulse and HIGH energy, SYNC OFF (immediate). V-Fib, pulseless V-Tach. Needs CPR.', 'EKG', false, 50, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'The nurse is analyzing an ECG strip and notes criteria consistent with SA Node. Which of the following statements apply? (Select all that apply)', 'The nurse is analyzing an ECG strip and notes criteria consistent with SA Node. Which of the following statements apply? (Select all that apply)', '[{"id": "a", "text": "fires at 60-100 bpm"}, {"id": "b", "text": "sends wave through atria"}, {"id": "c", "text": "It is treated with high-dose atropine"}, {"id": "d", "text": "It always presents as wide QRS"}, {"id": "e", "text": "pacemaker of the heart"}]'::jsonb, '["a", "b", "e"]', 'SA Node features include pacemaker of the heart, fires at 60-100 bpm, and sends wave through atria.', 'EKG', true, 51, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A client is at risk for complications related to AV Node. Which of the following are clinical facts the nurse should remember? (Select all that apply)', 'A client is at risk for complications related to AV Node. Which of the following are clinical facts the nurse should remember? (Select all that apply)', '[{"id": "a", "text": "It requires immediate chest compressions"}, {"id": "b", "text": "It gatekeeper"}, {"id": "c", "text": "It strictly indicates a first-degree block"}, {"id": "d", "text": "The key indicator is before ventricles contract"}, {"id": "e", "text": "It involves pauses signal to let atria dump blood"}]'::jsonb, '["b", "d", "e"]', 'For AV Node, it gatekeeper and involves pauses signal to let atria dump blood. Additionally, before ventricles contract.', 'EKG', true, 52, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'When educating a client about Bundle of His, the nurse should include which points? (Select all that apply)', 'When educating a client about Bundle of His, the nurse should include which points? (Select all that apply)', '[{"id": "a", "text": "It is generally defined by leads to Purkinje Fibers."}, {"id": "b", "text": "It indicates normal repolarization."}, {"id": "c", "text": "The condition involves pathway to left and right bundle branches."}, {"id": "d", "text": "It demonstrates a flatline."}, {"id": "e", "text": "It ventricles contract."}]'::jsonb, '["a", "c", "e"]', 'Teaching for Bundle of His should include: pathway to left and right bundle branches, leads to Purkinje Fibers, and ventricles contract.', 'EKG', true, 53, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'An assessment of Depolarization on the ECG grid reveals which associated findings? (Select all that apply)', 'An assessment of Depolarization on the ECG grid reveals which associated findings? (Select all that apply)', '[{"id": "a", "text": "Na+ enters cell"}, {"id": "b", "text": "charge goes negative to positive"}, {"id": "c", "text": "Usually benign with no intervention"}, {"id": "d", "text": "Pacing spikes follow the T wave"}, {"id": "e", "text": "Related factor: Toward a lead = bump UP; Away = dip DOWN"}]'::jsonb, '["a", "b", "e"]', 'Depolarization is associated with Na+ enters cell and charge goes negative to positive. Furthermore, Toward a lead = bump UP; Away = dip DOWN.', 'EKG', true, 54, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'The nurse is analyzing an ECG strip and notes criteria consistent with Repolarization. Which of the following statements apply? (Select all that apply)', 'The nurse is analyzing an ECG strip and notes criteria consistent with Repolarization. Which of the following statements apply? (Select all that apply)', '[{"id": "a", "text": "positive to negative"}, {"id": "b", "text": "Toward lead = dip DOWN; Away = bump UP"}, {"id": "c", "text": "cell resets"}, {"id": "d", "text": "It is treated with high-dose atropine"}, {"id": "e", "text": "It always presents as wide QRS"}]'::jsonb, '["a", "b", "c"]', 'Repolarization features include cell resets, positive to negative, and Toward lead = dip DOWN; Away = bump UP.', 'EKG', true, 55, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A client is at risk for complications related to P Wave. Which of the following are clinical facts the nurse should remember? (Select all that apply)', 'A client is at risk for complications related to P Wave. Which of the following are clinical facts the nurse should remember? (Select all that apply)', '[{"id": "a", "text": "It strictly indicates a first-degree block"}, {"id": "b", "text": "The key indicator is 2\u20132.5 small boxes"}, {"id": "c", "text": "It requires immediate chest compressions"}, {"id": "d", "text": "It Atrial depolarization"}, {"id": "e", "text": "It involves 0.08\u20130.10 sec"}]'::jsonb, '["b", "d", "e"]', 'For P Wave, it Atrial depolarization and involves 0.08–0.10 sec. Additionally, 2–2.5 small boxes.', 'EKG', true, 56, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'When educating a client about PR Interval, the nurse should include which points? (Select all that apply)', 'When educating a client about PR Interval, the nurse should include which points? (Select all that apply)', '[{"id": "a", "text": "It demonstrates a flatline."}, {"id": "b", "text": "The condition involves SA to AV node conduction time."}, {"id": "c", "text": "It 3\u20135 small boxes."}, {"id": "d", "text": "It is generally defined by 0.12\u20130.20 sec."}, {"id": "e", "text": "It indicates normal repolarization."}]'::jsonb, '["b", "c", "d"]', 'Teaching for PR Interval should include: SA to AV node conduction time, 0.12–0.20 sec, and 3–5 small boxes.', 'EKG', true, 57, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'An assessment of PR Segment on the ECG grid reveals which associated findings? (Select all that apply)', 'An assessment of PR Segment on the ECG grid reveals which associated findings? (Select all that apply)', '[{"id": "a", "text": "0.04\u20130.12 sec"}, {"id": "b", "text": "Pacing spikes follow the T wave"}, {"id": "c", "text": "Related factor: 1\u20133 small boxes"}, {"id": "d", "text": "Usually benign with no intervention"}, {"id": "e", "text": "AV node delay"}]'::jsonb, '["a", "c", "e"]', 'PR Segment is associated with AV node delay and 0.04–0.12 sec. Furthermore, 1–3 small boxes.', 'EKG', true, 58, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'The nurse is analyzing an ECG strip and notes criteria consistent with QRS Complex. Which of the following statements apply? (Select all that apply)', 'The nurse is analyzing an ECG strip and notes criteria consistent with QRS Complex. Which of the following statements apply? (Select all that apply)', '[{"id": "a", "text": ">0.12 sec is wide/abnormal"}, {"id": "b", "text": "It is treated with high-dose atropine"}, {"id": "c", "text": "It always presents as wide QRS"}, {"id": "d", "text": "Ventricular depolarization"}, {"id": "e", "text": "<0.12 sec (narrow)"}]'::jsonb, '["a", "d", "e"]', 'QRS Complex features include Ventricular depolarization, <0.12 sec (narrow), and >0.12 sec is wide/abnormal.', 'EKG', true, 59, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A client is at risk for complications related to T Wave. Which of the following are clinical facts the nurse should remember? (Select all that apply)', 'A client is at risk for complications related to T Wave. Which of the following are clinical facts the nurse should remember? (Select all that apply)', '[{"id": "a", "text": "It requires immediate chest compressions"}, {"id": "b", "text": "It strictly indicates a first-degree block"}, {"id": "c", "text": "The key indicator is ventricular repolarization"}, {"id": "d", "text": "It involves a variable duration of 0.10\u20130.25 sec"}, {"id": "e", "text": "It reflects ventricular repolarization"}]'::jsonb, '["c", "d", "e"]', 'For the T wave, key facts are that it reflects ventricular repolarization and has a variable duration of about 0.10–0.25 sec.', 'EKG', true, 60, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'When educating a client about U Wave, the nurse should include which points? (Select all that apply)', 'When educating a client about U Wave, the nurse should include which points? (Select all that apply)', '[{"id": "a", "text": "The condition involves a wave that is not always present."}, {"id": "b", "text": "It demonstrates a flatline."}, {"id": "c", "text": "It may become more prominent in electrolyte disturbances."}, {"id": "d", "text": "It indicates normal repolarization."}, {"id": "e", "text": "It may indicate hypokalemia."}]'::jsonb, '["a", "c", "e"]', 'Teaching for the U wave should include that it is not always present, may indicate hypokalemia, and may become more prominent with electrolyte disturbances.', 'EKG', true, 61, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'An assessment of Cardioversion on the ECG grid reveals which associated findings? (Select all that apply)', 'An assessment of Cardioversion on the ECG grid reveals which associated findings? (Select all that apply)', '[{"id": "a", "text": "Related factor: SVT, A-Fib, A-Flutter, V-Tach with pulse"}, {"id": "b", "text": "Patient HAS a pulse"}, {"id": "c", "text": "Usually benign with no intervention"}, {"id": "d", "text": "Pacing spikes follow the T wave"}, {"id": "e", "text": "LOW energy, SYNC ON (R wave)"}]'::jsonb, '["a", "b", "e"]', 'Cardioversion is associated with Patient HAS a pulse and LOW energy, SYNC ON (R wave). Furthermore, SVT, A-Fib, A-Flutter, V-Tach with pulse.', 'EKG', true, 62, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'The nurse is analyzing an ECG strip and notes criteria consistent with Defibrillation. Which of the following statements apply? (Select all that apply)', 'The nurse is analyzing an ECG strip and notes criteria consistent with Defibrillation. Which of the following statements apply? (Select all that apply)', '[{"id": "a", "text": "It always presents as wide QRS"}, {"id": "b", "text": "HIGH energy, SYNC OFF (immediate)"}, {"id": "c", "text": "V-Fib, pulseless V-Tach. Needs CPR"}, {"id": "d", "text": "It is treated with high-dose atropine"}, {"id": "e", "text": "Patient has NO pulse"}]'::jsonb, '["b", "c", "e"]', 'Defibrillation features include Patient has NO pulse, HIGH energy, SYNC OFF (immediate), and V-Fib, pulseless V-Tach. Needs CPR.', 'EKG', true, 63, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A client is at risk for complications related to Grid Paper Speed. Which of the following are clinical facts the nurse should remember? (Select all that apply)', 'A client is at risk for complications related to Grid Paper Speed. Which of the following are clinical facts the nurse should remember? (Select all that apply)', '[{"id": "a", "text": "It is 25 mm/sec"}, {"id": "b", "text": "It requires immediate chest compressions"}, {"id": "c", "text": "It involves standard ECG paper speed"}, {"id": "d", "text": "The key indicator is 25 mm/sec"}, {"id": "e", "text": "It strictly indicates a first-degree block"}]'::jsonb, '["a", "c", "d"]', 'For grid paper speed, key points are that standard ECG speed is 25 mm/sec and this setting is used for routine interpretation.', 'EKG', true, 64, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'When educating a client about Small Box, the nurse should include which points? (Select all that apply)', 'When educating a client about Small Box, the nurse should include which points? (Select all that apply)', '[{"id": "a", "text": "It QRS width, P-wave duration."}, {"id": "b", "text": "It is generally defined by 1 mm width."}, {"id": "c", "text": "It demonstrates a flatline."}, {"id": "d", "text": "It indicates normal repolarization."}, {"id": "e", "text": "The condition involves 0.04 s."}]'::jsonb, '["a", "b", "e"]', 'Teaching for Small Box should include: 0.04 s, 1 mm width, and QRS width, P-wave duration.', 'EKG', true, 65, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'An assessment of Large Box on the ECG grid reveals which associated findings? (Select all that apply)', 'An assessment of Large Box on the ECG grid reveals which associated findings? (Select all that apply)', '[{"id": "a", "text": "5 small boxes"}, {"id": "b", "text": "Usually benign with no intervention"}, {"id": "c", "text": "Pacing spikes follow the T wave"}, {"id": "d", "text": "0.20 s"}, {"id": "e", "text": "Related factor: PR interval, QRS duration"}]'::jsonb, '["a", "d", "e"]', 'Large Box is associated with 0.20 s and 5 small boxes. Furthermore, PR interval, QRS duration.', 'EKG', true, 66, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'The nurse is analyzing an ECG strip and notes criteria consistent with One Second. Which of the following statements apply? (Select all that apply)', 'The nurse is analyzing an ECG strip and notes criteria consistent with One Second. Which of the following statements apply? (Select all that apply)', '[{"id": "a", "text": "HR Calculation"}, {"id": "b", "text": "It is treated with high-dose atropine"}, {"id": "c", "text": "1.00 s"}, {"id": "d", "text": "It always presents as wide QRS"}, {"id": "e", "text": "5 large boxes"}]'::jsonb, '["a", "c", "e"]', 'One Second features include 1.00 s, 5 large boxes, and HR Calculation.', 'EKG', true, 67, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A client is at risk for complications related to Heart Rate: Regular. Which of the following are clinical facts the nurse should remember? (Select all that apply)', 'A client is at risk for complications related to Heart Rate: Regular. Which of the following are clinical facts the nurse should remember? (Select all that apply)', '[{"id": "a", "text": "The key indicator is the number of large boxes between two R-wave peaks"}, {"id": "b", "text": "It uses the 300 \u00f7 large boxes method"}, {"id": "c", "text": "It requires immediate chest compressions"}, {"id": "d", "text": "It strictly indicates a first-degree block"}, {"id": "e", "text": "It involves counting between two R-wave peaks"}]'::jsonb, '["a", "b", "e"]', 'For a regular heart rate, use the 300 ÷ large boxes method by counting the large boxes between two R-wave peaks.', 'EKG', true, 68, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'When educating a client about Heart Rate: Irregular, the nurse should include which points? (Select all that apply)', 'When educating a client about Heart Rate: Irregular, the nurse should include which points? (Select all that apply)', '[{"id": "a", "text": "It is generally assessed in a 6-second strip (30 large boxes)."}, {"id": "b", "text": "It indicates normal repolarization."}, {"id": "c", "text": "It is often estimated using the QRS count × 10 method."}, {"id": "d", "text": "It demonstrates a flatline."}, {"id": "e", "text": "The condition involves QRS count × 10."}]'::jsonb, '["a", "c", "e"]', 'Teaching for irregular heart rate should include using a 6-second strip (30 large boxes) and estimating rate by QRS count × 10.', 'EKG', true, 69, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'An assessment of Heart Rate: Quick on the ECG grid reveals which associated findings? (Select all that apply)', 'An assessment of Heart Rate: Quick on the ECG grid reveals which associated findings? (Select all that apply)', '[{"id": "a", "text": "Memorization rule"}, {"id": "b", "text": "Related factor: countdown sequence from 300"}, {"id": "c", "text": "Pacing spikes follow the T wave"}, {"id": "d", "text": "Usually benign with no intervention"}, {"id": "e", "text": "300, 150, 100, 75, 60, 50"}]'::jsonb, '["a", "b", "e"]', 'The quick heart-rate method uses the memorized sequence 300, 150, 100, 75, 60, 50 counted from the R-wave alignment.', 'EKG', true, 70, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'The nurse is analyzing an ECG strip and notes criteria consistent with Normal Sinus Rhythm. Which of the following statements apply? (Select all that apply)', 'The nurse is analyzing an ECG strip and notes criteria consistent with Normal Sinus Rhythm. Which of the following statements apply? (Select all that apply)', '[{"id": "a", "text": "60-100 bpm"}, {"id": "b", "text": "No treatment needed"}, {"id": "c", "text": "It is treated with high-dose atropine"}, {"id": "d", "text": "It always presents as wide QRS"}, {"id": "e", "text": "Regular rhythm, consistent P waves, PR 0.12-0.20"}]'::jsonb, '["a", "b", "e"]', 'Normal Sinus Rhythm features include 60-100 bpm, Regular rhythm, consistent P waves, PR 0.12-0.20, and No treatment needed.', 'EKG', true, 71, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A client is at risk for complications related to Sinus Bradycardia. Which of the following are clinical facts the nurse should remember? (Select all that apply)', 'A client is at risk for complications related to Sinus Bradycardia. Which of the following are clinical facts the nurse should remember? (Select all that apply)', '[{"id": "a", "text": "It requires immediate chest compressions"}, {"id": "b", "text": "It strictly indicates a first-degree block"}, {"id": "c", "text": "It <60 bpm"}, {"id": "d", "text": "The key indicator is Symptomatic: Atropine. Asymptomatic: Monitor"}, {"id": "e", "text": "It involves Regular, normal P waves"}]'::jsonb, '["c", "d", "e"]', 'For Sinus Bradycardia, it <60 bpm and involves Regular, normal P waves. Additionally, Symptomatic: Atropine. Asymptomatic: Monitor.', 'EKG', true, 72, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'When educating a client about Sinus Tachycardia, the nurse should include which points? (Select all that apply)', 'When educating a client about Sinus Tachycardia, the nurse should include which points? (Select all that apply)', '[{"id": "a", "text": "It indicates normal repolarization."}, {"id": "b", "text": "It Calcium Channel Blockers, Beta-Blockers, Digoxin."}, {"id": "c", "text": "It is generally defined by Regular, normal P."}, {"id": "d", "text": "The condition involves 100-150 bpm."}, {"id": "e", "text": "It demonstrates a flatline."}]'::jsonb, '["b", "c", "d"]', 'Teaching for Sinus Tachycardia should include: 100-150 bpm, Regular, normal P, and Calcium Channel Blockers, Beta-Blockers, Digoxin.', 'EKG', true, 73, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'An assessment of SVT on the ECG grid reveals which associated findings? (Select all that apply)', 'An assessment of SVT on the ECG grid reveals which associated findings? (Select all that apply)', '[{"id": "a", "text": ">150 bpm"}, {"id": "b", "text": "Usually benign with no intervention"}, {"id": "c", "text": "Regular, narrow QRS, P hidden"}, {"id": "d", "text": "Related factor: Vagal Maneuver -> Adenosine IV -> Cardioversion"}, {"id": "e", "text": "Pacing spikes follow the T wave"}]'::jsonb, '["a", "c", "d"]', 'SVT is associated with >150 bpm and Regular, narrow QRS, P hidden. Furthermore, Vagal Maneuver -> Adenosine IV -> Cardioversion.', 'EKG', true, 74, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'The nurse is analyzing an ECG strip and notes criteria consistent with Atrial Flutter. Which of the following statements apply? (Select all that apply)', 'The nurse is analyzing an ECG strip and notes criteria consistent with Atrial Flutter. Which of the following statements apply? (Select all that apply)', '[{"id": "a", "text": "Anticoagulants, Beta-Blockers, Cardioversion"}, {"id": "b", "text": "250-350 bpm (atria)"}, {"id": "c", "text": "It always presents as wide QRS"}, {"id": "d", "text": "It is treated with high-dose atropine"}, {"id": "e", "text": "Sawtooth F waves"}]'::jsonb, '["a", "b", "e"]', 'Atrial Flutter features include 250-350 bpm (atria), Sawtooth F waves, and Anticoagulants, Beta-Blockers, Cardioversion.', 'EKG', true, 75, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A client is at risk for complications related to Atrial Fibrillation. Which of the following are clinical facts the nurse should remember? (Select all that apply)', 'A client is at risk for complications related to Atrial Fibrillation. Which of the following are clinical facts the nurse should remember? (Select all that apply)', '[{"id": "a", "text": "The key indicator is Anticoagulants, Rate/Rhythm control"}, {"id": "b", "text": "It involves Wavy/chaotic baseline, no distinct P"}, {"id": "c", "text": "It strictly indicates a first-degree block"}, {"id": "d", "text": "It requires immediate chest compressions"}, {"id": "e", "text": "It Irregular rate"}]'::jsonb, '["a", "b", "e"]', 'For Atrial Fibrillation, it Irregular rate and involves Wavy/chaotic baseline, no distinct P. Additionally, Anticoagulants, Rate/Rhythm control.', 'EKG', true, 76, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'When educating a client about V-Tach, the nurse should include which points? (Select all that apply)', 'When educating a client about V-Tach, the nurse should include which points? (Select all that apply)', '[{"id": "a", "text": "It demonstrates a flatline."}, {"id": "b", "text": "It is generally defined by Wide, bizarre QRS, no P."}, {"id": "c", "text": "It Pulse: Cardiovert. No Pulse: Defib + CPR."}, {"id": "d", "text": "It indicates normal repolarization."}, {"id": "e", "text": "The condition involves 100-250 bpm."}]'::jsonb, '["b", "c", "e"]', 'Teaching for V-Tach should include: 100-250 bpm, Wide, bizarre QRS, no P, and Pulse: Cardiovert. No Pulse: Defib + CPR.', 'EKG', true, 77, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'An assessment of V-Fib on the ECG grid reveals which associated findings? (Select all that apply)', 'An assessment of V-Fib on the ECG grid reveals which associated findings? (Select all that apply)', '[{"id": "a", "text": "Pacing spikes follow the T wave"}, {"id": "b", "text": "Related factor: Defibrillation (unsync), CPR, Epi, Amiodarone"}, {"id": "c", "text": "No effective pulse"}, {"id": "d", "text": "Chaotic, no QRS/P"}, {"id": "e", "text": "Usually benign with no intervention"}]'::jsonb, '["b", "c", "d"]', 'V-Fib is associated with No effective pulse and Chaotic, no QRS/P. Furthermore, Defibrillation (unsync), CPR, Epi, Amiodarone.', 'EKG', true, 78, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'The nurse is analyzing an ECG strip and notes criteria consistent with PVCs. Which of the following statements apply? (Select all that apply)', 'The nurse is analyzing an ECG strip and notes criteria consistent with PVCs. Which of the following statements apply? (Select all that apply)', '[{"id": "a", "text": "It is treated with high-dose atropine"}, {"id": "b", "text": "It always presents as wide QRS"}, {"id": "c", "text": "3+ in row = V-Tach. Check electrolytes"}, {"id": "d", "text": "Occasional irregular beat"}, {"id": "e", "text": "Wide bizarre QRS, no preceding P"}]'::jsonb, '["c", "d", "e"]', 'PVCs features include Occasional irregular beat, Wide bizarre QRS, no preceding P, and 3+ in row = V-Tach. Check electrolytes.', 'EKG', true, 79, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A client is at risk for complications related to 1st Degree AV Block. Which of the following are clinical facts the nurse should remember? (Select all that apply)', 'A client is at risk for complications related to 1st Degree AV Block. Which of the following are clinical facts the nurse should remember? (Select all that apply)', '[{"id": "a", "text": "It requires immediate chest compressions"}, {"id": "b", "text": "It strictly indicates a first-degree block"}, {"id": "c", "text": "It 60-100 bpm"}, {"id": "d", "text": "The key indicator is No treatment needed"}, {"id": "e", "text": "It involves Prolonged PR (>0.20)"}]'::jsonb, '["c", "d", "e"]', 'For 1st Degree AV Block, it 60-100 bpm and involves Prolonged PR (>0.20). Additionally, No treatment needed.', 'EKG', true, 80, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'When educating a client about 2nd Degree Type I, the nurse should include which points? (Select all that apply)', 'When educating a client about 2nd Degree Type I, the nurse should include which points? (Select all that apply)', '[{"id": "a", "text": "It is generally defined by PR progressively lengthens until QRS dropped."}, {"id": "b", "text": "It demonstrates a flatline."}, {"id": "c", "text": "It Pacemaker needed."}, {"id": "d", "text": "The condition involves Variable rate."}, {"id": "e", "text": "It indicates normal repolarization."}]'::jsonb, '["a", "c", "d"]', 'Teaching for 2nd Degree Type I should include: Variable rate, PR progressively lengthens until QRS dropped, and Pacemaker needed.', 'EKG', true, 81, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'An assessment of 2nd Degree Type II on the ECG grid reveals which associated findings? (Select all that apply)', 'An assessment of 2nd Degree Type II on the ECG grid reveals which associated findings? (Select all that apply)', '[{"id": "a", "text": "Usually benign with no intervention"}, {"id": "b", "text": "30-50 bpm"}, {"id": "c", "text": "Constant PR, dropped QRS"}, {"id": "d", "text": "Related factor: Pacemaker required urgently"}, {"id": "e", "text": "Pacing spikes follow the T wave"}]'::jsonb, '["b", "c", "d"]', '2nd Degree Type II is associated with 30-50 bpm and Constant PR, dropped QRS. Furthermore, Pacemaker required urgently.', 'EKG', true, 82, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'The nurse is analyzing an ECG strip and notes criteria consistent with 3rd Degree Block. Which of the following statements apply? (Select all that apply)', 'The nurse is analyzing an ECG strip and notes criteria consistent with 3rd Degree Block. Which of the following statements apply? (Select all that apply)', '[{"id": "a", "text": "30-40 bpm"}, {"id": "b", "text": "It is treated with high-dose atropine"}, {"id": "c", "text": "It always presents as wide QRS"}, {"id": "d", "text": "P and QRS completely independent"}, {"id": "e", "text": "Emergency pacemaker required"}]'::jsonb, '["a", "d", "e"]', '3rd Degree Block features include 30-40 bpm, P and QRS completely independent, and Emergency pacemaker required.', 'EKG', true, 83, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A client is at risk for complications related to Artificial Pacemaker. Which of the following are clinical facts the nurse should remember? (Select all that apply)', 'A client is at risk for complications related to Artificial Pacemaker. Which of the following are clinical facts the nurse should remember? (Select all that apply)', '[{"id": "a", "text": "It Regular paced rate"}, {"id": "b", "text": "The key indicator is Normal or wide QRS"}, {"id": "c", "text": "It requires immediate chest compressions"}, {"id": "d", "text": "It strictly indicates a first-degree block"}, {"id": "e", "text": "It involves Pacing spikes before P or QRS"}]'::jsonb, '["a", "b", "e"]', 'For Artificial Pacemaker, it Regular paced rate and involves Pacing spikes before P or QRS. Additionally, Normal or wide QRS.', 'EKG', true, 84, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'When educating a client about Asystole, the nurse should include which points? (Select all that apply)', 'When educating a client about Asystole, the nurse should include which points? (Select all that apply)', '[{"id": "a", "text": "It CPR + Epi. Confirm in 2 leads."}, {"id": "b", "text": "It demonstrates a flatline."}, {"id": "c", "text": "It is generally defined by Flat line. Non-shockable."}, {"id": "d", "text": "It indicates normal repolarization."}, {"id": "e", "text": "The condition involves No HR."}]'::jsonb, '["a", "c", "e"]', 'Teaching for Asystole should include: No HR, Flat line. Non-shockable, and CPR + Epi. Confirm in 2 leads.', 'EKG', true, 85, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'An assessment of Torsades de Pointes on the ECG grid reveals which associated findings? (Select all that apply)', 'An assessment of Torsades de Pointes on the ECG grid reveals which associated findings? (Select all that apply)', '[{"id": "a", "text": "Usually benign with no intervention"}, {"id": "b", "text": "Pacing spikes follow the T wave"}, {"id": "c", "text": "Related factor: IV Magnesium Sulfate"}, {"id": "d", "text": "QRS twists around baseline"}, {"id": "e", "text": ">200 bpm"}]'::jsonb, '["c", "d", "e"]', 'Torsades de Pointes is associated with >200 bpm and QRS twists around baseline. Furthermore, IV Magnesium Sulfate.', 'EKG', true, 86, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'The nurse is analyzing an ECG strip and notes criteria consistent with Cardiac Tamponade. Which of the following statements apply? (Select all that apply)', 'The nurse is analyzing an ECG strip and notes criteria consistent with Cardiac Tamponade. Which of the following statements apply? (Select all that apply)', '[{"id": "a", "text": "It is treated with high-dose atropine"}, {"id": "b", "text": "It always presents as wide QRS"}, {"id": "c", "text": "Electrical Alternans"}, {"id": "d", "text": "PR Segment Depression"}, {"id": "e", "text": "Low Voltage QRS, Sinus Tachy"}]'::jsonb, '["c", "d", "e"]', 'Cardiac Tamponade features include Electrical Alternans, Low Voltage QRS, Sinus Tachy, and PR Segment Depression.', 'EKG', true, 87, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A client is at risk for complications related to SA Node. Which of the following are clinical facts the nurse should remember? (Select all that apply)', 'A client is at risk for complications related to SA Node. Which of the following are clinical facts the nurse should remember? (Select all that apply)', '[{"id": "a", "text": "The key indicator is sends wave through atria"}, {"id": "b", "text": "It involves fires at 60-100 bpm"}, {"id": "c", "text": "It pacemaker of the heart"}, {"id": "d", "text": "It requires immediate chest compressions"}, {"id": "e", "text": "It strictly indicates a first-degree block"}]'::jsonb, '["a", "b", "c"]', 'For SA Node, it pacemaker of the heart and involves fires at 60-100 bpm. Additionally, sends wave through atria.', 'EKG', true, 88, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'When educating a client about AV Node, the nurse should include which points? (Select all that apply)', 'When educating a client about AV Node, the nurse should include which points? (Select all that apply)', '[{"id": "a", "text": "It is generally defined by pauses signal to let atria dump blood."}, {"id": "b", "text": "The condition involves gatekeeper."}, {"id": "c", "text": "It demonstrates a flatline."}, {"id": "d", "text": "It before ventricles contract."}, {"id": "e", "text": "It indicates normal repolarization."}]'::jsonb, '["a", "b", "d"]', 'Teaching for AV Node should include: gatekeeper, pauses signal to let atria dump blood, and before ventricles contract.', 'EKG', true, 89, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'An assessment of Bundle of His on the ECG grid reveals which associated findings? (Select all that apply)', 'An assessment of Bundle of His on the ECG grid reveals which associated findings? (Select all that apply)', '[{"id": "a", "text": "leads to Purkinje Fibers"}, {"id": "b", "text": "pathway to left and right bundle branches"}, {"id": "c", "text": "Pacing spikes follow the T wave"}, {"id": "d", "text": "Related factor: ventricles contract"}, {"id": "e", "text": "Usually benign with no intervention"}]'::jsonb, '["a", "b", "d"]', 'Bundle of His is associated with pathway to left and right bundle branches and leads to Purkinje Fibers. Furthermore, ventricles contract.', 'EKG', true, 90, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'The nurse is analyzing an ECG strip and notes criteria consistent with Depolarization. Which of the following statements apply? (Select all that apply)', 'The nurse is analyzing an ECG strip and notes criteria consistent with Depolarization. Which of the following statements apply? (Select all that apply)', '[{"id": "a", "text": "It is treated with high-dose atropine"}, {"id": "b", "text": "It always presents as wide QRS"}, {"id": "c", "text": "Na+ enters cell"}, {"id": "d", "text": "Toward a lead = bump UP; Away = dip DOWN"}, {"id": "e", "text": "charge goes negative to positive"}]'::jsonb, '["c", "d", "e"]', 'Depolarization features include Na+ enters cell, charge goes negative to positive, and Toward a lead = bump UP; Away = dip DOWN.', 'EKG', true, 91, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A client is at risk for complications related to Repolarization. Which of the following are clinical facts the nurse should remember? (Select all that apply)', 'A client is at risk for complications related to Repolarization. Which of the following are clinical facts the nurse should remember? (Select all that apply)', '[{"id": "a", "text": "It cell resets"}, {"id": "b", "text": "It strictly indicates a first-degree block"}, {"id": "c", "text": "The key indicator is Toward lead = dip DOWN; Away = bump UP"}, {"id": "d", "text": "It involves positive to negative"}, {"id": "e", "text": "It requires immediate chest compressions"}]'::jsonb, '["a", "c", "d"]', 'For Repolarization, it cell resets and involves positive to negative. Additionally, Toward lead = dip DOWN; Away = bump UP.', 'EKG', true, 92, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'When educating a client about P Wave, the nurse should include which points? (Select all that apply)', 'When educating a client about P Wave, the nurse should include which points? (Select all that apply)', '[{"id": "a", "text": "The condition involves Atrial depolarization."}, {"id": "b", "text": "It demonstrates a flatline."}, {"id": "c", "text": "It 2\u20132.5 small boxes."}, {"id": "d", "text": "It is generally defined by 0.08\u20130.10 sec."}, {"id": "e", "text": "It indicates normal repolarization."}]'::jsonb, '["a", "c", "d"]', 'Teaching for P Wave should include: Atrial depolarization, 0.08–0.10 sec, and 2–2.5 small boxes.', 'EKG', true, 93, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'An assessment of PR Interval on the ECG grid reveals which associated findings? (Select all that apply)', 'An assessment of PR Interval on the ECG grid reveals which associated findings? (Select all that apply)', '[{"id": "a", "text": "SA to AV node conduction time"}, {"id": "b", "text": "Usually benign with no intervention"}, {"id": "c", "text": "Pacing spikes follow the T wave"}, {"id": "d", "text": "Related factor: 3\u20135 small boxes"}, {"id": "e", "text": "0.12\u20130.20 sec"}]'::jsonb, '["a", "d", "e"]', 'PR Interval is associated with SA to AV node conduction time and 0.12–0.20 sec. Furthermore, 3–5 small boxes.', 'EKG', true, 94, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'The nurse is analyzing an ECG strip and notes criteria consistent with PR Segment. Which of the following statements apply? (Select all that apply)', 'The nurse is analyzing an ECG strip and notes criteria consistent with PR Segment. Which of the following statements apply? (Select all that apply)', '[{"id": "a", "text": "It is treated with high-dose atropine"}, {"id": "b", "text": "0.04\u20130.12 sec"}, {"id": "c", "text": "It always presents as wide QRS"}, {"id": "d", "text": "AV node delay"}, {"id": "e", "text": "1\u20133 small boxes"}]'::jsonb, '["b", "d", "e"]', 'PR Segment features include AV node delay, 0.04–0.12 sec, and 1–3 small boxes.', 'EKG', true, 95, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A client is at risk for complications related to QRS Complex. Which of the following are clinical facts the nurse should remember? (Select all that apply)', 'A client is at risk for complications related to QRS Complex. Which of the following are clinical facts the nurse should remember? (Select all that apply)', '[{"id": "a", "text": "It requires immediate chest compressions"}, {"id": "b", "text": "It involves <0.12 sec (narrow)"}, {"id": "c", "text": "The key indicator is >0.12 sec is wide/abnormal"}, {"id": "d", "text": "It Ventricular depolarization"}, {"id": "e", "text": "It strictly indicates a first-degree block"}]'::jsonb, '["b", "c", "d"]', 'For QRS Complex, it Ventricular depolarization and involves <0.12 sec (narrow). Additionally, >0.12 sec is wide/abnormal.', 'EKG', true, 96, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'When educating a client about T Wave, the nurse should include which points? (Select all that apply)', 'When educating a client about T Wave, the nurse should include which points? (Select all that apply)', '[{"id": "a", "text": "It demonstrates a flatline."}, {"id": "b", "text": "It indicates normal repolarization."}, {"id": "c", "text": "The condition involves ventricular repolarization."}, {"id": "d", "text": "It typically follows the QRS complex."}, {"id": "e", "text": "It is generally defined by a variable duration of 0.10\u20130.25 sec."}]'::jsonb, '["c", "d", "e"]', 'Teaching for the T wave should include that it reflects ventricular repolarization and has a variable duration of approximately 0.10–0.25 sec.', 'EKG', true, 97, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'An assessment of U Wave on the ECG grid reveals which associated findings? (Select all that apply)', 'An assessment of U Wave on the ECG grid reveals which associated findings? (Select all that apply)', '[{"id": "a", "text": "May indicate hypokalemia"}, {"id": "b", "text": "Not always present"}, {"id": "c", "text": "Related factor: can become prominent with electrolyte imbalance"}, {"id": "d", "text": "Pacing spikes follow the T wave"}, {"id": "e", "text": "Usually benign with no intervention"}]'::jsonb, '["a", "b", "c"]', 'U waves are not always present and may indicate hypokalemia, especially when they become prominent with electrolyte imbalance.', 'EKG', true, 98, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'The nurse is analyzing an ECG strip and notes criteria consistent with Cardioversion. Which of the following statements apply? (Select all that apply)', 'The nurse is analyzing an ECG strip and notes criteria consistent with Cardioversion. Which of the following statements apply? (Select all that apply)', '[{"id": "a", "text": "LOW energy, SYNC ON (R wave)"}, {"id": "b", "text": "It always presents as wide QRS"}, {"id": "c", "text": "SVT, A-Fib, A-Flutter, V-Tach with pulse"}, {"id": "d", "text": "It is treated with high-dose atropine"}, {"id": "e", "text": "Patient HAS a pulse"}]'::jsonb, '["a", "c", "e"]', 'Cardioversion features include Patient HAS a pulse, LOW energy, SYNC ON (R wave), and SVT, A-Fib, A-Flutter, V-Tach with pulse.', 'EKG', true, 99, 1, true);
  INSERT INTO test_questions (test_id, topic_id, question, question_stem, options, correct_answer, rationale, category, is_multiple_choice, display_order, points, is_active)
  VALUES (test_id, topic_id, 'A client is at risk for complications related to Defibrillation. Which of the following are clinical facts the nurse should remember? (Select all that apply)', 'A client is at risk for complications related to Defibrillation. Which of the following are clinical facts the nurse should remember? (Select all that apply)', '[{"id": "a", "text": "It strictly indicates a first-degree block"}, {"id": "b", "text": "The key indicator is V-Fib, pulseless V-Tach. Needs CPR"}, {"id": "c", "text": "It involves HIGH energy, SYNC OFF (immediate)"}, {"id": "d", "text": "It Patient has NO pulse"}, {"id": "e", "text": "It requires immediate chest compressions"}]'::jsonb, '["b", "c", "d"]', 'For Defibrillation, it Patient has NO pulse and involves HIGH energy, SYNC OFF (immediate). Additionally, V-Fib, pulseless V-Tach. Needs CPR.', 'EKG', true, 100, 1, true);

END $$;
COMMIT;
