-- Insert subscribers in bulk, skipping anyone already in students or student_waiting_list
INSERT INTO subscribers (first_name, last_name, full_name, email, status)
SELECT
  c.first_name,
  c.last_name,
  c.full_name,
  lower(c.email),
  'active'
FROM (VALUES
  ('Vardan',    'Yeranosyan',      'Vardan Yeranosyan',           'vardanyeranosyan@yahoo.com'),
  ('Arevik',    'Harutyunyan',     'Arevik Harutyunyan',          'areviksmart@gmail.com'),
  ('Mariam',    'Abelyan',         'Mariam Abelyan',              'abelyanmariam97@gmail.com'),
  ('Robert',    'Zakaryan',        'Robert Zakaryan',             'ofeliminasyan89@gmail.com'),
  ('Azat',      'Abramyan',        'Azat Abramyan',               'azatabramyan@yahoo.com'),
  ('Lia',       'Ghazarian',       'Lia Ghazarian',               'liaghazarian1@gmail.com'),
  ('Srbui',     'Babayan',         'Srbui Babayan',               'srbui81@gmail.com'),
  ('Valentina', 'Sookassians',     'Valentina Sookassians',       'vsookassians@yahoo.com'),
  ('Ani',       'Lepedzhyan',      'Ani Lepedzhyan',              'anilepedzhyan@yahoo.com'),
  ('Armenuhi',  'Yeganyan',        'Armenuhi Yeganyan',           'armushik80@yahoo.fr'),
  ('Manvel',    'Chakmanyan',      'Manvel Chakmanyan',           'chakmanianmd@gmail.com'),
  ('Anna',      'Ohanjanyan',      'Anna Ohanjanyan',             'pv.annaohanjanyan@gmail.com'),
  ('Ani',       'Arakelyan',       'Ani Arakelyan',               'aniarakelyan1982@gmail.com'),
  ('Meri',      'Hovhanyan',       'Meri Hovhanyan',              'maryhovhanyan@yahoo.com'),
  ('Anna',      'Margaryan',       'Anna Margaryan',              'annalilit.30@gmail.com'),
  ('Sirarpi',   'Khachikyan',      'Sirarpi Khachikyan',          'sirarpi.khachikian@yahoo.com'),
  ('Mariam',    'Matevosyan',      'Mariam Matevosyan',           'mashamat20@gmail.com'),
  ('Mariam',    'Karakiyan',       'Mariam Karakiyan',            'marjoytar@gmail.com'),
  ('Ruzan',     'Galstyan',        'Ruzan Galstyan',              'ruzangalstyan@yahoo.com'),
  ('Lusine',    'Kalashyan',       'Lusine Kalashyan',            'l.kalashyan@acnhs.am'),
  ('Tereza',    'Abramyan',        'Tereza Abramyan',             'tereza07@yahoo.com'),
  ('Maria',     'Aghabalyan',      'Maria Aghabalyan',            'maaghabalyan@gmail.com'),
  ('Armen',     'Kalents',         'Armen Kalents',               'armenkalents@gmail.com'),
  ('Emil',      'Sargisyan',       'Emil Sargisyan',              'esargisyan@icloud.com'),
  ('Mari',      'Melkonyan',       'Mari Melkonyan',              'mmelkonyan20@gmail.com'),
  ('Sona',      'Husikyan',        'Sona Husikyan',               'shusikyan@gmail.com'),
  ('Anahit',    'Hovhannisyan',    'Anahit Hovhannisyan',         'anahit3434@gmail.com'),
  ('Christina', 'Grigorian',       'Christina Grigorian',         'grigorianc15@yahoo.com'),
  ('Marine',    'Martirosyan',     'Marine Martirosyan',          'marina.kirakosyan2023@gmail.com'),
  ('Hasmik',    'Antonova',        'Hasmik Antonova',             'hasmik.antonova@gmail.com'),
  ('Yelena',    'Mirijanyan',      'Yelena Mirijanyan',           'mirijanyanelena@gmail.com'),
  ('Vladislav', 'Saakyan',         'Vladislav Saakyan',           'vladarkadich@gmail.com'),
  ('Zaruhi',    'Arakelyan',       'Zaruhi Arakelyan',            'zaraarakelyan@hotmail.com'),
  ('Meri',      'Mkhitaryan',      'Meri Mkhitaryan',             'merimkhitaryan1987@gmail.com'),
  ('Milena',    'Terteryan',       'Milena Terteryan',            'terteryan.milenaa@gmail.com'),
  ('Lusine',    'Beglaryan',       'Lusine Beglaryan',            'lusine1122@icloud.com'),
  ('Gayane',    'Zadourian',       'Gayane Zadourian',            'g.zadourian@acnhs.am'),
  ('Lusine',    'Gevorgyan',       'Lusine Gevorgyan',            'lusinegevorgyan1969@gmail.com'),
  ('Elizabeth', 'Andoyan',         'Elizabeth Andoyan',           'eandoyan8@gmail.com'),
  ('Kristina',  'Simonyan',        'Kristina Simonyan',           'karenog74@gmail.com'),
  ('Syuzanna',  'Minasyan',        'Syuzanna Minasyan',           'minasyansyuzi@yahoo.com'),
  ('Ofelya',    'Minasyan',        'Ofelya Minasyan',             'ofeliminasyan@yahoo.com'),
  ('Tamara',    'Akopyan',         'Tamara Akopyan',              'akopiant@yahoo.com'),
  ('Inesa',     'Avetisyan',       'Inesa Avetisyan',             'avetisyan.inesa0118@gmail.com'),
  ('Susanna',   'Muradian',        'Susanna Muradian',            'susannamuradyan@yahoo.com'),
  ('Lilit',     'Najaryan',        'Lilit Najaryan',              'lilit.najaryan@gmail.com'),
  ('Ani',       'Abovian',         'Ani Ezabela Abovian',         'aboviana22@gmail.com'),
  ('Ashkhen',   'Adamyan',         'Ashkhen Adamyan',             'ashkhen1020@gmail.com'),
  ('Diana',     'Dallakyan',       'Diana Dallakyan',             'dianadallvn@gmail.com'),
  ('Narine',    'Tigranyan',       'Narine Tigranyan',            'narinetigranyan89@gmail.com'),
  ('Hayk',      'Yeranosyan',      'Hayk Yeranosyan',             'haykyeranosyan@yahoo.com'),
  ('Alvard',    'Ghukasyan',       'Alvard Ghukasyan',            'alvard85@yahoo.com'),
  ('Hermine',   'Muradyan',        'Hermine Muradyan',            'hemo.muradyan84@gmail.com'),
  ('Meri',      'Hakobyan',        'Meri Hakobyan',               'meryhakobyann@gmail.com'),
  ('Hrachuhi',  'Asatryan',        'Hrachuhi Asatryan',           'h.asatryan101@gmail.com'),
  ('Arevik',    'Arutyunyan',      'Arevik Angela Arutyunyan',    'arevika21@hotmail.com'),
  ('Gohar',     'Hovhannisyan',    'Gohar Hovhannisyan',          'gohar1983@yahoo.com'),
  ('Arpine',    'Ktratsyan',       'Arpine Ktratsyan',            'arpushka1985@gmail.com'),
  ('Zhaklen',   'Akopyan',         'Zhaklen Akopyan',             'zna07@yahoo.com'),
  ('Narine',    'Jamalyan',        'Narine Jamalyan',             'narinejamalyan83@gmail.com'),
  ('Lusine',    'Hakobyan',        'Lusine Hakobyan',             'hakobyanl26@gmail.com'),
  ('Lusine',    'Hovhannisyan',    'Lusine Hovhannisyan',         'lusine.h@yahoo.com'),
  ('Arpi',      'Atabekyan',       'Arpi Atabekyan',              'arpiatabekyan@yahoo.com'),
  ('Mariam',    'Davtyan',         'Mariam Davtyan',              'hellomari@ymail.com'),
  ('Anaeis',    'Baghoomian',      'Anaeis Baghoomian',           'anaisbaghumian@gmail.com'),
  ('Gohar',     'Arakelyan',       'Gohar Arakelyan',             'gohararakelyaniphone@gmail.com'),
  ('Hrachya',   'Yeranosyan',      'Hrachya Yeranosyan',          'yeranosyanhrach962@yahoo.com'),
  ('Varduhi',   'Nersesyan',       'Varduhi Nersesyan',           'varduhi1982@yahoo.com'),
  ('Narine',    'Avetisyan',       'Narine Avetisyan',            'narineavetisyan7788@gmail.com'),
  ('Gohar',     'Ilangyozyan',     'Gohar Ilangyozyan',           'gia.ilangyozyan@gmail.com'),
  ('Lusine',    'Tumasyan',        'Lusine Tumasyan',             'tumasyanlusine91@gmail.com')
) AS c(first_name, last_name, full_name, email)
WHERE lower(c.email) NOT IN (
  SELECT lower(email) FROM students          WHERE email IS NOT NULL
)
AND lower(c.email) NOT IN (
  SELECT lower(email) FROM student_waiting_list WHERE email IS NOT NULL
)
AND lower(c.email) NOT IN (
  SELECT lower(email) FROM subscribers       WHERE email IS NOT NULL
);
